//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "CBCentralManagerDelegate.h"
#import "LocationRetrieveDelegate.h"
#import "PBMessageObserverDelegate.h"
#import "UIAlertViewDelegate.h"

@class CBCentralManager, CLLocation, DeviceInfoData, LocationRetriever, MMTimer, NSString, WCCardDataCardInfo, WCCardDataCardTPInfo;

@interface AccessCardLogicController : MMObject <CBCentralManagerDelegate, LocationRetrieveDelegate, PBMessageObserverDelegate, UIAlertViewDelegate>
{
    MMTimer *_uploadTimer;
    CBCentralManager *_centralManager;
    DeviceInfoData *_foundDeviceWithMaxRSSI;
    _Bool _deviceInfoHasChanged;
    _Bool _deviceForceUpdate;
    NSString *_cardID;
    WCCardDataCardInfo *_cardInfo;
    WCCardDataCardTPInfo *_cardTPInfo;
    LocationRetriever *_locationRetriver;
    CLLocation *_curLocation;
    _Bool _locationHasChanged;
    _Bool _bIsBleScanning;
    _Bool _hasTurnedOnBluetooth;
    _Bool _hasAuthorizeLocation;
    _Bool _bIsShowingAlert;
    double _timerInterval;
    _Bool _bIsAlreadyShowLocationSwitchOff;
    id <AccessCardLogicDelegate> _m_delegate;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)alertConfirmRetriveLocation;
- (void)alertRefuseRetriveLocation;
- (void)centralManager:(id)arg1 didDiscoverPeripheral:(id)arg2 advertisementData:(id)arg3 RSSI:(id)arg4;
- (void)centralManagerDidUpdateState:(id)arg1;
- (void)dealloc;
- (void)doUplaodAction;
- (id)initWithCardID:(id)arg1 andCardInfo:(id)arg2 andCardTPInfo:(id)arg3;
@property(nonatomic) __weak id <AccessCardLogicDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
- (void)makeUploadRequest;
- (void)onResponseProcess:(id)arg1;
- (void)onRetrieveLocationError:(int)arg1;
- (void)onRetrieveLocationOK:(id)arg1;
- (void)onRetrieveLocationTimeOut:(id)arg1;
- (void)realScanBLE;
- (void)reportLocationWithLocation:(id)arg1 ErrorCode:(long long)arg2;
- (void)startRetriveLocation;
- (void)stopRetriveLocation;
- (void)tryStart;
- (void)tryStartBLELogic;
- (void)tryStartLocationLogic;
- (void)tryStop;
- (void)tryStopBLELogic;
- (void)tryStopLocationLogic;
- (void)tryStopUploadDataLogic;
- (void)tryUploadDataLogic;
- (void)updateWithCardID:(id)arg1 andCardInfo:(id)arg2 andCardTPInfo:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

