//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MyCamGPUFilter.h"

@interface AlphaFilter : MyCamGPUFilter
{
    int widthUniform;
    int heightUniform;
    int matUniform;
}

- (id)init;
- (id)initWithTag:(int)arg1;
- (void)renderToTextureWithVertices:(const float *)arg1 textureCoordinates:(const float *)arg2;
- (void)setProperty:(id)arg1 value:(id)arg2;

@end

