//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSString;

@interface AudioRecorderUserData : NSObject <NSCopying>
{
    unsigned int _createtime;
    unsigned int _audioid;
    unsigned int _duration;
    unsigned int _inputId;
    unsigned int _errorCode;
    NSString *_fromusr;
    NSString *_tousr;
    NSString *_chatname;
    NSString *_msgSource;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int audioid; // @synthesize audioid=_audioid;
@property(retain) NSString *chatname; // @synthesize chatname=_chatname;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property unsigned int createtime; // @synthesize createtime=_createtime;
@property unsigned int duration; // @synthesize duration=_duration;
@property unsigned int errorCode; // @synthesize errorCode=_errorCode;
@property(retain) NSString *fromusr; // @synthesize fromusr=_fromusr;
@property unsigned int inputId; // @synthesize inputId=_inputId;
@property(copy) NSString *msgSource; // @synthesize msgSource=_msgSource;
@property(retain) NSString *tousr; // @synthesize tousr=_tousr;

@end

