//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BaseStyle : NSObject
{
    struct CGRect _frame;
    _Bool _bUserInteractionEnabled;
    _Bool _endOfContent;
    struct _NSRange _range;
}

@property(nonatomic) _Bool bUserInteractionEnabled; // @synthesize bUserInteractionEnabled=_bUserInteractionEnabled;
- (void)drawInContext:(struct CGContext *)arg1;
@property(nonatomic) _Bool endOfContent; // @synthesize endOfContent=_endOfContent;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
- (id)init;
@property(nonatomic) struct _NSRange range; // @synthesize range=_range;

@end

