//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface BaseFilterParam : NSObject
{
    NSString *_type;
    NSString *_name;
    NSString *_value;
    NSDictionary *_rawDict;
}

+ (id)createNoneModel;
+ (id)parseDictionary:(id)arg1;
- (void).cxx_destruct;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSDictionary *rawDict; // @synthesize rawDict=_rawDict;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *value; // @synthesize value=_value;

@end

