//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface BaseFilterModel : NSObject
{
    long long _baseFilterId;
    long long _index;
    NSMutableArray *_params;
}

+ (id)createNoneModel;
+ (id)parseDictionnary:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) long long baseFilterId; // @synthesize baseFilterId=_baseFilterId;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
@property(nonatomic) long long index; // @synthesize index=_index;
- (id)init;
- (id)initWithCoder:(id)arg1;
@property(retain, nonatomic) NSMutableArray *params; // @synthesize params=_params;

@end

