//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIViewController;

@protocol BaseScanLogicDelegate <NSObject>

@optional
- (void)didShowScanResult;
- (float)getBottomBarHeight;
- (struct CGRect)getContentRect;
- (UIViewController *)getMainViewController;
- (double)getZoomFactor;
- (void)onGetA8KeyResultType:(unsigned int)arg1;
- (void)onPlaySound;
- (void)onPopViewControllerCount:(int)arg1 animated:(_Bool)arg2;
- (void)onPushViewContoller:(UIViewController *)arg1 animated:(_Bool)arg2;
- (void)onScanCodeFinish;
- (void)onScanEnds;
- (void)onScanInUnreachableNetworkStatus;
- (void)onScanRequestTimeout;
- (void)onSetCameraZoomFactor:(double)arg1;
- (void)onShowAlertWording;
- (void)onStartLoading;
- (void)onStartScanAnimation;
- (void)onStopLoading;
- (void)onStopScanAnimation;
- (void)onUpdateWording;
@end

