//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface BluetoothInfo : MMObject
{
    unsigned long long _uploadTimeInterval;
    NSString *_peripheralName;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(retain, nonatomic) NSString *peripheralName; // @synthesize peripheralName=_peripheralName;
@property(nonatomic) unsigned long long uploadTimeInterval; // @synthesize uploadTimeInterval=_uploadTimeInterval;

@end

