//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ForwardMessageLogicDelegate.h"
#import "IDeviceRankProfileMgrExt.h"
#import "IDeviceRankSnsMgrExt.h"
#import "MMImagePickerManagerDelegate.h"
#import "MMSightCameraViewControllerDelegate.h"
#import "MMWebImageViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WCActionSheetDelegate.h"

@class BraceletRankStepsView, BraceletRankUtils, DeviceRankDetailResonse, ForwardMessageLogicController, MMHeadImageView, MMTableView, MMUIImageView, MMUILabel, MMWebImageView, NSArray, NSMutableArray, NSString, NSURL, UIButton, UIImage, UIImageView, UILabel, UIScrollView, UIView;

@interface BraceletRankProfileViewController : MMUIViewController <MMSightCameraViewControllerDelegate, MMImagePickerManagerDelegate, IDeviceRankProfileMgrExt, WCActionSheetDelegate, MMWebImageViewDelegate, UITableViewDataSource, UITableViewDelegate, IDeviceRankSnsMgrExt, ForwardMessageLogicDelegate>
{
    NSString *nsUserName;
    NSString *nsBrandUserName;
    NSArray *arrAffectedUser;
    DeviceRankDetailResonse *_oDataSource;
    NSURL *_coverUrl;
    NSMutableArray *_sectionDatas;
    NSMutableArray *_stepDatas;
    NSString *_stepCacheFilePath;
    int _cacheDistance;
    MMTableView *_tableView;
    MMWebImageView *_coverWebImageView;
    UIImageView *_cameraImageView;
    MMUILabel *_tipLablel;
    UILabel *_headTipLabel;
    UILabel *_nickNameLabel;
    MMHeadImageView *_headImageView;
    UIView *_affectTipView;
    UIScrollView *_affectedUserListView;
    UIView *_tableHeaderView;
    UIView *_tableFooterView;
    UIButton *_followBtn;
    UIImageView *_followedBut;
    BraceletRankStepsView *_stepView;
    MMUIImageView *_reverseImageView;
    UIImageView *_blurView;
    UIImage *_snapShotImg;
    UIImage *_shareBGImage;
    _Bool _bCoverChanged;
    _Bool _bMySelf;
    _Bool _isBluring;
    _Bool _bDidBePushed;
    _Bool _bIsNotifySetCover;
    ForwardMessageLogicController *_forwardMsgLogic;
    BraceletRankUtils *_braceletRankUtils;
    id <BraceletRankProfileViewControllerDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)MMImagePickerManager:(id)arg1 didFinishPickingImageWithInfo:(id)arg2;
- (void)MMImagePickerManagerDidCancel:(id)arg1;
- (void)OnForwardMessageCancel:(id)arg1;
- (void)OnForwardMessageSend:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(retain, nonatomic) NSArray *arrAffectedUser; // @synthesize arrAffectedUser;
- (id)braceletRankUtils;
- (void)clickAffectedImage:(id)arg1;
- (void)dealAffectUserViewState:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <BraceletRankProfileViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)getAffectTipView;
- (id)getAffectUserListView;
- (void)getAllStepsFromNow;
- (id)getCurrentViewController;
- (id)getHeaderImgUrl;
- (id)getMyselfHeadImageData;
- (id)getNotRankTitle;
- (double)getTableViewBgHeight;
- (void)initData;
- (void)initTableFooterView;
- (void)initView;
- (id)initWithUserName:(id)arg1 withBrandUserName:(id)arg2 AffectedUserList:(id)arg3;
- (_Bool)launchDonateStepWAApp;
- (void)loadCacheStepData;
- (void)makeAddFollowCell:(id)arg1;
- (void)makeButtonCell:(id)arg1 row:(unsigned long long)arg2;
- (void)makeFollowCell:(id)arg1 row:(unsigned long long)arg2;
- (void)makeSectionSpaCell:(id)arg1 section:(unsigned long long)arg2;
- (void)makeStepsCell:(id)arg1;
- (void)mergeLocalStep;
- (void)notifyEmptyCoverIfNeed;
@property(retain, nonatomic) NSString *nsBrandUserName; // @synthesize nsBrandUserName;
@property(retain, nonatomic) NSString *nsUserName; // @synthesize nsUserName;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)onAddFollow;
- (void)onAddFollowWithFollowItems:(id)arg1 error:(int)arg2;
- (void)onAffectTipSingleTap:(id)arg1;
- (void)onClickHeadImage;
- (void)onDelFollow;
- (void)onDelFollowWithUserName:(id)arg1 error:(int)arg2;
- (void)onDoneForwardForForwardView:(id)arg1;
- (void)onGotStepListWithBeginTime:(unsigned int)arg1 endTime:(unsigned int)arg2 stepArray:(id)arg3 err:(int)arg4;
- (void)onGotUserRankDetail:(id)arg1 rankDetailResp:(id)arg2 err:(int)arg3;
- (void)onHandleImage:(id)arg1;
- (void)onLikeFriendRank:(id)arg1 optype:(unsigned int)arg2 err:(int)arg3;
- (void)onLoadImageOK:(id)arg1;
- (void)onNotRank;
- (void)onReport;
- (void)onRightNavBtnClickedInProfile;
- (void)onRightNavBtnClickedInSelfProfile;
- (void)onSightPictureTaken:(id)arg1 imageData:(id)arg2 withFrontCamera:(_Bool)arg3 editImageAttr:(id)arg4;
- (void)onSingleTap;
- (void)reloadData;
- (void)reloadRowData;
- (void)scrollViewDidScroll:(id)arg1;
- (void)shareToFriend;
- (void)shareToTimeline;
- (_Bool)shouldShowRightBarItem;
- (void)showImagePicker:(long long)arg1;
- (void)showNotRankActionSheet;
- (void)slashCameraImage:(int)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (void)updateCoverImageView;
- (void)updateHeadImageView;
- (void)updateInfoViewSnapshot;
- (void)updateReverseImage:(id)arg1;
- (void)updateRightNavBarItem;
- (void)updateTableBgView;
- (void)updateTableFooterView;
- (void)updateTableHeaderView;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewDidBePushed:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

