//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "BTBaseItemCellViewDelegate.h"
#import "BTMsgSectionDataDelegate.h"
#import "BTNotifyMsgCellViewDelegate.h"
#import "BTOftenReadBarViewCellDelegate.h"
#import "BrandArticleSearchControllerDelegate.h"
#import "BrandTimelineMsgMgrExt.h"
#import "BrandTimelineNotifyLogicDelegate.h"
#import "BrandTimelineReportLogicDelegate.h"
#import "IContactMgrExt.h"
#import "MMRefreshTableFooterDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UIViewControllerPreviewingDelegate.h"
#import "WCActionSheetDelegate.h"
#import "contactInfoDelegate.h"
#import "tableViewDelegate.h"

@class BrandArticleSearchController, BrandTimelineNotifyLogic, BrandTimelineReportLogic, CContact, CMessageWrap, MMTableView, MMTimer, NSIndexSet, NSMutableArray, NSMutableSet, NSString, UIButton, UIView, WCTimeLineFooterView;

@interface BrandTimelineViewController : MMUIViewController <BrandArticleSearchControllerDelegate, MMRefreshTableFooterDelegate, BrandTimelineMsgMgrExt, IContactMgrExt, UIViewControllerPreviewingDelegate, BrandTimelineNotifyLogicDelegate, BrandTimelineReportLogicDelegate, BTNotifyMsgCellViewDelegate, BTBaseItemCellViewDelegate, WCActionSheetDelegate, BTMsgSectionDataDelegate, contactInfoDelegate, BTOftenReadBarViewCellDelegate, UITableViewDelegate, UITableViewDataSource, tableViewDelegate>
{
    BrandArticleSearchController *m_articleSearchController;
    UIView *m_searchBarMaskView;
    struct CGPoint m_topContentOffset;
    MMTableView *m_tableView;
    WCTimeLineFooterView *m_footerView;
    UIButton *m_navNewTipsBtn;
    UIView *m_navDefaultTitleView;
    unsigned int m_navBarNewMsgCount;
    unsigned int m_newMsgCountInBgCacheTime;
    unsigned long long m_topLastNewMsgSequenceId;
    unsigned long long m_newMsgDividingLineSequenceId;
    MMTimer *m_msgRefreshTimer;
    _Bool m_bLoadingData;
    _Bool m_bAnimatedInsertRowFromTop;
    NSIndexSet *m_animatedInsertSectionSetFromTop;
    _Bool m_bAnimatedInsertRowFromBottom;
    NSIndexSet *m_animatedInsertSectionSetFromBottom;
    id <UIViewControllerPreviewing> _previewingContext;
    _Bool m_isScrollingToTop;
    _Bool m_hasLoadNumberOfTableRow;
    _Bool m_hasViewWillBePushedOnce;
    CContact *_contactToProfile;
    NSMutableSet *m_setFastLoadTemplateType;
    _Bool m_isSingleCellExposeDigest;
    _Bool _isShowRedDotInMainFrameSession;
    _Bool _isPush;
    _Bool _didAppear;
    unsigned int _displayMode;
    unsigned long long _source;
    unsigned long long _enterRowIndexInMainFrameSession;
    CMessageWrap *_enterMsgInMainFrameSession;
    NSMutableArray *_arrSectionData;
    NSMutableArray *_arrTimelineMsg;
    NSMutableArray *_arrTimelineMsgToAdd;
    BrandTimelineNotifyLogic *_notifyMsgLogic;
    BrandTimelineReportLogic *_reportLogic;
}

- (void).cxx_destruct;
- (void)MMRefreshTableFooterDidTriggerRefresh:(id)arg1;
- (void)ShowReader:(id)arg1 fromMsgWrap:(id)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)addMsgSectionIfNeed;
- (void)addNotifySectionIfNeed;
- (void)addOftenReadSectionIfNeed:(id)arg1;
- (void)adjustTableViewInset:(id)arg1;
- (void)advanceDownloadNewMsgCoverIfNeed;
- (void)advanceUpdateMPPageData;
- (void)advanceUpdateMPPageDataWithMessage:(id)arg1;
- (void)animatedDisplayCell:(id)arg1 delay:(double)arg2 duration:(double)arg3;
@property(retain, nonatomic) NSMutableArray *arrSectionData; // @synthesize arrSectionData=_arrSectionData;
@property(retain, nonatomic) NSMutableArray *arrTimelineMsg; // @synthesize arrTimelineMsg=_arrTimelineMsg;
@property(retain, nonatomic) NSMutableArray *arrTimelineMsgToAdd; // @synthesize arrTimelineMsgToAdd=_arrTimelineMsgToAdd;
- (void)ayncNotifyEnterChat:(id)arg1;
- (void)brandArticleSearchWillBeginSearch;
- (void)brandArticleSearchWillEndSearch;
- (_Bool)canInsertCellFromTopWithAnimation;
- (void)checkFirstVisibleCell;
- (void)dealloc;
- (void)deleteAllMsg;
@property(nonatomic) _Bool didAppear; // @synthesize didAppear=_didAppear;
@property(nonatomic) unsigned int displayMode; // @synthesize displayMode=_displayMode;
@property(retain, nonatomic) CMessageWrap *enterMsgInMainFrameSession; // @synthesize enterMsgInMainFrameSession=_enterMsgInMainFrameSession;
@property(nonatomic) unsigned long long enterRowIndexInMainFrameSession; // @synthesize enterRowIndexInMainFrameSession=_enterRowIndexInMainFrameSession;
- (_Bool)existNotifySection;
- (id)filterMsgList:(id)arg1;
- (void)footerTryLoadDownMoreMsg;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (id)getContactDisplayNameFromHeaderCell:(id)arg1;
- (id)getContactFromHeaderCell:(id)arg1;
- (id)getNotifySectionData;
- (id)getTitleColor;
- (id)getViewController;
- (id)getWebViewController:(id)arg1 url:(id)arg2 forPeek:(_Bool)arg3 fromMsgWrap:(id)arg4;
- (unsigned long long)indexForFirstMsgSection;
- (unsigned long long)indexForMsgSectionToInsert;
- (unsigned long long)indexForNotifySection;
- (unsigned long long)indexForNotifySectionToInsert;
- (unsigned long long)indexForOftenRead;
- (id)init;
- (void)initData;
- (void)initFooterView;
- (void)initNavigationBar;
- (void)initSearchBar;
- (void)initTableView;
- (void)initView;
- (_Bool)isContactNeedProcess:(id)arg1;
- (_Bool)isMsgWrapExist:(id)arg1;
@property(nonatomic) _Bool isPush; // @synthesize isPush=_isPush;
- (_Bool)isSeachActive;
- (_Bool)isSectionLastNewMsgSection:(long long)arg1;
- (_Bool)isSectionOneDayLastMsgSection:(long long)arg1;
@property(nonatomic) _Bool isShowRedDotInMainFrameSession; // @synthesize isShowRedDotInMainFrameSession=_isShowRedDotInMainFrameSession;
- (_Bool)jumpVideoPageView:(id)arg1 fromMsgWrap:(id)arg2 fromItemView:(id)arg3;
- (void)jumpWeappOpWrap:(id)arg1 fromMsgWrap:(id)arg2;
- (void)layoutNavTipsBtn;
- (unsigned long long)msgIndexForMsg:(id)arg1;
- (unsigned long long)msgIndexFormsgSectionData:(id)arg1;
- (id)msgSectionDataAtIndex:(unsigned long long)arg1;
@property(retain, nonatomic) BrandTimelineNotifyLogic *notifyMsgLogic; // @synthesize notifyMsgLogic=_notifyMsgLogic;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)oftenReadSection;
- (void)onAddBrandTimelineMsg:(id)arg1;
- (void)onBrandItemAudioClick:(id)arg1;
- (void)onClearAllTimelineMsgUnreadStatus;
- (void)onClickHeaderContact:(id)arg1 fromView:(id)arg2;
- (void)onClickHeaderDeleteMsg:(id)arg1 fromView:(id)arg2;
- (void)onClickHeaderLongPress:(id)arg1 fromView:(id)arg2;
- (void)onClickHeaderRemoveContact:(id)arg1 fromView:(id)arg2;
- (void)onClickHeaderTopContact:(id)arg1 fromView:(id)arg2;
- (void)onClickHeaderUnTopContact:(id)arg1 fromView:(id)arg2;
- (void)onClickNavNewTipsBtn;
- (void)onDelBrandTimelineMsg:(id)arg1 msgWrap:(id)arg2;
- (void)onDelBrandTimelineMsgBySession:(id)arg1;
- (void)onLongPressForDebug:(id)arg1;
- (void)onMigrateBrandMsgFinish:(unsigned long long)arg1;
- (void)onModBrandTimelineMsg:(id)arg1;
- (void)onModBrandTimelineMsgArr:(id)arg1;
- (void)onModifyContact:(id)arg1;
- (void)onMsgSectionHeightChange:(id)arg1;
- (void)onNavBackBarButtonClicked;
- (void)onNotifyMsgCellViewClicked;
- (void)onNotifyMsgCountChange:(unsigned int)arg1;
- (void)onOftenReadBarView:(id)arg1 didClickItemView:(id)arg2;
- (void)onOftenReadBarView:(id)arg1 exposeItemViewArr:(id)arg2;
- (void)onPreviewMsgImg:(id)arg1 originFrame:(struct CGRect)arg2 fromView:(id)arg3;
- (void)onReloadItemView:(id)arg1;
- (void)onScrollToTop;
- (void)onShowUnFinishedView;
- (void)onUpateOftenReadBiz:(id)arg1;
- (void)openContactSession:(id)arg1 fromOftenRead:(_Bool)arg2;
- (void)openReaderWrap:(id)arg1 fromMsgWrap:(id)arg2 fromItemView:(id)arg3;
- (void)p_addBrandTimelineMsgArr;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (void)registerPreviewing;
- (void)reloadCellWithCellView:(id)arg1;
- (void)reloadTableView;
- (void)removeOftenReadSection;
@property(retain, nonatomic) BrandTimelineReportLogic *reportLogic; // @synthesize reportLogic=_reportLogic;
- (void)resetOftenReadBarPosition;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (_Bool)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
@property(nonatomic) unsigned long long source; // @synthesize source=_source;
- (void)setVisibleMsgBrowsed;
- (_Bool)shouldDownMoreLoading;
- (_Bool)shouldGoToEmoticonDetail:(id)arg1 fromMsgWrap:(id)arg2;
- (void)showComfirmDeleteActionSheet:(id)arg1 fromHeaderCellView:(id)arg2;
- (void)showConfirmUnsubcribeActionSheet:(id)arg1 fromHeaderCellView:(id)arg2;
- (void)showHeaderActionSheet:(id)arg1 fromHeaderCellView:(id)arg2;
- (void)showMessageList;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)traitCollectionDidChange:(id)arg1;
- (void)tryLoadDownMoreMessageWithInsertAnimation:(_Bool)arg1;
- (void)tryRefreshTimelineItemInfo;
- (void)unfoldTimelineMsg:(id)arg1;
- (void)unregisterPreviewing;
- (void)unsubscribeContact:(id)arg1;
- (void)updateDivdingLinePositionOnViewBePushed;
- (void)updateDivdingLinePositionOnViewDealloc;
- (void)updateLoadingState;
- (void)updateNavigationBarWithNewMsgCount:(unsigned int)arg1;
- (void)updateNewMsgDividingLinePosition:(unsigned long long)arg1 reloadTableView:(_Bool)arg2;
- (void)updateOftenReadBar;
- (void)updateOftenReadBarWithContactArr:(id)arg1;
- (void)updateOneDayLinePosition;
- (void)updateReaderPosInTL;
- (void)updateVisibleCellTime;
- (id)viewControllerForBrandArticleSearch;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewDidBePushed:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillBePoped:(_Bool)arg1;
- (void)viewWillBePushed:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (id)visibleMsgList;
- (id)visibleMsgSectionDataList;
- (id)visibleReaderItemViewModelList;
- (id)webViewExtraInfoWithReaderWrap:(id)arg1 msgWrap:(id)arg2;
- (void)willEnterForeground:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

