//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MyCamGPUFilter.h"

@interface ChannelSharpen : MyCamGPUFilter
{
    float step_width;
}

- (id)init;
- (id)init:(float)arg1;
- (void)newFrameReadyAtTime:(CDStruct_1b6d18a9)arg1 atIndex:(long long)arg2;
- (void)setSharpeness:(float)arg1;
@property(nonatomic) float step_width; // @synthesize step_width;

@end

