//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MyCamGPUFilter.h"

@interface ColorTempFilter : MyCamGPUFilter
{
    double _scaleC;
    double _scaleT;
}

- (id)init;
@property(nonatomic) double scaleC; // @synthesize scaleC=_scaleC;
@property(nonatomic) double scaleT; // @synthesize scaleT=_scaleT;

@end

