//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CContactVerifyLogic, CVerifyContactWrap, NSArray, NSString;

@protocol contactVerifyLogicDelegate <NSObject>

@optional
- (void)contactAddContactOk:(CVerifyContactWrap *)arg1;
- (void)contactSendReplyOk:(CVerifyContactWrap *)arg1;
- (void)contactSendRequestOk:(CVerifyContactWrap *)arg1;
- (void)contactVerifyOk:(NSArray *)arg1;
- (NSString *)getAlertMessageForVerifyLogic:(CContactVerifyLogic *)arg1;
- (NSString *)getAlertTitleForVerifyLogic:(CContactVerifyLogic *)arg1;
- (void)onContactVerifyFail;
- (void)onContactVerifyFillVerifyMsg:(NSArray *)arg1;
@end

