//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CPUImageFilter.h"

@interface CPUGauss : CPUImageFilter
{
    int m_flag;
}

- (void)addWithTexture:(struct _Image *)arg1;
- (id)initWithFlag:(int)arg1;
- (id)main;
- (void)thoseYearCPUFilter:(struct _Image *)arg1;

@end

