//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class EditImageColor, UIView;

@interface EditImageColorDotView : UIControl
{
    UIView *m_dotView;
    EditImageColor *_editColor;
    double _selectedSizeLen;
    double _unselectedSizeLen;
    double _borderWidth;
    long long _expandHitWidth;
    long long _expandHitHeight;
}

- (void).cxx_destruct;
@property(nonatomic) double borderWidth; // @synthesize borderWidth=_borderWidth;
@property(retain, nonatomic) EditImageColor *editColor; // @synthesize editColor=_editColor;
@property(nonatomic) long long expandHitHeight; // @synthesize expandHitHeight=_expandHitHeight;
@property(nonatomic) long long expandHitWidth; // @synthesize expandHitWidth=_expandHitWidth;
- (void)layoutSubviews;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
@property(nonatomic) double selectedSizeLen; // @synthesize selectedSizeLen=_selectedSizeLen;
- (void)setSelected:(_Bool)arg1;
@property(nonatomic) double unselectedSizeLen; // @synthesize unselectedSizeLen=_unselectedSizeLen;

@end

