//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "EditImageColorSquareBarDelegate.h"

@class EditImageColorSquareBar, NSMutableArray, NSString, UIButton, UIColor, UIImageView, UIView;

@interface EditImagePenToolAttrView : MMUIView <EditImageColorSquareBarDelegate>
{
    UIView *colorDot;
    NSMutableArray *_colorArr;
    NSMutableArray *_dotArr;
    int _selectedNumber;
    UIView *_line;
    UIView *_bottomLine;
    UIButton *_undoBtn;
    UIView *_vline;
    _Bool _enable;
    EditImageColorSquareBar *_colorSquareBar;
    UIButton *_lineBtn;
    unsigned long long _lineStyle;
    UIImageView *_lineSelectView;
    UIImageView *_backgroundView;
    UIColor *_selectedColor;
    id <EditImagePenToolAttrDelegate> _m_delegate;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIColor *_selectedColor; // @synthesize _selectedColor;
- (id)getLineColor;
- (double)getLineWidth;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(nonatomic) __weak id <EditImagePenToolAttrDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
- (void)onLineBtnClicked;
- (void)onLineSelect:(id)arg1;
- (void)onUndoEditImage;
- (void)setAlpha:(double)arg1;
- (void)setHidden:(_Bool)arg1;
- (void)setSelectedColorFromSquareBar:(id)arg1;
- (void)setUndoEnable:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

