//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@interface EditVideoReporter : MMObject
{
}

+ (void)editVideoReportCompositionResult:(_Bool)arg1 startTime:(struct timeval)arg2 endTime:(struct timeval)arg3 videoDuration:(unsigned long long)arg4 videoStartTime:(unsigned long long)arg5 videoEndTime:(unsigned long long)arg6;
+ (void)editVideoReportOnEntranceType:(unsigned long long)arg1 withClickBtn:(unsigned long long)arg2 withEditAttr:(id)arg3 withVideoDuration:(unsigned long long)arg4 withCropDuration:(unsigned long long)arg5;

@end

