//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EJJavaScriptView, NSMutableDictionary;

@interface EJRenderTriggerCollection : NSObject
{
    NSMutableDictionary *triggers;
    int lastId;
    EJJavaScriptView *scriptView;
}

- (void)cancelId:(int)arg1;
- (void)dealloc;
- (id)initWithScriptView:(id)arg1;
- (int)scheduleCallback:(struct OpaqueJSValue *)arg1 isMain:(_Bool)arg2;
- (void)update;

@end

