//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSSet, NSString;

@protocol EJTouchDelegate
- (void)triggerEvent:(NSString *)arg1 timestamp:(double)arg2 all:(NSSet *)arg3 changed:(NSSet *)arg4 remaining:(NSSet *)arg5;
@end

