//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseMsgContentLogicController.h"

#import "EnterpriseRoomContactSelectDelegate.h"
#import "IEnterpriseContactMgrExt.h"
#import "IEnterpriseGroupMgrExt.h"
#import "IEnterpriseMsgExt.h"
#import "IEnterpriseSessionMgrExt.h"
#import "MMWebViewDelegate.h"
#import "UIAlertViewDelegate.h"

@class MMLoadingView, NSString;

@interface EnterpriseMsgContentLogicController : BaseMsgContentLogicController <MMWebViewDelegate, IEnterpriseMsgExt, IEnterpriseContactMgrExt, IEnterpriseGroupMgrExt, IEnterpriseSessionMgrExt, UIAlertViewDelegate, EnterpriseRoomContactSelectDelegate>
{
    _Bool m_bStartShowRoomContactSelector;
    _Bool m_bPresentRoomContactSelector;
    MMLoadingView *m_loadingView;
}

- (void).cxx_destruct;
- (void)AddAtUser:(id)arg1;
- (void)AddMsg:(id)arg1 MsgWrap:(id)arg2;
- (_Bool)CanAddApp;
- (_Bool)CanLongPressHeadImage;
- (_Bool)CanOpenCamera;
- (_Bool)CanOpenServiceAppList;
- (_Bool)CanOpenTrackRoom;
- (_Bool)CanRemoteRecord;
- (_Bool)CanRotateOrientation;
- (_Bool)CanSelectMyFavoritesItemForSendingMsg;
- (_Bool)CanSend3rdMsg;
- (_Bool)CanSendEmoticonMessage;
- (_Bool)CanSendImageMsg:(id)arg1;
- (_Bool)CanSendLocationMsg;
- (_Bool)CanSendMultiImage;
- (_Bool)CanSendOriginalImage;
- (_Bool)CanSendShareCard;
- (_Bool)CanSendVideoMsg;
- (_Bool)CanSendVoiceMsg;
- (_Bool)CanSendVoipMsg;
- (_Bool)CanShowBanner;
- (_Bool)CanShowFavorite;
- (_Bool)CanShowLocation;
- (_Bool)CanShowSight;
- (_Bool)CanWXTalk;
- (void)CancelRecording;
- (void)ClearUnRead:(id)arg1 FromID:(unsigned int)arg2 ToID:(unsigned int)arg3;
- (void)CustomToolViewEX:(id)arg1;
- (void)DelMsg:(id)arg1 MsgList:(id)arg2 DelAll:(_Bool)arg3;
- (void)DidEnterBackground:(id)arg1;
- (id)FormImageMsg:(id)arg1 withImage:(id)arg2;
- (id)FormImageMsg:(id)arg1 withImage:(id)arg2 withData:(id)arg3;
- (id)FormImageMsg:(id)arg1 withImage:(id)arg2 withData:(id)arg3 withImageInfo:(id)arg4;
- (id)FormLocationMsg:(id)arg1;
- (id)FormTextMsg:(id)arg1 withText:(id)arg2;
- (id)FormVoiceMsg:(id)arg1 withFilePath:(id)arg2;
- (id)GetContactName;
- (id)GetDownMsg:(id)arg1 FromID:(unsigned int)arg2 Limit:(int)arg3 LeftCount:(unsigned int *)arg4 LeftUnreadCount:(unsigned int *)arg5;
- (id)GetFirstUnReadMessage;
- (id)GetMsg:(id)arg1 FromID:(unsigned int)arg2 Limit:(int)arg3 LeftCount:(unsigned int *)arg4 LeftUnreadCount:(unsigned int *)arg5;
- (id)GetRightBarBtn;
- (id)GetRightBarButtonImageName;
- (_Bool)HasCustomToolBar;
- (_Bool)IsRecording;
- (void)ModImgStatus:(id)arg1 MsgWrap:(id)arg2;
- (void)ModMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)OnAddEnterpriseMsg:(id)arg1 Brand:(id)arg2 WrapMsg:(id)arg3;
- (void)OnAddMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)OnDelMsg:(id)arg1 Brand:(id)arg2 DelAll:(_Bool)arg3;
- (void)OnDelMsg:(id)arg1 Brand:(id)arg2 MsgWrap:(id)arg3;
- (void)OnModEnterpriseMsg:(id)arg1 Brand:(id)arg2 WrapMsg:(id)arg3;
- (void)OpenContactInfo:(id)arg1;
- (void)OpenDetailInfo;
- (void)OpenEmoticonToolView:(id)arg1;
- (void)Register;
- (void)ResendMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)RevokeMsg:(id)arg1;
- (void)SaveContentAndState;
- (void)SendLocationMessageWithLocation:(id)arg1;
- (void)SendTextMessage:(id)arg1;
- (void)SetMsgPlayed:(id)arg1;
- (_Bool)ShouldShowMultiSelectMode;
- (_Bool)ShouldShowSearchBar;
- (_Bool)ShouldShowSearchedAnyMsg;
- (void)StartRecording;
- (void)StopRecording;
- (void)UnRegister;
- (void)ViewDidInit;
- (id)canFavoritesItemBeForward:(id)arg1;
- (_Bool)canShowChatRoomInfo;
- (void)clearAtMeCount;
- (void)clickLinkToDealWithSysXml:(id)arg1 fromScene:(id)arg2;
- (void)createSingleChat:(id)arg1;
- (void)delChatroomMember:(id)arg1;
- (void)didSelectContact:(id)arg1;
- (void)enterChat:(id)arg1;
- (id)formImageMsgByMMAsset:(id)arg1 toUserName:(id)arg2;
- (id)genClientMsgId:(id)arg1;
- (id)genMsgSource;
- (id)getEnterpriseContact;
- (id)getExtraInfo;
- (unsigned int)getSearchedMsgLocalID;
- (void)initViewController;
- (_Bool)isLastCharacterAlphaNumeric:(id)arg1;
- (_Bool)isShowHeadImage:(id)arg1;
- (void)modMsgWithoutNotify:(id)arg1;
- (id)nameForHeadImageLongPressed:(id)arg1;
- (void)onCancelSelectContact;
- (void)onCleanUpEnterpriseChat:(id)arg1;
- (void)onFinishSelectedLocation;
- (id)onGetRightBarButton;
- (void)onInputTextDeleteAll;
- (void)onModifyEnterpriseContact:(id)arg1;
- (void)onSendLocationToFriend:(id)arg1 ViewController:(id)arg2;
- (void)onSessionTotalUnreadCountChange:(unsigned int)arg1;
- (void)onTextChange:(id)arg1 selectedRange:(struct _NSRange)arg2;
- (void)onUpdateEnterpriseGroupMemberList:(id)arg1 errorCode:(int)arg2;
- (void)onWebViewWillClose:(id)arg1;
- (void)onWillPopFromNavigationController;
- (void)onWillPushFromNavigationController;
- (void)setM_contact:(id)arg1;
- (void)setNeedUpdateTitle:(_Bool *)arg1;
- (_Bool)shouldSearchedMsgHightlight;
- (void)showRoomContactSelectorViewController;
- (void)updateTitleView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

