//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface FaceBaseHandle : NSObject
{
    unsigned int _processMode;
    NSData *_dataPack;
    NSString *_bioId;
}

+ (basic_string_90719d97)getConfig:(id)arg1 bioId:(id)arg2;
+ (id)screenshotOfVideoStream:(struct __CVBuffer *)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *bioId; // @synthesize bioId=_bioId;
@property(retain, nonatomic) NSData *dataPack; // @synthesize dataPack=_dataPack;
- (int)engineFaceProcess:(id)arg1;
- (basic_string_90719d97)engineGetCurMotionData;
- (int)engineGetCurrMotion;
- (id)engineGetData;
- (id)engineGetHeaderData;
- (id)engineGetImage:(struct opaqueCMSampleBuffer *)arg1;
- (int)engineNextMotion;
- (int)engineRelease;
- (int)engineReleaseCurrMotion;
- (int)getBestImg:(struct Mat *)arg1 shape:(struct TC_FaceShape *)arg2;
- (void)getLiveData:(GenericDocument_0d39f88c *)arg1;
- (id)initWithConfig:(id)arg1 bioId:(id)arg2;
@property(nonatomic) unsigned int processMode; // @synthesize processMode=_processMode;

@end

