//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FavBaseSearchConfig : NSObject
{
    long long _tableViewStyle;
    double _sectionFooterHeight;
    long long _tableViewSeparatorStyle;
}

@property(nonatomic) double sectionFooterHeight; // @synthesize sectionFooterHeight=_sectionFooterHeight;
@property(nonatomic) long long tableViewSeparatorStyle; // @synthesize tableViewSeparatorStyle=_tableViewSeparatorStyle;
@property(nonatomic) long long tableViewStyle; // @synthesize tableViewStyle=_tableViewStyle;

@end

