//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FavoritesUploadBaseProccessor.h"

@interface FavoritesUploadFileSaver : FavoritesUploadBaseProccessor
{
    int _uploadState;
}

- (_Bool)CountItemDataMD5:(id)arg1 withDataList:(id)arg2;
- (void)addItem:(id)arg1 isPrior:(_Bool)arg2;
- (_Bool)doCopyFileInDataList:(id)arg1;
- (void)onProccessEnd:(_Bool)arg1;
- (void)removeItem:(id)arg1;
- (void)saveCdnInfoOfFavItem:(id)arg1 InDataList:(id)arg2;
@property(nonatomic) int uploadState; // @synthesize uploadState=_uploadState;
- (void)tryProccess;

@end

