//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface FavRemindExtInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *desc; // @dynamic desc;
@property(nonatomic) unsigned int favId; // @dynamic favId;
@property(nonatomic) unsigned int localId; // @dynamic localId;
@property(retain, nonatomic) NSString *title; // @dynamic title;

@end

