//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MyCamGPUFilter.h"

@interface FBBSurfaceOneDim : MyCamGPUFilter
{
}

- (id)init:(int)arg1;
- (void)setInputThreshold:(float)arg1 radius:(int)arg2;

@end

