//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIColor;

@interface FBSDKIcon : NSObject
{
    UIColor *_color;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) UIColor *color; // @synthesize color=_color;
- (id)imageWithSize:(struct CGSize)arg1;
- (id)init;
- (id)initWithColor:(id)arg1;
- (struct CGPath *)pathWithSize:(struct CGSize)arg1;

@end

