//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "FileDetailLogicDelegate.h"
#import "MMCircleProgressViewDelegate.h"
#import "MinimizationTransitionControllerDelegate.h"
#import "UIDocumentInteractionControllerDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UIWebViewDelegate.h"
#import "WCActionSheetDelegate.h"
#import "WKNavigationDelegate.h"

@class FileDetailLogicController, MMCircleProgressView, MMMPMoviePlayerController, MMUILabel, MinimizationTransitionController, NSString, NSURL, ShareDataToOpenSDKController, UIButton, UIDocumentInteractionController, UIImageView, UITapGestureRecognizer, WCActionSheet, WKWebView;

@interface FileDetailViewController : MMUIViewController <WCActionSheetDelegate, FileDetailLogicDelegate, UIDocumentInteractionControllerDelegate, UIScrollViewDelegate, UIGestureRecognizerDelegate, UIWebViewDelegate, WKNavigationDelegate, MMCircleProgressViewDelegate, MinimizationTransitionControllerDelegate>
{
    FileDetailLogicController *m_logicController;
    _Bool m_bDownloading;
    _Bool m_bIsDelayingDownload;
    _Bool m_bFailDownload;
    UIButton *m_btnDownload;
    MMUILabel *m_labCannotOpen;
    UIButton *m_btnViewDetail;
    UIButton *m_btnOpenByApp;
    MMUILabel *m_labelFileName;
    MMUILabel *m_sizeLabel;
    MMUILabel *m_infoLabel;
    UIImageView *m_downloadTriggerView;
    MMCircleProgressView *m_circleProgressView;
    _Bool m_bPreview;
    unsigned int m_uiPreviewType;
    UIDocumentInteractionController *m_vcDocument;
    _Bool m_bOpenMode;
    MMMPMoviePlayerController *_moviePlayerController;
    WCActionSheet *m_actionSheet;
    ShareDataToOpenSDKController *m_shareOpenSDKController;
    WKWebView *m_webView;
    _Bool _bIsNaviBarHide;
    UITapGestureRecognizer *_singleTapRec;
    _Bool _bIsDisableTapRec;
    struct CGPoint m_lastContentOffset;
    UIButton *m_shareToFriendBtn;
    unsigned long long _startDownloadTime;
    unsigned long long _enterTime;
    unsigned long long _quitTime;
    unsigned long long _finishDownloadTime;
    MinimizationTransitionController *_minimizationTransitionController;
    NSURL *m_tmpLinkDestURL;
    _Bool m_showInfoOnly;
    int _minimizeGenerateType;
    NSString *_m_tmpFilePath;
}

- (void).cxx_destruct;
- (id)GetFileDisplayName;
- (void)InitCircleProgressView;
- (void)InitDownload;
- (void)InitInfoiew;
- (void)InitPreview;
- (void)OnLookDetail;
- (void)OnOpenByApp:(id)arg1;
- (void)OnOperate:(id)arg1;
- (void)OnReturn;
- (void)SafeDeleteDocument;
- (void)SetDownloadHide:(_Bool)arg1;
- (void)SetProgressHide:(_Bool)arg1;
- (void)SetProgressPartLen:(unsigned long long)arg1 TotalLen:(unsigned long long)arg2;
- (void)ShowDownloadBtn;
- (void)ShowProgressView;
- (void)StartDownload:(id)arg1;
- (void)StopDownload;
- (void)StopDownloadAndUpdateView;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)addToMinimize;
- (void)circleProgressViewDidTapped:(id)arg1;
- (void)dealloc;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)documentInteractionController:(id)arg1 didEndSendingToApplication:(id)arg2;
- (id)generateExpiredText;
- (_Bool)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (id)getCurrentViewController;
- (id)getToSaveUrl;
- (_Bool)hasPdfView;
- (id)init;
- (void)initCannotOpenLabelIfNeeded;
- (void)initInfoLabel;
- (void)initShareToFriendBtn;
- (void)initSizeLabel;
- (void)installMinimizationTransitionController;
- (_Bool)isAudioPlaying;
- (_Bool)isExceptionFileName:(id)arg1;
- (_Bool)isMinimizeEnable;
- (_Bool)isOnMinimizeState;
- (void)layoutMyViews;
@property(nonatomic) _Bool m_bOpenMode; // @synthesize m_bOpenMode;
@property(nonatomic) _Bool m_showInfoOnly; // @synthesize m_showInfoOnly;
@property(retain, nonatomic) NSString *m_tmpFilePath; // @synthesize m_tmpFilePath=_m_tmpFilePath;
- (void)minimizationInteractivePopGestureRecognizerDidBegin;
- (_Bool)minimizationInteractivePopGestureRecognizerShouldBegin;
- (void)minimizationInteractivePopToMinimizeTask:(_Bool)arg1;
- (id)minimizationTaskData;
- (id)minimizationTransitionController;
@property(nonatomic) int minimizeGenerateType; // @synthesize minimizeGenerateType=_minimizeGenerateType;
- (id)minimizeKey;
- (id)mmNavigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (id)mmNavigationController:(id)arg1 interactionControllerForAnimationController:(id)arg2;
- (id)navigationBarBackgroundColor;
- (void)onCanShareToFriendByButton;
- (void)onDownloadFileFailWithHint:(id)arg1;
- (void)onDownloadFilePartLen:(unsigned int)arg1 TotalLen:(unsigned long long)arg2;
- (void)onDownloadFileSuccess;
- (void)onRevoked;
- (void)onRevokedReturn;
- (void)onSingleTap:(id)arg1;
- (void)pushSelfInNav:(id)arg1 animated:(_Bool)arg2;
- (void)reloadWhenMaximize;
- (void)resetPdfViewFrame;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)setFileFailText:(id)arg1;
- (void)setLogicController:(id)arg1;
- (void)setNaviBarHide:(_Bool)arg1 animation:(_Bool)arg2;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)tryAddToMinimize;
- (void)updateWebScrollViewInset;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewDidBePushed:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)webView:(id)arg1 didCommitNavigation:(id)arg2;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webViewWebContentProcessDidTerminate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

