//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GKImageCropOverlayView.h"

@class GKCropBorderView, UIView;

@interface GKResizeableCropOverlayView : GKImageCropOverlayView
{
    struct CGSize _initialContentSize;
    _Bool _resizingEnabled;
    struct CGPoint _theAnchor;
    struct CGPoint _startPoint;
    CDStruct_09df043f _resizeMultiplyer;
    UIView *_contentView;
    GKCropBorderView *_cropBorderView;
}

- (void).cxx_destruct;
- (void)_addContentViews;
- (struct CGPoint)_calcuateWhichBorderHandleIsTheAnchorPointFromHere:(struct CGPoint)arg1;
- (void)_fillMultiplyer;
- (id)_getAllCurrentHandlePositions;
- (struct CGRect)_preventBorderFrameFromGettingTooSmallOrTooBig:(struct CGRect)arg1;
- (void)_resetFramesToThisOne:(struct CGRect)arg1;
- (void)_resizeWithTouchPoint:(struct CGPoint)arg1;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(readonly, nonatomic) GKCropBorderView *cropBorderView; // @synthesize cropBorderView=_cropBorderView;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 andInitialContentSize:(struct CGSize)arg2;
- (void)setFrame:(struct CGRect)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;

@end

