//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPUImageOutput.h"

@class CALayer, UIView;

@interface GPUImageUIElement : GPUImageOutput
{
    UIView *view;
    CALayer *layer;
    struct CGSize previousLayerSizeInPixels;
    CDStruct_1b6d18a9 time;
    double actualTimeOfLastUpdate;
}

- (void).cxx_destruct;
- (id)initWithLayer:(id)arg1;
- (id)initWithView:(id)arg1;
- (struct CGSize)layerSizeInPixels;
- (void)update;
- (void)updateUsingCurrentTime;
- (void)updateWithTimestamp:(CDStruct_1b6d18a9)arg1;

@end

