//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HFManualFaceHandle.h"

@class NSMutableArray;

@interface HFManualFacePathHandle : HFManualFaceHandle
{
    struct CGPoint topLeft;
    struct CGPoint rightBottom;
    struct _Image *pathImage;
    NSMutableArray *pathPoints;
}

- (void).cxx_destruct;
- (void)createPouchMaskImageWithBrushSize:(int)arg1;
- (void)dealloc;
- (id)init;
- (void)setImage:(id)arg1;
- (struct _Rect)touchArea;
- (void)touchBeganAt:(struct CGPoint)arg1;
- (void)touchEndedAt:(struct CGPoint)arg1;
- (_Bool)touchMovedTo:(struct CGPoint)arg1;

@end

