//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VideoStreamDownloadLogic.h"

#import "ICdnComMgrExt.h"

@class AVAsset, NSString;

@interface HttpVideoStreamDownloadLogic : VideoStreamDownloadLogic <ICdnComMgrExt>
{
    NSString *_url;
    NSString *_filePath;
    NSString *_tempPath;
    AVAsset *_asset;
}

- (void).cxx_destruct;
- (void)OnCdnDownload:(id)arg1;
- (void)OnCdnDownloadPartialData:(id)arg1;
- (void)OnCdnDownloadProgress:(id)arg1;
- (void)OnCdnVideoMoovReady:(id)arg1;
@property(retain, nonatomic) AVAsset *asset; // @synthesize asset=_asset;
- (void)dealloc;
- (void)downloadAllData;
@property(retain, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
- (id)initWithUrl:(id)arg1 filePath:(id)arg2;
- (_Bool)isVideoCacheDataExistByOffset:(unsigned int)arg1 Length:(unsigned int)arg2;
- (_Bool)isVideoDownloading;
- (void)requestDataOnGetDuration:(double)arg1;
- (_Bool)requestNetVideoDataByOffset:(unsigned int)arg1 Length:(unsigned int)arg2 DurationSec:(unsigned int)arg3;
@property(retain, nonatomic) NSString *tempPath; // @synthesize tempPath=_tempPath;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
- (unsigned long long)startVideoStreamDownload;
- (void)stopVideoStreamDownload;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

