//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSMutableArray;

@interface IdKeyDataPkg : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int cliver; // @dynamic cliver;
@property(retain, nonatomic) NSMutableArray *dataitems; // @dynamic dataitems;
@property(nonatomic) unsigned int nettype; // @dynamic nettype;
@property(nonatomic) unsigned int uin; // @dynamic uin;

@end

