//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

@protocol IFTSIndexOperation <NSObject>
- (void)iFTSIndexingFireTask:(int)arg1;
- (void)iFTSIndexingInit;
- (void)iFTSIndexingPause;
- (void)iFTSIndexingReloadDB;
- (void)iFTSIndexingStop;
@property(nonatomic) int iFTSIndexingType;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *taskQueue;

@optional
- (void)iFTSIndexingMemoryWarning;
- (void)iFTSIndexingPrepareSearch;
@end

