//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol ISvrErrorExt <NSObject>
- (void)OnGetSvrError:(NSString *)arg1 Url:(NSString *)arg2 Tips:(NSString *)arg3 TimeOut:(unsigned int)arg4;
@end

