//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "KindaView.h"

#import "MMKSecureEditText.h"
#import "TenpaySecureCtrlDelegate.h"
#import "UITextFieldDelegate.h"

@class MMKSecureEditTextOnTextChangedCallback, NSString, TenpaySecureCtrl;

@interface KindaSecureEditText : KindaView <UITextFieldDelegate, MMKSecureEditText, TenpaySecureCtrlDelegate>
{
    long long m_tintColor;
    TenpaySecureCtrl *_m_textField;
    long long _m_textColor;
    NSString *_m_defaultValue;
    MMKSecureEditTextOnTextChangedCallback *_m_onTextChangedCallback;
}

- (void).cxx_destruct;
- (void)dealloc;
- (long long)getClearButtonMode;
- (id)getDefaultValue;
- (_Bool)getEnabled;
- (_Bool)getFocus;
- (long long)getTextColor;
- (long long)getTintColor;
- (id)getView;
- (id)gettext;
- (id)init;
- (_Bool)isCardFromatValid:(int)arg1;
@property(retain, nonatomic) NSString *m_defaultValue; // @synthesize m_defaultValue=_m_defaultValue;
@property(retain, nonatomic) MMKSecureEditTextOnTextChangedCallback *m_onTextChangedCallback; // @synthesize m_onTextChangedCallback=_m_onTextChangedCallback;
@property(nonatomic) long long m_textColor; // @synthesize m_textColor=_m_textColor;
@property(retain, nonatomic) TenpaySecureCtrl *m_textField; // @synthesize m_textField=_m_textField;
- (void)setClearButtonMode:(long long)arg1;
- (void)setDefaultValue:(id)arg1;
- (void)setEnabled:(_Bool)arg1;
- (void)setFocus:(_Bool)arg1;
- (void)setHint:(id)arg1;
- (void)setKeyboardType:(long long)arg1;
- (void)setOnTextChangedCallback:(id)arg1;
- (void)setTextColor:(long long)arg1;
- (void)setTintColor:(long long)arg1;
- (void)tenpayCtrlShouldChange:(id)arg1;
- (void)tenpayCtrlShouldReturn:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

