//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MMRsaCryptUtil.h"

@class NSString;

@interface KindaRsaCryptUtil : NSObject <MMRsaCryptUtil>
{
}

- (id)rsaPublicEncryptPemkey:(id)arg1 pemKey:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

