//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface LaunchAction : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int actionCode; // @dynamic actionCode;
@property(retain, nonatomic) NSString *alertMsg; // @dynamic alertMsg;
@property(retain, nonatomic) NSString *alertTitle; // @dynamic alertTitle;
@property(nonatomic) _Bool needHistoryList; // @dynamic needHistoryList;
@property(retain, nonatomic) NSString *openUrl; // @dynamic openUrl;

@end

