//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface LocalSearchConfig : NSObject
{
    NSMutableArray *_arrClassConfig;
}

+ (id)getSharedDefaultConfig;
+ (id)makeConfigFromClassArray:(id)arg1;
- (void).cxx_destruct;
- (void)addClassConfigFromArray:(id)arg1;
@property(retain, nonatomic) NSMutableArray *arrClassConfig; // @synthesize arrClassConfig=_arrClassConfig;
- (id)description;

@end

