//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@interface MailRTEPasteMgr : MMObject
{
}

+ (void)clearPasteData;
+ (void)copy:(id)arg1;
+ (id)copyAttachment:(id)arg1;
+ (id)copyAttachmentsInAttributedString:(id)arg1;
+ (id)getDescOfAttachment:(id)arg1;
+ (id)getPasteData;
+ (_Bool)hasPasteData;
+ (_Bool)needClear;

@end

