//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MCTriggerElement.h"

@class MCSequenceStickerProvider, NSArray, NSString;

@interface MCFaceOffElement : MCTriggerElement
{
    _Bool _couldPreloadResource;
    _Bool _enableLazyLoad;
    int _faceOffType;
    int _frameType;
    unsigned int _materialTexture;
    float _blendAlpha;
    int _grayScale;
    int _blendMode;
    int _materialAlphaType;
    int _featureType;
    unsigned int _eyeIrisTexture;
    NSString *_elementID;
    double _frameDuration;
    long long _frames;
    float *_materialTexVec;
    float *_materialLineTexVec;
    NSString *_folderPath;
    NSString *_textureImagePath;
    NSArray *_facePoints;
    NSString *_eyeIrisImage;
    MCSequenceStickerProvider *_materialProvider;
    long long _currentFrameNumber;
    struct CGSize _frameSize;
    struct CGSize _imageFaceOriginSize;
}

- (void).cxx_destruct;
- (void)activeEyeIrisTextureAtTextureIndex:(unsigned int)arg1 forUniform:(int)arg2;
- (void)advanceTime:(double)arg1;
@property(nonatomic) float blendAlpha; // @synthesize blendAlpha=_blendAlpha;
@property(nonatomic) int blendMode; // @synthesize blendMode=_blendMode;
- (void)clearResource;
@property _Bool couldPreloadResource; // @synthesize couldPreloadResource=_couldPreloadResource;
@property(nonatomic) long long currentFrameNumber; // @synthesize currentFrameNumber=_currentFrameNumber;
- (unsigned int)currentMaterialTexture;
- (unsigned int)currentMaterialTexture:(id)arg1;
- (void)dealloc;
@property(copy, nonatomic) NSString *elementID; // @synthesize elementID=_elementID;
@property(nonatomic) _Bool enableLazyLoad; // @synthesize enableLazyLoad=_enableLazyLoad;
@property(copy, nonatomic) NSString *eyeIrisImage; // @synthesize eyeIrisImage=_eyeIrisImage;
@property(nonatomic) unsigned int eyeIrisTexture; // @synthesize eyeIrisTexture=_eyeIrisTexture;
@property(nonatomic) int faceOffType; // @synthesize faceOffType=_faceOffType;
@property(retain, nonatomic) NSArray *facePoints; // @synthesize facePoints=_facePoints;
@property(nonatomic) int featureType; // @synthesize featureType=_featureType;
@property(copy, nonatomic) NSString *folderPath; // @synthesize folderPath=_folderPath;
@property(nonatomic) double frameDuration; // @synthesize frameDuration=_frameDuration;
@property(nonatomic) struct CGSize frameSize; // @synthesize frameSize=_frameSize;
@property(nonatomic) int frameType; // @synthesize frameType=_frameType;
@property(nonatomic) long long frames; // @synthesize frames=_frames;
@property(nonatomic) int grayScale; // @synthesize grayScale=_grayScale;
- (_Bool)hasValidEyeIrisResource;
@property(nonatomic) struct CGSize imageFaceOriginSize; // @synthesize imageFaceOriginSize=_imageFaceOriginSize;
- (id)initWithDictionary:(id)arg1 withItem:(id)arg2;
- (_Bool)isMaterialValid;
@property(nonatomic) int materialAlphaType; // @synthesize materialAlphaType=_materialAlphaType;
@property float *materialLineTexVec; // @synthesize materialLineTexVec=_materialLineTexVec;
@property(retain, nonatomic) MCSequenceStickerProvider *materialProvider; // @synthesize materialProvider=_materialProvider;
@property float *materialTexVec; // @synthesize materialTexVec=_materialTexVec;
@property(nonatomic) unsigned int materialTexture; // @synthesize materialTexture=_materialTexture;
- (void)preloadResource;
- (void)preloadResourceWithImage:(id)arg1 facePoints:(id)arg2;
- (void)preloadResourceWithImageSize:(struct CGSize)arg1 facePoints:(id)arg2;
- (void)resetTime;
@property(copy, nonatomic) NSString *textureImagePath; // @synthesize textureImagePath=_textureImagePath;

@end

