//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MetalImageTexture : NSObject
{
    struct {
        unsigned long long count;
        _Bool enabled;
    } _reference;
    unsigned long long _readLockCount;
    struct __CVBuffer *_textureRef;
    struct __CVBuffer *_renderTarget;
    struct MTLUInt2 _size;
    id <MTLTexture> _texture;
}

+ (struct CGSize)sizeThatFitsWithinATextureForSize:(struct CGSize)arg1;
+ (_Bool)supportsFastTextureUpload;
+ (_Bool)supportsFastTextureUpload1;
- (void).cxx_destruct;
- (void)buildupTexture;
- (char *)byteBuffer;
- (unsigned long long)bytesPerRow;
- (void)clearAllLocks;
- (void)dealloc;
- (id)description;
- (void)disableReferenceCounting;
- (void)enableReferenceCounting;
- (id)imageFromTextureWithOrientation:(long long)arg1;
- (id)init;
- (id)initWithSampleBuffer:(struct opaqueCMSampleBuffer *)arg1 type:(long long)arg2;
- (id)initWithTextureSize:(struct MTLUInt2)arg1;
- (_Bool)isReferenceCountingEnable;
- (id)lock;
- (void)lockForReading;
- (unsigned long long)referenceCounting;
@property(readonly, nonatomic) struct MTLUInt2 size; // @synthesize size=_size;
- (void)teardownTexture;
@property(readonly, nonatomic) id <MTLTexture> texture; // @synthesize texture=_texture;
- (void)unlock;
- (void)unlockAfterReading;

@end

