//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MidasIAPLogger : NSObject
{
    _Bool enable;
}

+ (id)instance;
@property(nonatomic) _Bool enable; // @synthesize enable;
- (void)log:(id)arg1;
- (void)logD:(id)arg1;
- (id)logHead;

@end

