//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MidasIAPBaseReq, MidasIAPUserInfo, MidasIapOrderInfo, NSArray, NSError, SKPaymentQueue;

@protocol MidasIAPOperationProtocol <NSObject>
@property(nonatomic) __weak id delegate;
- (_Bool)midas_paymentQueue:(SKPaymentQueue *)arg1 midas_updatedTransactions:(NSArray *)arg2;
- (void)onDestroy;
@property(retain, nonatomic) MidasIapOrderInfo *orderInfo;
@property(nonatomic) __weak id <MidasIAPPayDelegate> outerDelegate;
@property(retain, nonatomic) MidasIAPBaseReq *req;
@property(retain, nonatomic) MidasIAPUserInfo *userInfo;
- (void)start;

@optional
- (void)midas_paymentQueue:(SKPaymentQueue *)arg1 midas_restoreCompletedTransactionsFailedWithError:(NSError *)arg2;
- (void)midas_paymentQueueRestoreCompletedTransactionsFinished:(SKPaymentQueue *)arg1;
@end

