//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSData, NSString;

@interface MMAuthInfo : NSObject <NSCopying>
{
    int _encryptAlgo;
    NSString *_identify;
    NSData *_clientSessionKey;
    NSData *_serverSessionKey;
    NSData *_serverId;
}

- (void).cxx_destruct;
@property(retain) NSData *clientSessionKey; // @synthesize clientSessionKey=_clientSessionKey;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(nonatomic) int encryptAlgo; // @synthesize encryptAlgo=_encryptAlgo;
- (_Bool)hasSessionKey;
@property(retain, nonatomic) NSString *identify; // @synthesize identify=_identify;
- (_Bool)isValid;
@property(retain) NSData *serverId; // @synthesize serverId=_serverId;
@property(retain) NSData *serverSessionKey; // @synthesize serverSessionKey=_serverSessionKey;

@end

