//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBCoding.h"

@class MMFolderWrapCacheData, NSMutableArray, NSMutableDictionary, NSString;

@interface MMDiskUsageScanStat : NSObject <PBCoding>
{
    unsigned int m_totalStartTime;
    unsigned int m_totalEndTime;
    unsigned int m_totalUsedTime;
    unsigned int m_totalScanCount;
    unsigned int m_totalFolderNum;
    unsigned int m_totalFileNum;
    unsigned int m_totalDelFolderNum;
    unsigned int m_totalDelFileNum;
    unsigned int m_curStartTime;
    unsigned int m_curEndTime;
    unsigned int m_curUsedTime;
    unsigned int m_curScannedFolderNum;
    unsigned int m_curAddFolderNum;
    unsigned int m_curScannedFileNum;
    unsigned int m_curDelFolderNum;
    unsigned int m_curDelFileNum;
    unsigned int m_hitCacheCount;
    unsigned int m_setCacheCount;
    unsigned int m_timeOutCacheCount;
    unsigned int m_fileModifyCacheCount;
    unsigned int m_refreshCacheTimeCount;
    unsigned int m_deleteCacheCount;
    unsigned long long m_totalFileSize;
    NSMutableDictionary *m_dicTotalBizStat;
    unsigned long long m_totalDelFileSize;
    NSMutableDictionary *m_dicTotalFileTypeInUseStat;
    NSMutableDictionary *m_dicTotalSpecialFileStat;
    NSMutableDictionary *m_dicTotalWechatFileClassStat;
    NSMutableDictionary *m_hardlinkInodeDict;
    NSMutableDictionary *m_beScannedDeleteFilesDict;
    unsigned long long m_curDelFileSize;
    NSMutableArray *_filesScanResult;
    NSMutableArray *_folderScanResult;
    NSMutableArray *_filesDeleteInfo;
    NSMutableArray *_foldersDeleteInfo;
    NSMutableArray *_fileClassScanDetailInfo;
    MMFolderWrapCacheData *_wrapCacheData;
}

+ (void)initialize;
- (void).cxx_destruct;
- (id)currentScanSummary;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) NSMutableArray *fileClassScanDetailInfo; // @synthesize fileClassScanDetailInfo=_fileClassScanDetailInfo;
@property(retain, nonatomic) NSMutableArray *filesDeleteInfo; // @synthesize filesDeleteInfo=_filesDeleteInfo;
@property(retain, nonatomic) NSMutableArray *filesScanResult; // @synthesize filesScanResult=_filesScanResult;
@property(retain, nonatomic) NSMutableArray *folderScanResult; // @synthesize folderScanResult=_folderScanResult;
@property(retain, nonatomic) NSMutableArray *foldersDeleteInfo; // @synthesize foldersDeleteInfo=_foldersDeleteInfo;
- (id)getFileClassDetailInfo;
- (const map_f8690629 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (id)init;
@property(retain, nonatomic) NSMutableDictionary *m_beScannedDeleteFilesDict; // @synthesize m_beScannedDeleteFilesDict;
@property(nonatomic) unsigned int m_curAddFolderNum; // @synthesize m_curAddFolderNum;
@property(nonatomic) unsigned int m_curDelFileNum; // @synthesize m_curDelFileNum;
@property(nonatomic) unsigned long long m_curDelFileSize; // @synthesize m_curDelFileSize;
@property(nonatomic) unsigned int m_curDelFolderNum; // @synthesize m_curDelFolderNum;
@property(nonatomic) unsigned int m_curEndTime; // @synthesize m_curEndTime;
@property(nonatomic) unsigned int m_curScannedFileNum; // @synthesize m_curScannedFileNum;
@property(nonatomic) unsigned int m_curScannedFolderNum; // @synthesize m_curScannedFolderNum;
@property(nonatomic) unsigned int m_curStartTime; // @synthesize m_curStartTime;
@property(nonatomic) unsigned int m_curUsedTime; // @synthesize m_curUsedTime;
@property(nonatomic) unsigned int m_deleteCacheCount; // @synthesize m_deleteCacheCount;
@property(retain, nonatomic) NSMutableDictionary *m_dicTotalBizStat; // @synthesize m_dicTotalBizStat;
@property(retain, nonatomic) NSMutableDictionary *m_dicTotalFileTypeInUseStat; // @synthesize m_dicTotalFileTypeInUseStat;
@property(retain, nonatomic) NSMutableDictionary *m_dicTotalSpecialFileStat; // @synthesize m_dicTotalSpecialFileStat;
@property(retain, nonatomic) NSMutableDictionary *m_dicTotalWechatFileClassStat; // @synthesize m_dicTotalWechatFileClassStat;
@property(nonatomic) unsigned int m_fileModifyCacheCount; // @synthesize m_fileModifyCacheCount;
@property(retain, nonatomic) NSMutableDictionary *m_hardlinkInodeDict; // @synthesize m_hardlinkInodeDict;
@property(nonatomic) unsigned int m_hitCacheCount; // @synthesize m_hitCacheCount;
@property(nonatomic) unsigned int m_refreshCacheTimeCount; // @synthesize m_refreshCacheTimeCount;
@property(nonatomic) unsigned int m_setCacheCount; // @synthesize m_setCacheCount;
@property(nonatomic) unsigned int m_timeOutCacheCount; // @synthesize m_timeOutCacheCount;
@property(nonatomic) unsigned int m_totalDelFileNum; // @synthesize m_totalDelFileNum;
@property(nonatomic) unsigned long long m_totalDelFileSize; // @synthesize m_totalDelFileSize;
@property(nonatomic) unsigned int m_totalDelFolderNum; // @synthesize m_totalDelFolderNum;
@property(nonatomic) unsigned int m_totalEndTime; // @synthesize m_totalEndTime;
@property(nonatomic) unsigned int m_totalFileNum; // @synthesize m_totalFileNum;
@property(nonatomic) unsigned long long m_totalFileSize; // @synthesize m_totalFileSize;
@property(nonatomic) unsigned int m_totalFolderNum; // @synthesize m_totalFolderNum;
@property(nonatomic) unsigned int m_totalScanCount; // @synthesize m_totalScanCount;
@property(nonatomic) unsigned int m_totalStartTime; // @synthesize m_totalStartTime;
@property(nonatomic) unsigned int m_totalUsedTime; // @synthesize m_totalUsedTime;
- (void)markStartTime;
- (void)markStopTime:(_Bool)arg1;
@property(retain, nonatomic) MMFolderWrapCacheData *wrapCacheData; // @synthesize wrapCacheData=_wrapCacheData;
- (id)totalScanSummy;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

