//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "MMDiskUsageRepoterDelegate.h"
#import "MMDiskUsageScannerDelegate.h"

@class MMDiskUsageReporter, MMDiskUsageScaner, NSString, UIButton, UITextView;

@interface MMDiskUsageScanResultViewController : MMUIViewController <MMDiskUsageScannerDelegate, MMDiskUsageRepoterDelegate>
{
    UIButton *_scanStartButton;
    UIButton *_scanStopButton;
    MMDiskUsageScaner *_usageScanner;
    MMDiskUsageReporter *_usageReporter;
    UITextView *_resultTextView;
    NSString *_infoString;
}

- (void).cxx_destruct;
- (id)getDeleteTextOfScanStat:(id)arg1;
- (id)getFileClassDetailInfoOfScanStat:(id)arg1;
- (id)getFileInfoWithStoreTimeType:(int)arg1 withAll:(id)arg2;
- (id)getFolderInfoWithFileTyeInUse:(int)arg1 withAll:(id)arg2;
- (id)getFolderInfoWithStoreTimeType:(int)arg1 withAll:(id)arg2;
- (id)getSlimPath:(id)arg1;
- (id)getStringForFileDeleteInfo:(id)arg1;
- (id)getStringForFileInfo:(id)arg1;
- (id)getStringForFolderInfo:(id)arg1;
- (id)getStringWithFileTypeInUse:(int)arg1;
- (id)getStringWithStoreTimeType:(int)arg1;
- (id)getTextOfScanStat:(id)arg1;
@property(copy, nonatomic) NSString *infoString; // @synthesize infoString=_infoString;
- (void)onDiskUsageScanCancel;
- (void)onDiskUsageScanFinishedWithScanStat:(id)arg1;
- (void)onDiskUsageScanStart;
- (void)onReportFinished;
@property(retain, nonatomic) UITextView *resultTextView; // @synthesize resultTextView=_resultTextView;
- (void)scanDiskBegin;
- (void)scanDiskStop;
@property(retain, nonatomic) UIButton *scanStartButton; // @synthesize scanStartButton=_scanStartButton;
@property(retain, nonatomic) UIButton *scanStopButton; // @synthesize scanStopButton=_scanStopButton;
- (void)sendDataToFileHelper;
@property(retain, nonatomic) MMDiskUsageReporter *usageReporter; // @synthesize usageReporter=_usageReporter;
@property(retain, nonatomic) MMDiskUsageScaner *usageScanner; // @synthesize usageScanner=_usageScanner;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

