//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMKView.h"

@class MMKCountryCallingCodeViewOnSelectCallback, NSArray, NSString;

@protocol MMKCountryCallingCodeView <MMKView>
- (NSString *)getCountryCode;
- (_Bool)getFocus;
- (_Bool)getHideCode;
- (NSString *)getNationality;
- (NSString *)getPlaceHolder;
- (void)setCountryCode:(NSString *)arg1;
- (void)setFocus:(_Bool)arg1;
- (void)setHideCode:(_Bool)arg1;
- (void)setNationality:(NSString *)arg1;
- (void)setNationalityExcludeArray:(NSArray *)arg1;
- (void)setOnSelectCallback:(MMKCountryCallingCodeViewOnSelectCallback *)arg1;
- (void)setPlaceHolder:(NSString *)arg1;
@end

