//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMKView.h"

@class MMKPwdInputViewOnEndEnterPasswordCallback, MMKPwdInputViewOnPasswordChangeCallback, NSString;

@protocol MMKPwdInputView <MMKView>
- (_Bool)getAutoRemarkKeyBoradType;
- (_Bool)getChearInput;
- (_Bool)getFocus;
- (NSString *)getHashData;
- (long long)getTextLength;
- (void)setAutoRemarkKeyBoradType:(_Bool)arg1;
- (void)setChearInput:(_Bool)arg1;
- (void)setFocus:(_Bool)arg1;
- (void)setHashData:(NSString *)arg1;
- (void)setOnEndEnterPasswordCallback:(MMKPwdInputViewOnEndEnterPasswordCallback *)arg1;
- (void)setOnPasswordChangeCallback:(MMKPwdInputViewOnPasswordChangeCallback *)arg1;
- (void)setTextLength:(long long)arg1;
@end

