//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMKScrollViewOnScrollCallback : NSObject
{
    struct Handle<std::__1::shared_ptr<kinda::KScrollViewOnScrollCallback>> _cppRefHandle;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithCpp:(const shared_ptr_1731e3e1 *)arg1;
- (void)onScroll:(float)arg1 y:(float)arg2;

@end

