//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMResourceMgrExt.h"
#import "MMService.h"

@class NSString;

@interface MMLanguagePackageDownloadMgr : MMService <MMService, MMResourceMgrExt>
{
    NSString *m_sLangRootPath;
    _Bool m_hasUpdate;
    _Bool isCheckingPackageList;
    unsigned int uiInterval;
}

- (void).cxx_destruct;
- (void)checkIfUpdatedForLang:(id)arg1 andRefreshOn:(unsigned int)arg2;
- (_Bool)checkInterval:(_Bool)arg1;
- (void)checkResouce;
- (void)dealloc;
- (void)doCheckUpdate;
- (void)doCheckUpdateDelay;
- (void)doCheckUpdateOnMainThread:(_Bool)arg1;
- (unsigned int)getLangVersion;
- (id)getLangVersionFile;
- (id)init;
- (void)onResDeleteFinishWithResType:(unsigned int)arg1 subResType:(unsigned int)arg2;
- (void)onResUpdateFinish:(long long)arg1 resType:(unsigned int)arg2 subResType:(unsigned int)arg3;
- (void)updateVersion:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

