//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "MMWebImageViewDelegate.h"

@class MMWebImageView, NSString, UILabel;

@interface MMLocationAttributeBanner : MMUIView <MMWebImageViewDelegate>
{
    NSString *_title;
    NSString *_logoUrl;
    NSString *_link;
    id <MMLocationAttributeBannerDelegate> _delegate;
    UILabel *_titleLable;
    MMWebImageView *_logoImgView;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) __weak id <MMLocationAttributeBannerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithFrame:(struct CGRect)arg1;
@property(readonly, nonatomic) NSString *logoUrl; // @synthesize logoUrl=_logoUrl;
- (void)onLoadImageOK:(id)arg1;
- (void)onTapBanner:(id)arg1;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
- (void)updateBanner:(id)arg1 LogoUrl:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

