//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMNotificationSetting : NSObject
{
    _Bool _isAlertSettingOn;
    _Bool _isNotificationCenterSettingOn;
    _Bool _isLockScreenSettingOn;
    _Bool _isSoundSettingOn;
    _Bool _isBadgeSettingOn;
}

@property(readonly, nonatomic) _Bool canShowAlert;
- (id)description;
@property(nonatomic) _Bool isAlertSettingOn; // @synthesize isAlertSettingOn=_isAlertSettingOn;
@property(readonly, nonatomic) _Bool isAllSettingOff;
@property(nonatomic) _Bool isBadgeSettingOn; // @synthesize isBadgeSettingOn=_isBadgeSettingOn;
- (_Bool)isEqual:(id)arg1;
@property(nonatomic) _Bool isLockScreenSettingOn; // @synthesize isLockScreenSettingOn=_isLockScreenSettingOn;
@property(nonatomic) _Bool isNotificationCenterSettingOn; // @synthesize isNotificationCenterSettingOn=_isNotificationCenterSettingOn;
@property(nonatomic) _Bool isSoundSettingOn; // @synthesize isSoundSettingOn=_isSoundSettingOn;

@end

