//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MMOpenVoiceMember : NSObject
{
    int memberId;
    NSString *openId;
}

- (void).cxx_destruct;
@property(nonatomic) int memberId; // @synthesize memberId;
@property(retain, nonatomic) NSString *openId; // @synthesize openId;

@end

