//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "CNContactPickerDelegate.h"
#import "CNContactViewControllerDelegate.h"
#import "WCActionSheetDelegate.h"

@class CBaseContact, NSString, UIViewController;

@interface MMPhoneNumberHandler : MMObject <WCActionSheetDelegate, CNContactViewControllerDelegate, CNContactPickerDelegate>
{
    NSString *_phoneNumber;
    UIViewController *_viewController;
    CBaseContact *m_oContact;
}

+ (_Bool)canMakePhoneCall;
+ (void)handlePhoneNumber:(id)arg1;
+ (void)handlePhoneNumber:(id)arg1 contact:(id)arg2;
+ (void)handleWechatOutPhoneNumber:(id)arg1;
+ (void)makePhoneCall:(id)arg1;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)AddPhoneNumberToExistContact:(id)arg1 viewController:(id)arg2;
- (void)CreateNewContact:(id)arg1 viewController:(id)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)contactPicker:(id)arg1 didSelectContact:(id)arg2;
- (void)contactPickerDidCancel:(id)arg1;
- (void)contactViewController:(id)arg1 didCompleteWithContact:(id)arg2;
- (id)getViewController;
- (void)handleContactActionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)handlePhoneNumber:(id)arg1;
- (void)handlePhoneNumber:(id)arg1 contact:(id)arg2;
- (void)handleTotalActionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)handleWechatOutActionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)handleWechatOutPhone:(id)arg1;
@property(retain, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
- (void)requestAccessForContactsDone:(_Bool)arg1 withAlertTitle:(id)arg2;
@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
- (void)showContactActionSheet:(id)arg1;
- (void)showNewPersonViewController;
- (void)showPeoplePickerController;
- (void)showTotalActionSheet:(id)arg1;
- (void)showWechatOutActionSheet;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

