//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MMSafeModeInfo : NSObject
{
    int m_version;
    NSString *m_path;
    _Bool _shouldNotUpdateConfig;
    _Bool _isCrashBySpecialCharacter;
    _Bool _isBootTimeNotEnough;
    _Bool _isSheildFOOMEnterSafeMode;
    int _appContinuousCrashCount;
    int _appLastCrashSignalNumber;
    int _appLastCrashSignalCode;
    int _appTimeoutCount;
    int _appTimeoutSceneCount;
    int _appContinuousFOOMCount;
    long long _appLastBootTime;
}

+ (id)shareInstance;
- (void).cxx_destruct;
@property(nonatomic) int appContinuousCrashCount; // @synthesize appContinuousCrashCount=_appContinuousCrashCount;
@property(nonatomic) int appContinuousFOOMCount; // @synthesize appContinuousFOOMCount=_appContinuousFOOMCount;
@property(nonatomic) long long appLastBootTime; // @synthesize appLastBootTime=_appLastBootTime;
@property(nonatomic) int appLastCrashSignalCode; // @synthesize appLastCrashSignalCode=_appLastCrashSignalCode;
@property(nonatomic) int appLastCrashSignalNumber; // @synthesize appLastCrashSignalNumber=_appLastCrashSignalNumber;
@property(nonatomic) int appTimeoutCount; // @synthesize appTimeoutCount=_appTimeoutCount;
@property(nonatomic) int appTimeoutSceneCount; // @synthesize appTimeoutSceneCount=_appTimeoutSceneCount;
- (void)clearAll;
- (id)infoPath;
- (id)init;
@property(nonatomic) _Bool isBootTimeNotEnough; // @synthesize isBootTimeNotEnough=_isBootTimeNotEnough;
@property(nonatomic) _Bool isCrashBySpecialCharacter; // @synthesize isCrashBySpecialCharacter=_isCrashBySpecialCharacter;
@property(nonatomic) _Bool isSheildFOOMEnterSafeMode; // @synthesize isSheildFOOMEnterSafeMode=_isSheildFOOMEnterSafeMode;
- (_Bool)loadInfo;
- (void)saveInfo;
@property(nonatomic) _Bool shouldNotUpdateConfig; // @synthesize shouldNotUpdateConfig=_shouldNotUpdateConfig;

@end

