//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface MMSelectCoverView : UIView
{
    UIColor *_selectedColor;
    UIColor *_cursorColor;
    double _leftLineLength;
    double _topLineLength;
    double _rightLineLength;
    double _bottomLineLength;
    double _dotRadius;
    struct CGRect _leftCursorRect;
    struct CGRect _rightCursorRect;
}

- (void).cxx_destruct;
@property(nonatomic) double bottomLineLength; // @synthesize bottomLineLength=_bottomLineLength;
@property(retain, nonatomic) UIColor *cursorColor; // @synthesize cursorColor=_cursorColor;
@property(nonatomic) double dotRadius; // @synthesize dotRadius=_dotRadius;
- (void)drawRect:(struct CGRect)arg1;
- (double)farBottom;
- (double)farLeft;
- (double)farRight;
- (double)farTop;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)isTouchInLeftCursor:(struct CGPoint)arg1;
- (_Bool)isTouchInRightCursor:(struct CGPoint)arg1;
@property(nonatomic) struct CGRect leftCursorRect; // @synthesize leftCursorRect=_leftCursorRect;
@property(nonatomic) double leftLineLength; // @synthesize leftLineLength=_leftLineLength;
@property(nonatomic) struct CGRect rightCursorRect; // @synthesize rightCursorRect=_rightCursorRect;
@property(nonatomic) double rightLineLength; // @synthesize rightLineLength=_rightLineLength;
@property(retain, nonatomic) UIColor *selectedColor; // @synthesize selectedColor=_selectedColor;
@property(nonatomic) double topLineLength; // @synthesize topLineLength=_topLineLength;

@end

