//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface MMTemplateMsg3rdAppShowItem : MMObject
{
    NSString *_avatarUrl;
    NSString *_displayName;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *avatarUrl; // @synthesize avatarUrl=_avatarUrl;
@property(copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;

@end

