//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface MMTitleView : UIView
{
}

- (id)accessibilityLabel;
- (id)getSubTitle;
- (id)getSubViewAccessibilityStr:(id)arg1;
- (id)getTitle;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)isAccessibilityElement;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)setSubTitle:(id)arg1;
- (void)setTitle:(id)arg1;

@end

