//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMWebViewPluginBase.h"

@class NSMutableDictionary;

@interface MMWebViewPlugin_Share : MMWebViewPluginBase
{
    NSMutableDictionary *_dictShareDataForSendAppMessage;
    NSMutableDictionary *_dictShareDataForShareTimeline;
}

+ (_Bool)canShareAppMessageWithUpdateShareData:(id)arg1;
- (void).cxx_destruct;
- (id)appMessageShareDataParamsFromCurrentUrl:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *dictShareDataForSendAppMessage; // @synthesize dictShareDataForSendAppMessage=_dictShareDataForSendAppMessage;
@property(retain, nonatomic) NSMutableDictionary *dictShareDataForShareTimeline; // @synthesize dictShareDataForShareTimeline=_dictShareDataForShareTimeline;
- (void)doUpdateShareData:(id)arg1 forCurrentUrl:(id)arg2 inDictionary:(id)arg3;
- (id)init;
- (id)timelineShareDataParamsFromCurrentUrl:(id)arg1;
- (void)updateSendAppMessageShareData:(id)arg1 forCurrentUrl:(id)arg2;
- (void)updateTimelineShareData:(id)arg1 forCurrentUrl:(id)arg2;

@end

