//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@protocol MMWebViewPreloadContentHandler <NSObject>
- (NSString *)addSessoinQueryForRequestUrl:(NSString *)arg1;
- (NSString *)addTemplateQueryForUrl:(NSString *)arg1 useFlag:(unsigned long long)arg2;
- (NSString *)getLatestPageTemplateFullVersion;
- (unsigned int)getPageCheckInterval;
- (unsigned int)getPageDataRequiredTemplateVersion;
- (NSString *)getPageForceUrl;
- (_Bool)getPageForceUrlFullScreenValidState;
- (NSString *)getPageTemplateFullVersion;
- (NSString *)getPageTemplateHttpHeader;
- (unsigned int)getPageTemplateReportId;
- (unsigned int)getPageTemplateType;
- (unsigned int)getPageTemplateVersion;
- (id)initWithParameter:(id)arg1;
- (void)onInjectPageDataNotifySuccessWithA8keyScene:(unsigned int)arg1 useFlag:(unsigned long long)arg2;
- (NSString *)pageDataString;
- (NSString *)pageFrameHtmlString;
- (NSString *)pageFrameUrlString;
- (NSDictionary *)requestSessionHeader;
- (void)saveA8KeyInfoWithUrl:(NSString *)arg1 header:(NSDictionary *)arg2;
- (void)setupPageUrl:(NSString *)arg1 pageDataKeyUrl:(NSString *)arg2 scene:(unsigned int)arg3 enterType:(unsigned int)arg4;
- (void)updatePageDataWithCompletion:(void (^)(NSString *, NSString *))arg1;
- (unsigned long long)useFlagForIsUsePreCreateWebView:(_Bool)arg1 isSyncGetPageData:(_Bool)arg2;
@end

