//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface MPLandingVideoInfo : MMObject
{
    _Bool _isOverSize;
    unsigned int _formatId;
    unsigned int _durationMs;
    unsigned int _width;
    unsigned int _height;
    NSString *_url;
    unsigned long long _fileSize;
}

- (void).cxx_destruct;
- (id)description;
@property(nonatomic) unsigned int durationMs; // @synthesize durationMs=_durationMs;
@property(nonatomic) unsigned long long fileSize; // @synthesize fileSize=_fileSize;
@property(nonatomic) unsigned int formatId; // @synthesize formatId=_formatId;
@property(nonatomic) unsigned int height; // @synthesize height=_height;
@property(nonatomic) _Bool isOverSize; // @synthesize isOverSize=_isOverSize;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) unsigned int width; // @synthesize width=_width;

@end

