//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UILabel;

@interface MPLandingVideoOversizeTipsView : UIView
{
    UIView *_containerView;
    UILabel *_tipsLabel;
    UIButton *_playBtn;
    CDUnknownBlockType _comfirmHanlder;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType comfirmHanlder; // @synthesize comfirmHanlder=_comfirmHanlder;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
- (void)initSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)onClickPlayBtn;
@property(retain, nonatomic) UIButton *playBtn; // @synthesize playBtn=_playBtn;
- (void)setTips:(id)arg1 confirmTips:(id)arg2 comfirmHandler:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;

@end

