//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface MPPageFastLoadPageDataCgiContext : NSObject
{
    _Bool _isResponseSuccess;
    unsigned int _responseContentUpdateCount;
    unsigned int _responseContentNoUpdateCount;
    unsigned int _responseContentSize;
    long long _enterType;
    unsigned long long _sceneForFetch;
    NSArray *_urlInfoList;
    unsigned long long _startTime;
    unsigned long long _endTime;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long endTime; // @synthesize endTime=_endTime;
@property(nonatomic) long long enterType; // @synthesize enterType=_enterType;
@property(nonatomic) _Bool isResponseSuccess; // @synthesize isResponseSuccess=_isResponseSuccess;
@property(nonatomic) unsigned int responseContentNoUpdateCount; // @synthesize responseContentNoUpdateCount=_responseContentNoUpdateCount;
@property(nonatomic) unsigned int responseContentSize; // @synthesize responseContentSize=_responseContentSize;
@property(nonatomic) unsigned int responseContentUpdateCount; // @synthesize responseContentUpdateCount=_responseContentUpdateCount;
@property(nonatomic) unsigned long long sceneForFetch; // @synthesize sceneForFetch=_sceneForFetch;
@property(nonatomic) unsigned long long startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) NSArray *urlInfoList; // @synthesize urlInfoList=_urlInfoList;

@end

