//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MPPageDownloadedTemplateRecord, MPPageTemplateInfo;

@interface MPPageDownloadingTemplateInfo : NSObject
{
    _Bool _isInvalid;
    unsigned int _scene;
    MPPageTemplateInfo *_templateInfo;
    MPPageDownloadedTemplateRecord *_record;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isInvalid; // @synthesize isInvalid=_isInvalid;
@property(retain, nonatomic) MPPageDownloadedTemplateRecord *record; // @synthesize record=_record;
@property(nonatomic) unsigned int scene; // @synthesize scene=_scene;
@property(retain, nonatomic) MPPageTemplateInfo *templateInfo; // @synthesize templateInfo=_templateInfo;

@end

