//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface MPPageFastLoadReportContext : NSObject
{
    unsigned int _requestTimes;
    unsigned long long _scene;
    NSArray *_itemList;
}

- (void).cxx_destruct;
- (id)description;
@property(retain, nonatomic) NSArray *itemList; // @synthesize itemList=_itemList;
@property(nonatomic) unsigned int requestTimes; // @synthesize requestTimes=_requestTimes;
@property(nonatomic) unsigned long long scene; // @synthesize scene=_scene;

@end

