//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QBWupService.h"

@interface MttWKStatService : QBWupService
{
}

+ (id)service;
- (void)getMemoryInfoWithPhoneID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getWKMachineInfoWithReq:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)preloadMachineListWithWithReq:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)preloadWKMachineInfoWithCompletion:(CDUnknownBlockType)arg1;

@end

