//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MMTimerLabel, UIButton, UILabel, VoipDescriptionButton;

@interface MultiTalkTalkingOperateView : UIView
{
    _Bool _m_videoOn;
    _Bool _m_muteOn;
    _Bool _m_speakerOn;
    MMTimerLabel *_m_timerView;
    UILabel *_m_statusLabel;
    VoipDescriptionButton *_m_videoButton;
    VoipDescriptionButton *_m_muteButton;
    VoipDescriptionButton *_m_speakerButton;
    UIButton *_m_addMemberButton;
    UIButton *_m_minimizeButton;
    UIButton *_m_hangupButton;
    UIButton *_m_flipCameraButton;
    id <MultiTalkTalkingOperateViewDelegate> _m_delegate;
    id <MultiTalkTalkingOperateViewLayoutDelegate> _m_layoutDelegate;
}

- (void).cxx_destruct;
- (_Bool)MuteSelected;
- (_Bool)SpeakerSelected;
- (long long)currentDuration;
- (void)hideOperateView;
- (void)initFlipCameraButton;
- (void)initHangupButton;
- (void)initMuteButton;
- (void)initSpeakerButton;
- (void)initStatusLabel;
- (void)initTimerView;
- (void)initVideoButton;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(retain, nonatomic) UIButton *m_addMemberButton; // @synthesize m_addMemberButton=_m_addMemberButton;
@property(nonatomic) __weak id <MultiTalkTalkingOperateViewDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
@property(retain, nonatomic) UIButton *m_flipCameraButton; // @synthesize m_flipCameraButton=_m_flipCameraButton;
@property(retain, nonatomic) UIButton *m_hangupButton; // @synthesize m_hangupButton=_m_hangupButton;
@property(nonatomic) __weak id <MultiTalkTalkingOperateViewLayoutDelegate> m_layoutDelegate; // @synthesize m_layoutDelegate=_m_layoutDelegate;
@property(retain, nonatomic) UIButton *m_minimizeButton; // @synthesize m_minimizeButton=_m_minimizeButton;
@property(retain, nonatomic) VoipDescriptionButton *m_muteButton; // @synthesize m_muteButton=_m_muteButton;
@property(nonatomic) _Bool m_muteOn; // @synthesize m_muteOn=_m_muteOn;
@property(retain, nonatomic) VoipDescriptionButton *m_speakerButton; // @synthesize m_speakerButton=_m_speakerButton;
@property(nonatomic) _Bool m_speakerOn; // @synthesize m_speakerOn=_m_speakerOn;
@property(retain, nonatomic) UILabel *m_statusLabel; // @synthesize m_statusLabel=_m_statusLabel;
@property(retain, nonatomic) MMTimerLabel *m_timerView; // @synthesize m_timerView=_m_timerView;
@property(retain, nonatomic) VoipDescriptionButton *m_videoButton; // @synthesize m_videoButton=_m_videoButton;
@property(nonatomic) _Bool m_videoOn; // @synthesize m_videoOn=_m_videoOn;
- (void)onFlipCameraButtonClick;
- (void)onHangupButtonClick;
- (void)onMuteButtonClick;
- (void)onSpeakerButtonClick;
- (void)onVideoButtonClick;
- (void)relayoutPanelButton;
- (void)reloadHeadView;
- (void)restartTimer;
- (void)showOperateView;
- (void)updateAddMemberEnabled:(_Bool)arg1;
- (void)updateDelegate:(id)arg1;
- (void)updateFlipCameraButtonHidden:(_Bool)arg1;
- (void)updateLayoutDelegate:(id)arg1;
- (void)updateMuteButtonEnabled:(_Bool)arg1;
- (void)updateMuteButtonSelected:(_Bool)arg1;
- (void)updateSpeakerButtonEnabled:(_Bool)arg1;
- (void)updateSpeakerButtonSelected:(_Bool)arg1;
- (void)updateStatusWording:(id)arg1;
- (void)updateVideoButtonEnabled:(_Bool)arg1;
- (void)updateVideoButtonSelected:(_Bool)arg1;
- (_Bool)videoSelected;
- (struct CGSize)viewSize;

@end

