//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CContact, WCVideoRender;

@protocol MultiTalkContactCellDelegate <NSObject>
- (_Bool)getMultitalkCollectionViewDoingAnimatioin;
- (void)onClickMultiTalkContactCellBigview;
- (void)onClickMultiTalkContactCellWithContact:(CContact *)arg1 render:(WCVideoRender *)arg2;
- (void)setMultitalkCollectionViewDoingAnimatioin:(_Bool)arg1;
@end

