//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "WCTTableCoding.h"

@class NSString;

@interface MultiTalkSessionItem : MMObject <WCTTableCoding>
{
    _Bool isAutoIncrement;
    unsigned int localID;
    unsigned int lastMessageID;
    NSString *groupID;
    NSString *clientGroupID;
    NSString *createUserName;
    long long lastInsertedRowID;
}

+ (void)__wcdb_column_constraint_34:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)__wcdb_synthesize_29:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)__wcdb_synthesize_30:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)__wcdb_synthesize_31:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)__wcdb_synthesize_32:(struct WCTBinding *)arg1;
+ (const struct WCTProperty *)__wcdb_synthesize_33:(struct WCTBinding *)arg1;
+ (id)__wcdbtyper;
+ (const SyntaxList_7f15fe8c *)allProperties;
+ (const struct WCTProperty *)clientGroupID;
+ (const struct WCTProperty *)createUserName;
+ (const struct WCTProperty *)groupID;
+ (const struct WCTProperty *)lastMessageID;
+ (const struct WCTProperty *)localID;
+ (const struct WCTBinding *)objectRelationalMapping;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *clientGroupID; // @synthesize clientGroupID;
@property(retain, nonatomic) NSString *createUserName; // @synthesize createUserName;
- (void)dealloc;
- (id)description;
@property(retain, nonatomic) NSString *groupID; // @synthesize groupID;
@property(nonatomic) _Bool isAutoIncrement; // @synthesize isAutoIncrement;
- (_Bool)isSessionItemValid;
@property(nonatomic) long long lastInsertedRowID; // @synthesize lastInsertedRowID;
@property(nonatomic) unsigned int lastMessageID; // @synthesize lastMessageID;
@property(nonatomic) unsigned int localID; // @synthesize localID;

@end

