//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, WCVideoRender, WXCGroupMember;

@protocol MultiTalkContactsCollectionViewDelegate <NSObject>
- (void)onMultiTalkContactsCollectionViewAnimateToOnePerson;
- (_Bool)onMultiTalkContactsCollectionViewIsVideoUserName:(NSString *)arg1;
- (WXCGroupMember *)onMultiTalkContactsCollectionViewMemberAtIndex:(unsigned long long)arg1;
- (NSString *)onMultiTalkContactsCollectionViewMemberBeforeTalkingAtIndex:(unsigned long long)arg1;
- (unsigned long long)onMultiTalkContactsCollectionViewMemberCountBeforeTalking;
- (NSString *)onMultiTalkContactsCollectionViewMemberThatInviteMeBeforeTalking;
- (void)onMultiTalkContactsCollectionViewOnBigView;
- (void)onMultiTalkContactsCollectionViewOnNormalView;
- (WCVideoRender *)onMultiTalkContactsCollectionViewRequestRenderForUsername:(NSString *)arg1;
- (void)onMultiTalkContactsCollectionViewTapToFlipCamera;
- (void)onMultiTalkContactsCollectionViewTapToInviteUser:(NSString *)arg1;
- (void)onMultiTalkContactsCollectionViewTapToPreviewWithUserName:(NSString *)arg1;
- (unsigned long long)onMultiTalkContactsCollectionViewTotalMemberCount;
@end

