//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ReaderItemView.h"

#import "MMMusicPlayerContollerDelegate.h"
#import "MMWebImageViewDelegate.h"

@class MMMusicInfo, MMMusicPlayerContoller, NSString, UIImageView, UIView;

@interface MusicReaderItemView : ReaderItemView <MMMusicPlayerContollerDelegate, MMWebImageViewDelegate>
{
    UIImageView *m_bgImageView;
    UIView *m_titleSingerView;
    MMMusicPlayerContoller *m_playButton;
    MMMusicInfo *_musicInfo;
    unsigned long long _musicSource;
}

- (void).cxx_destruct;
- (void)initCoverImageView;
- (void)initPlayBtn:(_Bool)arg1 loading:(_Bool)arg2;
@property(retain, nonatomic) MMMusicInfo *musicInfo; // @synthesize musicInfo=_musicInfo;
@property(nonatomic) unsigned long long musicSource; // @synthesize musicSource=_musicSource;
- (void)onLoadImageOK:(id)arg1;
- (void)setPlayBtnLoading:(_Bool)arg1;
- (void)topView;
- (id)viewForTitleAndSingerLabel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

