//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MyBufferRange : NSObject
{
    unsigned long long _length;
    CDStruct_1b6d18a9 _time;
}

@property unsigned long long length; // @synthesize length=_length;
@property CDStruct_1b6d18a9 time; // @synthesize time=_time;

@end

