//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class ImageViewData, TextViewData;

@interface NavigationCtrlItem : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) ImageViewData *image; // @dynamic image;
@property(retain, nonatomic) TextViewData *text; // @dynamic text;
@property(nonatomic) int type; // @dynamic type;

@end

