//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface NewTipsConfigCenter : NSObject
{
    NSMutableDictionary *_dictNewTipsConfig;
}

- (void).cxx_destruct;
- (id)GetPathOfNewTipsConfig;
- (id)GetRootPathOfNewTips;
@property(retain, nonatomic) NSMutableDictionary *dictNewTipsConfig; // @synthesize dictNewTipsConfig=_dictNewTipsConfig;
- (id)getConfigWithId:(unsigned int)arg1 Version:(unsigned int)arg2 Key:(id)arg3 Type:(unsigned long long)arg4 FilterClass:(id)arg5 Path:(id)arg6;
- (id)getDictNewTipsConfig;
- (id)getNewTipsConfigWithTipsId:(unsigned int)arg1;
- (id)init;
- (void)loadTipsConfig;
- (void)registerDynamicTipsWithId:(unsigned int)arg1;
- (void)registerDynamicTipsWithId:(unsigned int)arg1 FilterClass:(id)arg2 Path:(id)arg3;
- (void)registerInteractiveTipsWithId:(unsigned int)arg1 FilterClass:(id)arg2 Path:(id)arg3;
- (void)registerInteractiveWithId:(unsigned int)arg1;
- (void)registerLocalTipsWithId:(unsigned int)arg1 Version:(unsigned int)arg2 Key:(id)arg3;
- (void)registerLocalTipsWithId:(unsigned int)arg1 Version:(unsigned int)arg2 Key:(id)arg3 FilterClass:(id)arg4 Path:(id)arg5;
- (void)registerNewTipsCenter;
- (void)registerTipsWithId:(unsigned int)arg1 Version:(unsigned int)arg2 Key:(id)arg3 Type:(unsigned long long)arg4 FilterClass:(id)arg5 Path:(id)arg6;
- (void)syncConfigsToFile;

@end

