//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IMsgExt.h"
#import "MMService.h"

@class NSString, NewYearCtrlData;

@interface NewYearCtrlMgr : MMService <IMsgExt, MMService>
{
    NewYearCtrlData *_ctrlData;
}

- (void).cxx_destruct;
- (void)OnGetNewXmlMsg:(id)arg1 Type:(id)arg2 MsgWrap:(id)arg3;
- (void)handleMiniAppNoticeXML:(id)arg1 msgSvrId:(long long)arg2;
- (void)handleNewYearCtrlInfoXml:(id)arg1;
- (_Bool)hasCtrlDataFile;
- (void)loadCtrlData;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)onServiceReloadData;
- (id)parseNewYearCtrlInfoFromXML:(id)arg1;
- (id)parseTemplateMsgFromXML:(id)arg1;
- (void)reloadCtrlData;
- (void)saveCtrlData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

