//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSString, WCBusinessJumpViewController;

@interface OpenSDKLaunchFakeNativeMiniProgramContext : MMObject
{
    NSString *_appId;
    NSString *_businessType;
    NSString *_query;
    unsigned long long _miniProgramType;
    WCBusinessJumpViewController *_jumpViewController;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(copy, nonatomic) NSString *businessType; // @synthesize businessType=_businessType;
- (id)description;
@property(retain, nonatomic) WCBusinessJumpViewController *jumpViewController; // @synthesize jumpViewController=_jumpViewController;
@property(nonatomic) unsigned long long miniProgramType; // @synthesize miniProgramType=_miniProgramType;
@property(copy, nonatomic) NSString *query; // @synthesize query=_query;

@end

