//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class BaseResponse, LQTDepositBanner, NSMutableArray, NSString;

@interface PlanIndexResp : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) LQTDepositBanner *banner; // @dynamic banner;
@property(retain, nonatomic) BaseResponse *baseResponse; // @dynamic baseResponse;
@property(retain, nonatomic) NSString *indexDesc; // @dynamic indexDesc;
@property(nonatomic) unsigned long long limitCnt; // @dynamic limitCnt;
@property(retain, nonatomic) NSString *overPlanlimitDesc; // @dynamic overPlanlimitDesc;
@property(retain, nonatomic) NSMutableArray *planList; // @dynamic planList;
@property(nonatomic) int retCode; // @dynamic retCode;
@property(retain, nonatomic) NSString *retMsg; // @dynamic retMsg;

@end

