//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PreEnterBaseStep.h"

@class NSString;

@interface PreEnterSetTrustedFriendsStep : PreEnterBaseStep
{
    NSString *m_content;
}

- (void).cxx_destruct;
- (id)initWithXml:(id)arg1;
- (void)showTrustedFriendsVC:(id)arg1;
- (void)startStep;

@end

