//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBMessageObserverDelegate.h"

@class NSMutableDictionary;

@interface PublicWifiReportQuality : NSObject <PBMessageObserverDelegate>
{
    NSMutableDictionary *_reportQualityInfoList;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)addReportInfoWithApBase:(id)arg1 protoType:(int)arg2 shopId:(id)arg3 errscene:(unsigned int)arg4 userName:(id)arg5 timecost:(unsigned int)arg6;
- (void)dealloc;
- (id)genContentJSONWithReportInfo:(id)arg1;
- (id)init;
- (void)removeReportedItemWithReportId:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *reportQualityInfoList; // @synthesize reportQualityInfoList=_reportQualityInfoList;
- (void)sendReportRequest;

@end

