//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface QBPostRequestDataManager : NSObject
{
    NSMutableDictionary *_dicData;
}

+ (id)appendBodyForRequest:(id)arg1 originURLString:(id *)arg2;
+ (void)setHTTPBodyElementData:(id)arg1 forRequest:(id)arg2;
+ (void)setHTTPBodyElementStream:(id)arg1 forRequest:(id)arg2;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)addPostDataElement:(id)arg1 forURLString:(id)arg2 mainURLString:(id)arg3;
- (id)arrayFromContainerWithKey:(id)arg1;
- (id)arrayFromKey:(id)arg1;
@property(retain) NSMutableDictionary *dicData; // @synthesize dicData=_dicData;
- (void)fillElement:(id)arg1 forRandomString:(long long)arg2 URLString:(id)arg3;
- (id)init;
- (id)postDataElementForURLString:(id)arg1;
- (void)removeAllPostData;
- (void)removeFirstDataForURLString:(id)arg1;

@end

