//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QShape.h"

#import "QOverlay.h"

@class NSString, WAMapCircleData;

@interface QCircle : QShape <QOverlay>
{
    double _radius;
    struct CLLocationCoordinate2D _coordinate;
    CDStruct_02837cd9 _boundingMapRect;
}

+ (id)circleWithCenterCoordinate:(struct CLLocationCoordinate2D)arg1 radius:(double)arg2;
+ (id)circleWithMapRect:(CDStruct_02837cd9)arg1;
@property(nonatomic) CDStruct_02837cd9 boundingMapRect; // @synthesize boundingMapRect=_boundingMapRect;
- (void)calculateBoundingMapRect;
@property(readonly, nonatomic) struct CLLocationCoordinate2D coordinate; // @synthesize coordinate=_coordinate;
- (id)initWithWithCenterCoordinate:(struct CLLocationCoordinate2D)arg1 radius:(double)arg2;
@property(nonatomic) double radius; // @synthesize radius=_radius;
- (void)setCoordinate:(struct CLLocationCoordinate2D)arg1;
@property(retain, nonatomic) WAMapCircleData *userData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

