//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QOverlayHandler.h"

@class UIImage;

@interface QPolylineHandler : QOverlayHandler
{
    UIImage *_styleTextureImage;
    UIImage *_symbolImage;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImage *styleTextureImage; // @synthesize styleTextureImage=_styleTextureImage;
@property(retain, nonatomic) UIImage *symbolImage; // @synthesize symbolImage=_symbolImage;

@end

