//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString, RouteInfo, TextViewData;

@interface RightTextViewData : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) int clickRegion; // @dynamic clickRegion;
@property(nonatomic) int imageType; // @dynamic imageType;
@property(retain, nonatomic) RouteInfo *routeInfo; // @dynamic routeInfo;
@property(retain, nonatomic) TextViewData *text; // @dynamic text;
@property(retain, nonatomic) NSString *viewId; // @dynamic viewId;

@end

