//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class FacingMember, UIImageView;

@interface RSCreateRoomHeadImageView : MMUIView
{
    UIImageView *m_statusView;
    FacingMember *m_facingMember;
}

+ (struct CGSize)getHeadImageSize;
- (void).cxx_destruct;
- (id)initWithFacingMember:(id)arg1;
@property(retain, nonatomic) FacingMember *m_facingMember; // @synthesize m_facingMember;
- (void)updateWithFacingMember:(id)arg1;

@end

