//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IMMFacebookMgrExt.h"
#import "PBMessageObserverDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UITextViewDelegate.h"
#import "scrollViewDelegate.h"

@class MMAnimationTipView, MMLoadingView, MMScrollView, NSMutableArray, NSString, UIImageView, UITextView;

@interface SendWeiboPublishController : MMUIViewController <UIAlertViewDelegate, UITextViewDelegate, PBMessageObserverDelegate, scrollViewDelegate, IMMFacebookMgrExt>
{
    MMLoadingView *m_loadingView;
    MMAnimationTipView *m_tipView;
    UITextView *m_descriptionView;
    MMScrollView *m_scrollView;
    UIImageView *m_textBkgImgView;
    struct stWeixinEntryRow *m_weixinEntry;
    NSMutableArray *m_arrAddShareObjects;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)clickSend:(id)arg1;
- (void)dealloc;
- (void)done:(id)arg1;
- (id)getPlaceHolderString;
- (id)init;
- (void)initData;
- (void)initLoadingView;
- (void)initTipView;
- (void)initView;
@property(nonatomic) struct stWeixinEntryRow *m_weixinEntry; // @synthesize m_weixinEntry;
- (void)onCancel:(id)arg1;
- (void)onExtendTokenFinish:(_Bool)arg1;
- (void)popToTop;
- (void)sendFail;
- (void)sendOK;
- (void)startLoading;
- (void)stopLoading;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)updateTextViewFrame:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

