//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class MMUILabel, UIImageView;

@interface SGCustomButton : UIButton
{
    UIImageView *_iconBkg;
    MMUILabel *_label;
    UIImageView *_icon;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *icon; // @synthesize icon=_icon;
- (id)init;
- (void)initView;
@property(retain, nonatomic) MMUILabel *label; // @synthesize label=_label;
- (void)layoutSubviews;
- (void)setDiscrpiton:(id)arg1;
- (void)setHighlightedStatus;
- (void)setImage:(id)arg1;
- (void)setNormalStatus;
- (void)setPreferMaxWidth:(double)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;

@end

