//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDate;

@interface ShowRatingAchive : NSObject <NSCoding>
{
    unsigned int m_uiLastShowedVersion;
    NSDate *m_dtFirstRecieveTime;
    unsigned int m_uiShowType;
    _Bool _m_bShowing;
    _Bool _m_bUseNewShowRatingStrategy;
    unsigned int m_uiWaitDays;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) _Bool m_bShowing; // @synthesize m_bShowing=_m_bShowing;
@property(nonatomic) _Bool m_bUseNewShowRatingStrategy; // @synthesize m_bUseNewShowRatingStrategy=_m_bUseNewShowRatingStrategy;
@property(retain, nonatomic) NSDate *m_dtFirstRecieveTime; // @synthesize m_dtFirstRecieveTime;
@property(nonatomic) unsigned int m_uiLastShowedVersion; // @synthesize m_uiLastShowedVersion;
@property(nonatomic) unsigned int m_uiShowType; // @synthesize m_uiShowType;
@property(nonatomic) unsigned int m_uiWaitDays; // @synthesize m_uiWaitDays;

@end

