//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface SimpleImgInfo : MMObject
{
    NSString *m_strMsgLocalID;
    unsigned int m_uiCreateTime;
    _Bool m_bExpired;
    id <SimpleImgInfoDelegate> m_delegate;
}

- (void).cxx_destruct;
- (long long)compare:(id)arg1;
- (id)getDefaultImg;
- (id)getIconName;
- (id)getImgPath;
- (id)getSightPath;
- (id)getSquareImgDir;
- (id)getTitle;
- (unsigned int)getVideoTime;
- (_Bool)isAppFileMsg;
- (_Bool)isAppMusicMsg;
- (_Bool)isAppUrlMsg;
- (_Bool)isAppVideoMsg;
- (_Bool)isFileMsg;
- (_Bool)isFromC2C;
- (_Bool)isGifMsg;
- (_Bool)isImgMsg;
- (_Bool)isVideoMsg;
@property(nonatomic) _Bool m_bExpired; // @synthesize m_bExpired;
@property(nonatomic) __weak id <SimpleImgInfoDelegate> m_delegate; // @synthesize m_delegate;
@property(retain, nonatomic) NSString *m_strMsgLocalID; // @synthesize m_strMsgLocalID;
@property(nonatomic) unsigned int m_uiCreateTime; // @synthesize m_uiCreateTime;

@end

