//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMTimer, SimpleRecordState;

@interface SimpleAudioRecorder : NSObject
{
    _Bool _m_hasPrepare;
    MMTimer *_m_meterTimer;
    SimpleRecordState *_m_bufferState;
}

+ (void)sprintRetCode:(int)arg1;
- (void).cxx_destruct;
- (long long)RecordingTime;
- (_Bool)audioQueueStart;
- (_Bool)audioQueueStop;
- (void)clearBuffer;
- (void)clearQueue;
- (void)dealloc;
- (id)getState;
- (id)init;
@property(retain, nonatomic) SimpleRecordState *m_bufferState; // @synthesize m_bufferState=_m_bufferState;
@property(nonatomic) _Bool m_hasPrepare; // @synthesize m_hasPrepare=_m_hasPrepare;
@property(retain, nonatomic) MMTimer *m_meterTimer; // @synthesize m_meterTimer=_m_meterTimer;
- (void)onMeterChange;
- (_Bool)prepareRecord;
- (void)printRetCode:(int)arg1;
- (_Bool)record;
- (void)stop;
- (_Bool)updateBuffer;
- (_Bool)updateDataFormat;
- (_Bool)updateQueue;

@end

