//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "ForwardMessageLogicDelegate.h"
#import "WCActionSheetDelegate.h"
#import "WCCommitViewResultDelegate.h"

@class CContact, EmotionBannerSet, ForwardMessageLogicController, NSString, WCDataItem;

@interface StoreEmotionPageShareLogic : MMObject <WCActionSheetDelegate, ForwardMessageLogicDelegate, WCCommitViewResultDelegate>
{
    ForwardMessageLogicController *m_forwardMsgLogic;
    NSString *m_titleForShareToTimeline;
    NSString *m_titleForShareToFriend;
    NSString *m_desc;
    NSString *m_iconUrl;
    NSString *m_linkUrl;
    int m_shareToTimelineType;
    int m_shareToFriendType;
    NSString *m_pid;
    unsigned int m_packType;
    unsigned int m_designerUin;
    NSString *m_designerName;
    EmotionBannerSet *m_bannerSet;
    CContact *m_shareContact;
    id <MMUIViewControllerDelegate> _delegate;
    WCDataItem *_timeLineDataItem;
}

+ (id)genProductIdFromTimelineUserData:(id)arg1;
- (void).cxx_destruct;
- (void)OnForwardMessageCancel:(id)arg1;
- (void)OnForwardMessageException:(id)arg1;
- (void)OnForwardMessageSend:(id)arg1;
- (void)ReportShareAction:(unsigned long long)arg1 BannerSet:(id)arg2 Type:(unsigned long long)arg3;
- (void)ReportShareAction:(unsigned long long)arg1 DesignerUin:(unsigned int)arg2;
- (void)ReportShareAction:(unsigned long long)arg1 Pid:(id)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(nonatomic) __weak id <MMUIViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)genShareFriendMessage;
- (id)genTimelineUserData;
- (id)genUploadTask;
- (id)getCurrentViewController;
- (id)init;
- (id)initWithBannerSet:(id)arg1;
- (id)initWithPersonalDesigner:(id)arg1 Desc:(id)arg2 OldRedirectUrl:(id)arg3;
- (id)initWithStoreItem:(id)arg1;
- (void)onCancelForwardForForwardView:(id)arg1;
- (void)onDoneForwardForForwardView:(id)arg1;
@property(retain, nonatomic) WCDataItem *timeLineDataItem; // @synthesize timeLineDataItem=_timeLineDataItem;
- (void)shareToFriend;
- (void)shareToTimeline;
- (void)showActionSheetWithSender:(id)arg1;
- (void)showLoadingWithMsg:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

