//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TencentLBSHttpClient : NSObject
{
}

+ (void)configHttpClientWithCallbackQueue;
+ (void)doPostForUrl:(id)arg1 data:(id)arg2 withMaxTimeout:(double)arg3 completionBlock:(CDUnknownBlockType)arg4;

@end

