//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UITextField;

@interface TPIDKeyboardView : UIView
{
    UITextField *curText;
    UIView *myKeyboardiPadPortrait;
    UIView *myKeyboardiPadLandscape;
    long long keybordOrientation;
    int maxInput;
}

+ (void)addLabelOnButton:(id)arg1 text:(id)arg2 frame:(struct CGRect)arg3;
+ (id)createMainKeyboardWithWidth:(int)arg1 andHeight:(int)arg2 ImageNumNormal:(id)arg3 ImageNumPress:(id)arg4 ImageDelNormal:(id)arg5 ImageDelPess:(id)arg6 ImageExtendNormal:(id)arg7 ImageExtendPess:(id)arg8 forTarget:(id)arg9 WithX:(_Bool)arg10;
- (void)OrientationDidChange:(id)arg1;
- (void)UseKeyboardWithImageNumNormalOnIPad:(id)arg1 ImageNumPress:(id)arg2 ImageDelNormal:(id)arg3 ImageDelPess:(id)arg4 ImageExtendNormal:(id)arg5 ImageExtendPess:(id)arg6 forTarget:(id)arg7 Controller:(id)arg8 WithX:(_Bool)arg9;
- (void)UseKeyboardWithImageNumNormalOnIPad:(id)arg1 ImageNumPress:(id)arg2 ImageDelNormal:(id)arg3 ImageDelPess:(id)arg4 forTarget:(id)arg5 Controller:(id)arg6 WithX:(_Bool)arg7;
- (void)addController:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithX:(_Bool)arg1 ImageNumNormal:(id)arg2 ImageNumPress:(id)arg3 ImageDelNormal:(id)arg4 ImageDelPess:(id)arg5;
- (id)initWithX:(_Bool)arg1 ImageNumNormal:(id)arg2 ImageNumPress:(id)arg3 ImageDelNormal:(id)arg4 ImageDelPess:(id)arg5 ImageExtendNormal:(id)arg6 ImageExtendPess:(id)arg7;
@property(nonatomic) int maxInput; // @synthesize maxInput;
- (void)numberKeyBoardClicked:(id)arg1;
- (void)setKeyboradOrientation:(long long)arg1;
- (void)touchInput:(id)arg1;

@end

