//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSPacketResponse.h"

@interface TSPacketOwnerResponse : TSPacketResponse
{
    _Bool _isOwner;
    float _ownerProbability;
}

@property(nonatomic) _Bool isOwner; // @synthesize isOwner=_isOwner;
@property(nonatomic) float ownerProbability; // @synthesize ownerProbability=_ownerProbability;

@end

