//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class GPUImageOutput<GPUImageInput>, NSArray, NSObject<GPUImageInput>, TTGPUImageLayerBuffer, TTGPUImageLayerFrameBuffer, UIColor;

@interface TTGPUImageLayer : NSObject <NSCopying>
{
    float *_texCoordForFramebuffer;
    _Bool _flipX;
    _Bool _flipY;
    _Bool _hidden;
    _Bool _transactionHidden;
    TTGPUImageLayer *_parentNode;
    double _rotate;
    double _scale;
    double _alpha;
    long long _zOrder;
    double _textureScale;
    UIColor *_backgroundColor;
    TTGPUImageLayerBuffer *_backgroundImage;
    long long _backgroundMode;
    TTGPUImageLayerBuffer *_maskImage;
    long long _maskMode;
    NSArray *_childNodes;
    long long _blendMode;
    GPUImageOutput<GPUImageInput> *_effectFilter;
    GPUImageOutput<GPUImageInput> *_terminalFilter;
    long long _terminalFilterIndex;
    TTGPUImageLayer *_transactionLayer;
    NSObject<GPUImageInput> *_filterChainTarget;
    long long _indexTextureOfTheChainTarget;
    TTGPUImageLayerFrameBuffer *_outputBuffer;
    struct CGPoint _anchor;
    struct CGSize _backgroundSize;
    CDStruct_1b6d18a9 _renderTime;
    struct CGRect _frame;
    union _GLKMatrix4 _projectionMat4;
}

- (void).cxx_destruct;
- (void)addChildNode:(id)arg1;
@property(nonatomic) double alpha; // @synthesize alpha=_alpha;
@property(nonatomic) struct CGPoint anchor; // @synthesize anchor=_anchor;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(retain, nonatomic) TTGPUImageLayerBuffer *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(nonatomic) long long backgroundMode; // @synthesize backgroundMode=_backgroundMode;
@property(nonatomic) struct CGSize backgroundSize; // @synthesize backgroundSize=_backgroundSize;
@property(nonatomic) long long blendMode; // @synthesize blendMode=_blendMode;
- (void)childNodePropertyModified;
@property(retain) NSArray *childNodes; // @synthesize childNodes=_childNodes;
- (void)cleanResource;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
- (void)destroyBuffer;
@property(retain, nonatomic) GPUImageOutput<GPUImageInput> *effectFilter; // @synthesize effectFilter=_effectFilter;
@property(retain, nonatomic) NSObject<GPUImageInput> *filterChainTarget; // @synthesize filterChainTarget=_filterChainTarget;
@property(nonatomic) _Bool flipX; // @synthesize flipX=_flipX;
@property(nonatomic) _Bool flipY; // @synthesize flipY=_flipY;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
- (id)framebufferForOutput;
- (_Bool)framebufferPremultipliedAlpha;
- (long long)framebufferTextureType;
- (union _GLKMatrix4)genLookAtMatrix;
- (union _GLKMatrix4)genProjectionMatrix;
- (id)getTopVisibleChild;
@property(nonatomic) _Bool hidden; // @synthesize hidden=_hidden;
@property(nonatomic) long long indexTextureOfTheChainTarget; // @synthesize indexTextureOfTheChainTarget=_indexTextureOfTheChainTarget;
- (void)informFilterChainTargetAtTime:(CDStruct_1b6d18a9)arg1;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)isVisible;
@property(retain, nonatomic) TTGPUImageLayerBuffer *maskImage; // @synthesize maskImage=_maskImage;
@property(nonatomic) long long maskMode; // @synthesize maskMode=_maskMode;
- (int)nodeBuffType;
@property(retain) TTGPUImageLayerFrameBuffer *outputBuffer; // @synthesize outputBuffer=_outputBuffer;
@property(nonatomic) __weak TTGPUImageLayer *parentNode; // @synthesize parentNode=_parentNode;
@property(nonatomic) struct CGPoint position;
@property(readonly, nonatomic) union _GLKMatrix4 projectionMat4; // @synthesize projectionMat4=_projectionMat4;
- (void)removeAllChildNodes;
- (void)removeChildNode:(id)arg1;
@property(nonatomic) CDStruct_1b6d18a9 renderTime; // @synthesize renderTime=_renderTime;
- (void)renderToBuffer:(CDStruct_1b6d18a9)arg1;
- (void)renderToBuffer:(CDStruct_1b6d18a9)arg1 filter:(id)arg2;
- (void)renderToBufferInQueue:(CDStruct_1b6d18a9)arg1 withFilter:(id)arg2;
- (void)renderToView:(id)arg1 time:(CDStruct_1b6d18a9)arg2;
- (void)renderToView:(id)arg1 time:(CDStruct_1b6d18a9)arg2 filter:(id)arg3;
@property(nonatomic) double rotate; // @synthesize rotate=_rotate;
@property(nonatomic) double scale; // @synthesize scale=_scale;
- (void)setNeedDisplay;
@property(retain, nonatomic) GPUImageOutput<GPUImageInput> *terminalFilter; // @synthesize terminalFilter=_terminalFilter;
@property(nonatomic) long long terminalFilterIndex; // @synthesize terminalFilterIndex=_terminalFilterIndex;
@property(nonatomic) double textureScale; // @synthesize textureScale=_textureScale;
@property(nonatomic) _Bool transactionHidden; // @synthesize transactionHidden=_transactionHidden;
@property(retain, nonatomic) TTGPUImageLayer *transactionLayer; // @synthesize transactionLayer=_transactionLayer;
@property(nonatomic) long long zOrder; // @synthesize zOrder=_zOrder;
@property(readonly, nonatomic) struct CGSize size;
- (float *)texCoordForFramebuffer;

@end

