//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, TTImageDetectObject;

@protocol TTImageDetectProcessProtocol <NSObject>
- (TTImageDetectObject *)detectedImageObjectAtFrameTime:(CDStruct_1b6d18a9)arg1 clearCahceObjBefore:(_Bool)arg2;
- (_Bool)waitDetectEnd:(NSString *)arg1 timeout:(double)arg2;
@end

