//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MyCamGPUFilter.h"

@class HFGLTextureWrapper;

@interface UIImageOrientationFilter : MyCamGPUFilter
{
    int _format;
    int _width;
    int _height;
    int _displayWidth;
    HFGLTextureWrapper *texture[2];
    struct __CVBuffer *luminanceTextureRef;
    struct __CVBuffer *chrominanceTextureRef;
    struct __CVBuffer *bgraTextureRef;
    _Bool _useFastUploadMode;
    struct CGSize _pixelBufferSize;
}

- (void).cxx_destruct;
- (void)cleanUpTextures;
- (void)dealloc;
- (struct CGSize)getOutputSize;
- (id)init;
- (id)initWithFaseUploadMode:(_Bool)arg1 format:(int)arg2;
@property(nonatomic) struct CGSize pixelBufferSize; // @synthesize pixelBufferSize=_pixelBufferSize;
- (void)setInputFramebuffer:(id)arg1;
- (void)setInputImage:(id)arg1;
- (void)setInputPixelBuffer:(struct __CVBuffer *)arg1 withFormat:(int)arg2;
@property(nonatomic) _Bool useFastUploadMode; // @synthesize useFastUploadMode=_useFastUploadMode;

@end

