//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface UserOpInfo : NSObject
{
    unsigned int module;
    unsigned long long timestamp;
    unsigned int seq;
    int currentPage;
    int opType;
    NSString *dataflowSourceInfo;
    NSString *dataflowResultInfo;
    NSString *statusDesc1;
    NSString *statusDesc2;
}

- (void).cxx_destruct;
@property(nonatomic) int currentPage; // @synthesize currentPage;
@property(retain, nonatomic) NSString *dataflowResultInfo; // @synthesize dataflowResultInfo;
@property(retain, nonatomic) NSString *dataflowSourceInfo; // @synthesize dataflowSourceInfo;
- (id)genStatInfo;
- (id)init;
@property(nonatomic) unsigned int module; // @synthesize module;
@property(nonatomic) int opType; // @synthesize opType;
- (void)resetStatus;
@property(nonatomic) unsigned int seq; // @synthesize seq;
@property(retain, nonatomic) NSString *statusDesc1; // @synthesize statusDesc1;
@property(retain, nonatomic) NSString *statusDesc2; // @synthesize statusDesc2;
@property(nonatomic) unsigned long long timestamp; // @synthesize timestamp;

@end

