//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVAssetResourceLoaderDelegate.h"
#import "VideoStreamDownloadLogicDelegate.h"

@class NSMutableArray, NSString, VideoStreamDownloadLogic, VideoStreamInfo, VideoStreamKVReportLogic;

@interface VideoStreamPlayerViewModel : NSObject <VideoStreamDownloadLogicDelegate, AVAssetResourceLoaderDelegate>
{
    unsigned int m_uiLoadingRequestNum;
    NSMutableArray *m_arrPendingRequests;
    NSMutableArray *m_arrDownloadTaskArray;
    VideoStreamDownloadLogic *m_oDownloadLogic;
    VideoStreamKVReportLogic *m_oKVReportLogic;
    VideoStreamInfo *m_oVideoInfo;
    _Bool _bShouldLoadStreamResource;
    unsigned int _m_uiSeekTime;
    id <NSObject><VideoStreamPlayerViewModeDelegate> _delegate;
    long long _loadingRequestTotalLength;
}

- (void).cxx_destruct;
- (void)OnDownloadVideoErrorExpired:(_Bool)arg1;
- (void)OnSnsVideoChanged;
- (void)addLoadingRequest:(id)arg1;
- (void)addOneSliceTimeDownloadTask;
- (void)addWCAVDownloadTaskBySec:(float)arg1;
@property(nonatomic) _Bool bShouldLoadStreamResource; // @synthesize bShouldLoadStreamResource=_bShouldLoadStreamResource;
- (void)cancelAllPendingRequests;
- (void)checkData:(id)arg1 length:(unsigned int)arg2;
- (void)cleanDownloadTask;
- (void)consumeDownloadTask;
@property(nonatomic) __weak id <NSObject><VideoStreamPlayerViewModeDelegate> delegate; // @synthesize delegate=_delegate;
- (void)fillInformationForRequest:(id)arg1;
- (id)init;
- (id)initWithHttpUrl:(id)arg1 filePath:(id)arg2;
- (id)initWithMediaItem:(id)arg1 KVReportLogic:(id)arg2;
- (id)initWithVideoMessage:(id)arg1 KVReportLogic:(id)arg2;
- (id)loaderCancelledError;
@property(nonatomic) long long loadingRequestTotalLength; // @synthesize loadingRequestTotalLength=_loadingRequestTotalLength;
@property(nonatomic) unsigned int m_uiSeekTime; // @synthesize m_uiSeekTime=_m_uiSeekTime;
- (void)onDownloadVideoReturn:(id)arg1;
- (void)onDownloadVideoSuccess;
- (void)onGetAVDataFromNetOffset:(unsigned int)arg1 Length:(unsigned int)arg2 NeedNotifyToPlay:(_Bool)arg3;
- (void)onGetFristPartAVData;
- (void)processPendingRequestsFromOffset:(unsigned int)arg1 length:(unsigned int)arg2;
- (void)removeLoadingRequest:(id)arg1;
- (void)requestAllData;
- (void)resourceLoader:(id)arg1 didCancelLoadingRequest:(id)arg2;
- (_Bool)resourceLoader:(id)arg1 shouldWaitForLoadingOfRequestedResource:(id)arg2;
- (_Bool)respondWithDataForRequest:(id)arg1 offset:(unsigned int)arg2 length:(unsigned int)arg3;
- (void)setVideoInfo:(id)arg1;
- (unsigned long long)startVideoStreamDownload;
- (void)stopVideoStreamDownload;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

