//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MonoServiceMsg.h"

@class NSString, WXLocalNotificationInfo;

@interface VoipMonoMsg : MonoServiceMsg
{
    _Bool _m_fromAnswered;
    unsigned int _m_receiveTime;
    unsigned int _m_msgType;
    unsigned int _m_mode;
    int _m_roomId;
    unsigned int _m_fromScene;
    long long _m_roomKey;
    NSString *_m_fromUser;
    WXLocalNotificationInfo *_m_notificationInfo;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)init;
- (_Bool)isCancelMsg;
- (_Bool)isOutOfDate;
- (_Bool)isParaVaild;
- (_Bool)isTheSameToMsg:(id)arg1;
- (id)localNotificationInfo;
@property(nonatomic) _Bool m_fromAnswered; // @synthesize m_fromAnswered=_m_fromAnswered;
@property(nonatomic) unsigned int m_fromScene; // @synthesize m_fromScene=_m_fromScene;
@property(retain, nonatomic) NSString *m_fromUser; // @synthesize m_fromUser=_m_fromUser;
@property(nonatomic) unsigned int m_mode; // @synthesize m_mode=_m_mode;
@property(nonatomic) unsigned int m_msgType; // @synthesize m_msgType=_m_msgType;
@property(retain, nonatomic) WXLocalNotificationInfo *m_notificationInfo; // @synthesize m_notificationInfo=_m_notificationInfo;
@property(nonatomic) unsigned int m_receiveTime; // @synthesize m_receiveTime=_m_receiveTime;
@property(nonatomic) int m_roomId; // @synthesize m_roomId=_m_roomId;
@property(nonatomic) long long m_roomKey; // @synthesize m_roomKey=_m_roomKey;
- (id)msgKey;
- (_Bool)receiveTimeOutOfDate;
- (id)serviceType;

@end

