//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError;

@protocol WAAudioSourceDelegate <NSObject>
- (void)sourceDidError:(id <WAAudioSource>)arg1 error:(NSError *)arg2;
- (void)sourceDidFinishPlaying:(id <WAAudioSource>)arg1;
- (void)sourcePaused:(id <WAAudioSource>)arg1;
- (void)sourceSeeked:(id <WAAudioSource>)arg1;
- (void)sourceSeeking:(id <WAAudioSource>)arg1;
- (void)sourceStartPlaying:(id <WAAudioSource>)arg1;
- (void)sourceStop:(id <WAAudioSource>)arg1;
@end

