//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WARecordEncodeDelegate.h"
#import "WCAudioSessionExt.h"

@class NSDictionary, NSMutableData, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>, NSString, NSURL;

@interface WABaseRecorder : NSObject <WARecordEncodeDelegate, WCAudioSessionExt>
{
    struct WARecorderData *mAqData;
    unsigned long long mState;
    NSObject<OS_dispatch_queue> *mRecordQueue;
    NSURL *mUrl;
    NSDictionary *mSettings;
    unsigned long long mFrameRecordByteSize;
    id <WARecorderDelegate> mDelegate;
    NSMutableData *mEncodeBufferData;
    _Bool _timerOnFire;
    double _duration;
    double _startTime;
    double _recordTime;
    NSObject<OS_dispatch_source> *_timer;
    NSString *_inputSource;
}

+ (id)recorderWithFilePath:(id)arg1 settings:(id)arg2;
- (void).cxx_destruct;
- (void)activeAudioSession;
- (_Bool)checkErrorAndLogIfError:(int)arg1 withErrorString:(id)arg2;
- (_Bool)checkErrorAndStopIfError:(int)arg1 withErrorString:(id)arg2;
- (void)clearRecorderState;
@property(readonly, getter=currentTime) double currentTime;
- (void)dealloc;
@property(nonatomic) __weak id <WARecorderDelegate> delegate;
@property(nonatomic) double duration; // @synthesize duration=_duration;
- (void)encodePCMBufferToOutputFormat:(struct WARecorderData *)arg1 audioQueueRef:(struct OpaqueAudioQueue *)arg2 audioQueueBufferRef:(struct AudioQueueBuffer *)arg3 audioTimeStamp:(const struct AudioTimeStamp *)arg4 numPackets:(unsigned int)arg5 packetDescription:(const struct AudioStreamPacketDescription *)arg6;
- (id)initWithURL:(id)arg1 settings:(id)arg2;
@property(retain, nonatomic) NSString *inputSource; // @synthesize inputSource=_inputSource;
@property(readonly, getter=isIdle) _Bool isIdle;
@property(readonly, getter=isPaused) _Bool isPaused;
@property(readonly, getter=isRecording) _Bool recording;
- (void)onNotifyFrameRecordOnMainThread:(id)arg1 isLastFrame:(_Bool)arg2;
- (void)onNotifyStateChangeOnMainThread:(unsigned long long)arg1 error:(id)arg2;
- (void)onWCAudioSessionNewDeviceAvailable;
- (void)onWCAudioSessionOldDeviceUnavailable;
- (void)pause;
- (void)prepareToRecord;
- (void)record;
@property(nonatomic) double recordTime; // @synthesize recordTime=_recordTime;
- (void)resume;
- (void)setInputSourceIfNeed;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *timer; // @synthesize timer=_timer;
@property(nonatomic) _Bool timerOnFire; // @synthesize timerOnFire=_timerOnFire;
@property(readonly, nonatomic, getter=settings) NSDictionary *settings;
@property(readonly, getter=state) unsigned long long state;
- (void)stop;
- (void)unActiveAudioSession;
@property(readonly, nonatomic, getter=url) NSURL *url;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

