//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IWALocalCacheMgrExt.h"

@class NSDictionary, NSMutableArray, NSString, WAAppTaskExtInfo, WAInfoData, WALoadingViewController;

@interface WACacheVersionChecker : NSObject <IWALocalCacheMgrExt>
{
    unsigned long long _checkScene;
    NSString *_appID;
    NSString *_userName;
    WAInfoData *_appInfoData;
    unsigned int _appType;
    _Bool _isCancelled;
    CDUnknownBlockType _completeHandler;
    CDUnknownBlockType _progressHandler;
    _Bool _isUseModule;
    WAInfoData *_bootModuleInfoData;
    WAInfoData *_subModuleInfoData;
    NSMutableArray *_arrDownloadInfoData;
    NSDictionary *_dicExtraInfo;
    WAAppTaskExtInfo *_taskExtInfo;
    NSString *_relativePath;
    WALoadingViewController *_loadingVC;
    unsigned long long _startDownloadTime;
    _Bool _isDownloadStart;
    _Bool _hasReported;
    unsigned long long _updatePackageStartTime;
}

- (void).cxx_destruct;
- (void)addDownloadInfoData:(id)arg1;
- (unsigned long long)appstateWithExtraInfo:(id)arg1;
- (void)callCompletionHandlerWithSuccess:(_Bool)arg1 errorCode:(long long)arg2;
- (void)cancel;
- (void)checkCacheReadyWithContext:(id)arg1 completeHandler:(CDUnknownBlockType)arg2 progressHandler:(CDUnknownBlockType)arg3;
- (_Bool)checkLocalCacheOK:(id)arg1;
- (void)checkLocalCacheWithInfoDataList:(id)arg1 getDownloadInfoDataList:(id)arg2;
- (void)checkModuleCacheReadyWithPackageConfig:(id)arg1 moduleName:(id)arg2 completeHandler:(CDUnknownBlockType)arg3 progressHandler:(CDUnknownBlockType)arg4;
- (void)dealloc;
- (unsigned long long)downloadInfoDataCount;
- (id)generateInfoDataWithPackageConfig:(id)arg1 relativeUrl:(id)arg2;
- (id)getBootModuleInfoDataWithPackageConfig:(id)arg1 relativeUrl:(id)arg2;
- (_Bool)getDebugModePkgDownloadUrlWithAppInfoData:(id)arg1;
- (id)getInfoDataWithPackageConfig:(id)arg1 moduleName:(id)arg2;
- (_Bool)getRemoteCDNPkgDownloadUrlWithAppInfoData:(id)arg1;
- (void)handleGetDebugModePkgDownloadUrl:(id)arg1;
- (void)handleGetRemoteCDNPkgDownloadUrl:(id)arg1;
- (_Bool)hasDownloadInfoData:(id)arg1;
- (id)initWithAppID:(id)arg1;
- (void)onCgiResponse:(id)arg1 forEvent:(unsigned int)arg2;
- (void)onUpdateAppPkgComplete:(_Bool)arg1 withAppInfoData:(id)arg2 errorCode:(unsigned int)arg3 errorMsg:(id)arg4;
- (void)onUpdateAppPkgProgress:(float)arg1 remainingTime:(unsigned long long)arg2 totalLength:(unsigned long long)arg3 withAppInfoData:(id)arg4;
- (void)removeDownloadInfoData:(id)arg1;
- (void)reportIntallOrUpdateInfo:(_Bool)arg1 errorCode:(unsigned int)arg2;
- (void)reportLoadPackageInvalid:(id)arg1;
- (void)reportPluginCodesDownloadIDKey:(_Bool)arg1 packageType:(unsigned long long)arg2;
- (void)reportSplitPluginCodeStatisCheckData:(id)arg1 arrDownload:(id)arg2;
- (void)reportUpdatePackageTime;
- (void)resetOldExistVersionIfFileNotExist:(id)arg1;
- (_Bool)startDownloadPkgWithAppInfoData:(id)arg1 CDNURL:(id)arg2 CDNURLWithZstd:(id)arg3 patchURL:(id)arg4;
- (void)triggerPkgDownloadWithAppInfoData:(id)arg1;
- (void)tryDoDecryptAndRemoveDecryptEnabledInfoData:(id)arg1;
- (void)unfoldInfoData:(id)arg1;

@end

