//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXBaseWebViewController.h"

#import "UIGestureRecognizerDelegate.h"
#import "WAPageFlowReportExtention.h"

@class FixDocumentPresent, MMWebProgressBar, NSString, UILabel, WAWebViewController, WAWebViewPlugin_HTMLWeb;

@interface WAHTMLWebViewController : WXBaseWebViewController <UIGestureRecognizerDelegate, WAPageFlowReportExtention>
{
    NSString *m_oLoadingUrl;
    UILabel *m_addressLabel;
    long long m_nHttpRspCode;
    _Bool _didReceiveTerm;
    unsigned int _htmlId;
    WAWebViewPlugin_HTMLWeb *_plugin;
    WAWebViewController *_superVC;
    MMWebProgressBar *_progressBar;
    FixDocumentPresent *_presentProxy;
    struct CGRect _viewRect;
}

- (void).cxx_destruct;
- (void)EXReport_onAppExit:(unsigned int)arg1 onPage:(id)arg2;
- (void)EXReport_onBackOnPage:(id)arg1 toPage:(id)arg2;
- (void)EXReport_onTargetToNativaPage:(id)arg1;
- (void)configProgressBarWithWidth:(double)arg1;
- (void)configViewFrame:(struct CGRect)arg1;
- (void)dealloc;
@property(nonatomic) _Bool didReceiveTerm; // @synthesize didReceiveTerm=_didReceiveTerm;
- (void)dismissViewControllerAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (id)getAddressBarHostText:(id)arg1;
- (id)getDeafultReportHTMLJSAPIItem;
- (id)getDefaultHtmlActionItem;
- (void)handleHTMLViewDidBePoped;
- (void)handleInsertHTMLDone;
- (void)hideLoadFailView;
@property(nonatomic) unsigned int htmlId; // @synthesize htmlId=_htmlId;
- (void)initAddressBarLabel;
- (id)initWithURL:(id)arg1 extraInfo:(id)arg2;
- (void)onAppExit:(unsigned int)arg1 onPage:(id)arg2;
- (void)onBackOnPage:(id)arg1 toPage:(id)arg2;
- (void)onClickFailView:(id)arg1;
- (void)onTargetActionWebJump:(id)arg1 navigationType:(long long)arg2;
- (void)onTargetToNativaPage:(id)arg1;
@property(nonatomic) __weak WAWebViewPlugin_HTMLWeb *plugin; // @synthesize plugin=_plugin;
@property(retain, nonatomic) FixDocumentPresent *presentProxy; // @synthesize presentProxy=_presentProxy;
- (void)presentViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) MMWebProgressBar *progressBar; // @synthesize progressBar=_progressBar;
- (void)relayoutLoadFailView;
- (void)reportCurrentPageInfo:(unsigned long long)arg1;
- (void)reportJSApiRespForEvent:(id)arg1 result:(id)arg2;
- (void)restoreAddressBar;
@property(nonatomic) __weak WAWebViewController *superVC; // @synthesize superVC=_superVC;
@property(nonatomic) struct CGRect viewRect; // @synthesize viewRect=_viewRect;
- (void)showLoadFailView:(unsigned int)arg1 errorCode:(long long)arg2;
- (void)updateHTMLFrame;
- (void)updateWeAppUserAgent;
- (_Bool)useBlackStatusbar;
- (_Bool)useCustomNavibar;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)webViewController:(id)arg1 didFailLoadWithError:(id)arg2;
- (_Bool)webViewController:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3 isMainFrame:(_Bool)arg4;
- (id)webViewControllerBackgroundColor;
- (void)webViewControllerContentProcessDidTerminate:(id)arg1;
- (void)webViewControllerDidFinishLoad:(id)arg1;
- (void)webViewControllerDidStartLoad:(id)arg1;
- (void)webViewControllerDidStartSyncA8Key:(id)arg1;
- (void)webViewControllerForceSyncA8KeyError;
- (void)webViewControllerJSApiRespForEvent:(id)arg1 result:(id)arg2;
- (id)webViewControllerPreInjectScriptStr;
- (void)webViewControllerTitleDidChange:(id)arg1;
- (void)webViewDidReceiveResponse:(id)arg1 isMainFrame:(_Bool)arg2;
- (id)webviewForInitialization;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

