//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding.h"

@class NSString;

@interface WALocationWrap : MMObject <PBCoding>
{
    int floor;
    double latitude;
    double longitude;
    double altitude;
    double horizontalAccuracy;
    double verticalAccuracy;
    double course;
    double speed;
    double timestamp;
}

+ (void)initialize;
@property(nonatomic) double altitude; // @synthesize altitude;
@property(nonatomic) double course; // @synthesize course;
@property(nonatomic) int floor; // @synthesize floor;
- (const map_f8690629 *)getValueTagIndexMap;
- (id)getValueTypeTable;
@property(nonatomic) double horizontalAccuracy; // @synthesize horizontalAccuracy;
@property(nonatomic) double latitude; // @synthesize latitude;
@property(nonatomic) double longitude; // @synthesize longitude;
@property(nonatomic) double speed; // @synthesize speed;
@property(nonatomic) double timestamp; // @synthesize timestamp;
@property(nonatomic) double verticalAccuracy; // @synthesize verticalAccuracy;
- (id)transferToCLLocation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

