//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, NSThread;

@interface WAMsgNodeThreadInfo : NSObject
{
    unsigned int _createTime;
    NSThread *_thread;
    NSString *_appId;
    NSDictionary *_userInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(nonatomic) unsigned int createTime; // @synthesize createTime=_createTime;
- (id)description;
@property(retain, nonatomic) NSThread *thread; // @synthesize thread=_thread;
@property(retain, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;

@end

