//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAOpenSDKJSEventHandler_BaseEvent.h"

#import "ForwardMessageLogicDelegate.h"

@class ForwardMessageLogicController, NSData, NSDictionary, NSMutableArray, NSMutableDictionary, NSString;

@interface WAOpenSDKJSEventHandler_shareAppMessage : WAOpenSDKJSEventHandler_BaseEvent <ForwardMessageLogicDelegate>
{
    _Bool _shouldUseUpdatableShare;
    int _cardType;
    ForwardMessageLogicController *_forwardLogic;
    NSDictionary *_dic;
    NSData *_thumbData;
    NSString *_updatableShareTemplateId;
    NSMutableArray *_reportArray;
    NSMutableDictionary *_shareKeys;
}

- (void).cxx_destruct;
- (void)OnForwardMessageCancel:(id)arg1;
- (void)OnForwardMessageException:(id)arg1;
- (void)OnForwardMessageSelectSession:(id)arg1;
- (void)OnForwardMessageSend:(id)arg1;
- (void)OnForwardWeAppMessageSend:(id)arg1 appMsgItem:(id)arg2;
@property(nonatomic) int cardType; // @synthesize cardType=_cardType;
- (void)dealloc;
@property(retain, nonatomic) NSDictionary *dic; // @synthesize dic=_dic;
@property(retain, nonatomic) ForwardMessageLogicController *forwardLogic; // @synthesize forwardLogic=_forwardLogic;
- (id)getCurrentViewController;
- (void)handleJSEvent:(id)arg1;
- (void)onCgiResponse:(id)arg1 forEvent:(unsigned int)arg2;
@property(retain, nonatomic) NSMutableArray *reportArray; // @synthesize reportArray=_reportArray;
- (void)reportWeAppForwardMessage:(id)arg1;
- (void)reportWebviewMenuAction:(unsigned long long)arg1 actionResult:(unsigned long long)arg2 actionNote:(id)arg3 errCode:(int)arg4;
@property(retain, nonatomic) NSMutableDictionary *shareKeys; // @synthesize shareKeys=_shareKeys;
@property(nonatomic) _Bool shouldUseUpdatableShare; // @synthesize shouldUseUpdatableShare=_shouldUseUpdatableShare;
@property(retain, nonatomic) NSData *thumbData; // @synthesize thumbData=_thumbData;
@property(retain, nonatomic) NSString *updatableShareTemplateId; // @synthesize updatableShareTemplateId=_updatableShareTemplateId;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

