//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAReportBaseItem.h"

@class NSString;

@interface WAReportGameCBFPSItem : WAReportBaseItem
{
    unsigned int _duration;
    unsigned int _useCommandBuffer;
    NSString *_appname;
    long long _drawCall;
    long long _time;
    long long _fps;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *appname; // @synthesize appname=_appname;
@property(nonatomic) long long drawCall; // @synthesize drawCall=_drawCall;
@property(nonatomic) unsigned int duration; // @synthesize duration=_duration;
@property(nonatomic) long long fps; // @synthesize fps=_fps;
- (id)reportString;
@property(nonatomic) long long time; // @synthesize time=_time;
@property(nonatomic) unsigned int useCommandBuffer; // @synthesize useCommandBuffer=_useCommandBuffer;

@end

