//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAReportBaseItem.h"

@class NSString;

@interface WAReportPatchUpdateItem : WAReportBaseItem
{
    _Bool _canUsePatchUpdate;
    _Bool _isUpdateComplete;
    _Bool _isUpdateCompleteWithPatch;
    unsigned int _fullPkgSize;
    unsigned int _patchSize;
    unsigned int _patchError;
    unsigned int _gzipReadyTime;
    unsigned int _zstdReadyTime;
    unsigned int _pkgType;
    long long _oldVersion;
    long long _targetVersion;
    long long _beginTime;
    long long _endTime;
    NSString *_moduleName;
}

- (void).cxx_destruct;
@property(nonatomic) long long beginTime; // @synthesize beginTime=_beginTime;
@property(nonatomic) _Bool canUsePatchUpdate; // @synthesize canUsePatchUpdate=_canUsePatchUpdate;
@property(nonatomic) long long endTime; // @synthesize endTime=_endTime;
@property(nonatomic) unsigned int fullPkgSize; // @synthesize fullPkgSize=_fullPkgSize;
@property(nonatomic) unsigned int gzipReadyTime; // @synthesize gzipReadyTime=_gzipReadyTime;
@property(nonatomic) _Bool isUpdateComplete; // @synthesize isUpdateComplete=_isUpdateComplete;
@property(nonatomic) _Bool isUpdateCompleteWithPatch; // @synthesize isUpdateCompleteWithPatch=_isUpdateCompleteWithPatch;
@property(retain, nonatomic) NSString *moduleName; // @synthesize moduleName=_moduleName;
@property(nonatomic) long long oldVersion; // @synthesize oldVersion=_oldVersion;
@property(nonatomic) unsigned int patchError; // @synthesize patchError=_patchError;
@property(nonatomic) unsigned int patchSize; // @synthesize patchSize=_patchSize;
@property(nonatomic) unsigned int pkgType; // @synthesize pkgType=_pkgType;
- (int)reportID;
- (id)reportString;
@property(nonatomic) long long targetVersion; // @synthesize targetVersion=_targetVersion;
@property(nonatomic) unsigned int zstdReadyTime; // @synthesize zstdReadyTime=_zstdReadyTime;

@end

