//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIPanGestureRecognizer, UIScrollView;

@interface WARefreshComponent : UIView
{
    struct UIEdgeInsets _scrollViewOriginalInset;
    UIScrollView *_scrollView;
    CDUnknownBlockType _refreshingBlock;
    CDUnknownBlockType _beginRefreshingCompletionBlock;
    CDUnknownBlockType _endRefreshingCompletionBlock;
    long long _state;
    double _pullingPercent;
    UIPanGestureRecognizer *_pan;
}

- (void).cxx_destruct;
- (void)addObservers;
- (void)beginRefreshing;
@property(copy, nonatomic) CDUnknownBlockType beginRefreshingCompletionBlock; // @synthesize beginRefreshingCompletionBlock=_beginRefreshingCompletionBlock;
- (void)beginRefreshingWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)endRefreshing;
@property(copy, nonatomic) CDUnknownBlockType endRefreshingCompletionBlock; // @synthesize endRefreshingCompletionBlock=_endRefreshingCompletionBlock;
- (void)endRefreshingWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)executeRefreshingCallback;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)isRefreshing;
- (void)layoutSubviews;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(retain, nonatomic) UIPanGestureRecognizer *pan; // @synthesize pan=_pan;
- (void)placeSubviews;
- (void)prepare;
@property(nonatomic) double pullingPercent; // @synthesize pullingPercent=_pullingPercent;
@property(copy, nonatomic) CDUnknownBlockType refreshingBlock; // @synthesize refreshingBlock=_refreshingBlock;
- (void)removeObservers;
@property(readonly, nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)scrollViewContentOffsetDidChange:(id)arg1;
- (void)scrollViewContentSizeDidChange:(id)arg1;
@property(readonly, nonatomic) struct UIEdgeInsets scrollViewOriginalInset; // @synthesize scrollViewOriginalInset=_scrollViewOriginalInset;
- (void)scrollViewPanStateDidChange:(id)arg1;
@property(nonatomic) long long state; // @synthesize state=_state;
- (void)willMoveToSuperview:(id)arg1;

@end

