//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface WARemoteDebugRecvQueue : NSObject
{
    NSMutableArray *_recvIntervalList;
    unsigned int _currRecvSeq;
    unsigned int _prevRecvSeq;
    unsigned int _accumulateCount;
    id <WARemoteDebugRecvQueueDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)clearAccumulateCount;
- (void)dealloc;
@property(nonatomic) __weak id <WARemoteDebugRecvQueueDelegate> delegate; // @synthesize delegate=_delegate;
- (unsigned int)getCurrRecvSeq;
- (unsigned int)getIntervalRecvCount;
- (void)handleFirstRecvInterval;
- (id)init;
- (void)logRecvIntervalList;
- (void)mergeMessages:(id)arg1 cmdID:(unsigned int)arg2;

@end

