//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSArray, NSData, NSString, SubscribeMsgShowInfo;

@interface WASubscriptionMessagePageSheetViewModel : MMObject
{
    _Bool _keepOption;
    int _style;
    int _templateType;
    unsigned long long _headerStyleOptions;
    unsigned long long _footerStyleOptions;
    unsigned long long _scene;
    NSString *_iconUrl;
    NSString *_appName;
    NSString *_applyDescription;
    NSString *_mainDescription;
    NSString *_subDescription;
    NSString *_confirmWording;
    NSString *_cancelWording;
    NSString *_declineWording;
    NSString *_keepOptionWording;
    NSString *_detailTitle;
    NSArray *_messageItems;
    NSString *_username;
    NSData *_buffer;
    unsigned long long _operationType;
    SubscribeMsgShowInfo *_showInfo;
    NSString *_kvUid;
    long long _errorCode;
    NSString *_errorMessage;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *appName; // @synthesize appName=_appName;
@property(copy, nonatomic) NSString *applyDescription; // @synthesize applyDescription=_applyDescription;
@property(copy, nonatomic) NSData *buffer; // @synthesize buffer=_buffer;
@property(copy, nonatomic) NSString *cancelWording; // @synthesize cancelWording=_cancelWording;
- (void)checkDataValidWithResultBlock:(CDUnknownBlockType)arg1;
@property(copy, nonatomic) NSString *confirmWording; // @synthesize confirmWording=_confirmWording;
@property(copy, nonatomic) NSString *declineWording; // @synthesize declineWording=_declineWording;
@property(copy, nonatomic) NSString *detailTitle; // @synthesize detailTitle=_detailTitle;
@property(nonatomic) long long errorCode; // @synthesize errorCode=_errorCode;
@property(copy, nonatomic) NSString *errorMessage; // @synthesize errorMessage=_errorMessage;
- (void)fillWithRes:(id)arg1 scene:(unsigned long long)arg2 username:(id)arg3;
@property(nonatomic) unsigned long long footerStyleOptions; // @synthesize footerStyleOptions=_footerStyleOptions;
- (unsigned long long)generateFooterStyleOptionsWith:(id)arg1 scene:(unsigned long long)arg2 templateType:(int)arg3;
- (unsigned long long)generateHeaderStyleOptionsWith:(id)arg1 style:(int)arg2 templateType:(int)arg3;
- (id)generateMessageItemsWith:(id)arg1;
@property(nonatomic) unsigned long long headerStyleOptions; // @synthesize headerStyleOptions=_headerStyleOptions;
@property(copy, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
- (id)initWith:(id)arg1 scene:(unsigned long long)arg2 username:(id)arg3;
@property(nonatomic) _Bool keepOption; // @synthesize keepOption=_keepOption;
@property(copy, nonatomic) NSString *keepOptionWording; // @synthesize keepOptionWording=_keepOptionWording;
@property(retain, nonatomic) NSString *kvUid; // @synthesize kvUid=_kvUid;
@property(copy, nonatomic) NSString *mainDescription; // @synthesize mainDescription=_mainDescription;
@property(copy, nonatomic) NSArray *messageItems; // @synthesize messageItems=_messageItems;
- (_Bool)needsToShowPageSheet;
@property(nonatomic) unsigned long long operationType; // @synthesize operationType=_operationType;
@property(nonatomic) unsigned long long scene; // @synthesize scene=_scene;
@property(retain, nonatomic) SubscribeMsgShowInfo *showInfo; // @synthesize showInfo=_showInfo;
@property(nonatomic) int style; // @synthesize style=_style;
@property(copy, nonatomic) NSString *subDescription; // @synthesize subDescription=_subDescription;
@property(nonatomic) int templateType; // @synthesize templateType=_templateType;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
- (void)toInfoButtonClickReportStringResultBlock:(CDUnknownBlockType)arg1;
- (id)toMsgItemsReportString;
- (id)toUIData;

@end

