//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "MMWebImageViewDelegate.h"

@class MMUIButton, MMUILabel, MMWebImageView, NSObject<WAWebErrorViewDelegate>, NSString, UIButton, WAContact;

@interface WAWebErrorView : MMUIView <MMWebImageViewDelegate>
{
    WAContact *m_contact;
    NSString *m_title;
    NSString *m_desc;
    NSString *m_buttonTitle;
    MMUILabel *m_descLabel;
    MMUIButton *_quitButton;
    _Bool m_isNeedGray;
    MMWebImageView *m_logoView;
    MMUILabel *m_titleLabel;
    UIButton *m_operationButton;
    NSObject<WAWebErrorViewDelegate> *_delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak NSObject<WAWebErrorViewDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)initDescLabel;
- (void)initLogoView;
- (void)initOperationButton;
- (void)initTitleLabel;
- (id)initWithUserName:(id)arg1 title:(id)arg2 desc:(id)arg3;
- (id)initWithUserName:(id)arg1 title:(id)arg2 desc:(id)arg3 buttonTitle:(id)arg4 needGrayed:(_Bool)arg5;
- (void)layoutSubviews;
- (void)onClickQuitButton;
- (void)onLoadImageOK:(id)arg1;
- (void)onOperationButtonTapped:(id)arg1;
- (void)showQuitButton;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

