//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCAccountBaseViewController.h"

#import "CountryCodePickerDelegate.h"
#import "ILinkEventExt.h"
#import "UITextFieldDelegate.h"

@class CountryCodeWrap, NSMutableArray, NSString, PhoneNumberFormatLogic, UIButton, UIView, WCAccountTextFieldItem, WCBaseKeyboardToolBar;

@interface WCAccountMainLoginViewController : WCAccountBaseViewController <CountryCodePickerDelegate, UITextFieldDelegate, ILinkEventExt>
{
    id <WCAccountMainLoginViewControllerDelegate> _delegate;
    UIView *_phoneHeaderView;
    WCAccountTextFieldItem *_textFieldCountryCodeSelectItem;
    WCAccountTextFieldItem *_textFieldCountryCodeItem;
    WCAccountTextFieldItem *_textFieldPhoneNumberItem;
    PhoneNumberFormatLogic *_phoneNumFormatter;
    CountryCodeWrap *_curCountryCode;
    UIView *_userHeaderView;
    WCAccountTextFieldItem *_textFieldUserNameItem;
    WCAccountTextFieldItem *_textFieldUserPwdItem;
    WCBaseKeyboardToolBar *_keyboardBar;
    UIButton *_btnNext;
    unsigned long long _enLoginType;
    _Bool _bInSwitchAnimation;
    UIView *m_oBottomView;
    NSMutableArray *m_moreBtnArr;
    _Bool _bShouldShowBackBtn;
    _Bool _bShowPhoneLoginViewFirst;
}

- (void).cxx_destruct;
- (void)CountryCodePickerDidPickCountryCode:(id)arg1;
- (void)WCBaseInfoItemBeginEdit:(id)arg1;
- (void)WCBaseInfoItemEditChanged:(id)arg1;
- (void)WCBaseInfoItemEndEdit:(id)arg1;
- (void)WCBaseInfoItemPressReturnKey:(id)arg1;
@property(nonatomic) _Bool bShouldShowBackBtn; // @synthesize bShouldShowBackBtn=_bShouldShowBackBtn;
@property(nonatomic) _Bool bShowPhoneLoginViewFirst; // @synthesize bShowPhoneLoginViewFirst=_bShowPhoneLoginViewFirst;
- (void)checkNextBtnEnable;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)findCountryCode;
- (id)init;
- (void)initMoreView;
- (void)initTableView;
- (void)onBothDeviceClicked;
- (void)onNext;
- (void)onSwitch;
- (void)setDelegate:(id)arg1;
- (void)setupWithData:(id)arg1;
- (void)showCountryCode;
- (void)showCountryCodePickerView;
- (void)showFooterViewWithSwitchBtnTitle:(id)arg1 loginBtnTitle:(id)arg2;
- (void)showPhoneLoginFooter;
- (void)showUserLoginFooter;
- (void)switchToPhoneLogin;
- (void)switchToUserLogin;
- (_Bool)useGrayBackgroundColor;
- (void)userDidClickBack;
- (void)userDidClickMore;
- (void)vcResignFirstResponder;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

