//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface WCADAtFriendCompatible : NSObject <NSCoding>
{
    unsigned int _minVersion;
    unsigned int _maxVersion;
    NSString *_jumpUrl;
}

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (_Bool)isCompatible;
@property(retain, nonatomic) NSString *jumpUrl; // @synthesize jumpUrl=_jumpUrl;
@property(nonatomic) unsigned int maxVersion; // @synthesize maxVersion=_maxVersion;
@property(nonatomic) unsigned int minVersion; // @synthesize minVersion=_minVersion;

@end

