//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIPopoverPresentationControllerDelegate.h"

@class NSString, UIPickerView, UIView, UIViewController;

@interface WCBizPickerView : NSObject <UIPopoverPresentationControllerDelegate>
{
    UIPickerView *m_pickerView;
    id <WCBizPickerViewDelegate> _m_delegate;
    UIView *_contentView;
    UIView *_transparentView;
    UIViewController *_contentVC;
    long long _lastOri;
}

+ (struct CGSize)getPickerViewSize;
- (void).cxx_destruct;
- (void)UIPickerViewDidCancel;
- (void)UIPickerViewDidFinish;
- (long long)adaptivePresentationStyleForPresentationController:(id)arg1;
@property(retain, nonatomic) UIViewController *contentVC; // @synthesize contentVC=_contentVC;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
- (void)dealloc;
- (void)didRotate:(id)arg1;
- (void)dismissWithAnimated:(_Bool)arg1;
- (void)handleTap:(id)arg1;
- (id)initWithDelegate:(id)arg1;
@property(nonatomic) long long lastOri; // @synthesize lastOri=_lastOri;
@property(nonatomic) __weak id <WCBizPickerViewDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
- (void)reloadComponent:(long long)arg1;
- (void)removeAllPickerViewDelegate;
- (void)setSelectedRow:(long long)arg1 Component:(long long)arg2;
@property(retain, nonatomic) UIView *transparentView; // @synthesize transparentView=_transparentView;
- (void)showInView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

