//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@interface WCCardSecondaryView : MMUIView
{
    id <WCCardDataSource> _cardDataSource;
    id <WCCardSecondaryViewDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) __weak id <WCCardSecondaryViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)fieldClicked:(id)arg1;
- (id)initWithCardDataSource:(id)arg1;
- (void)layoutSubviews;

@end

