//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface WCDBManager : NSObject
{
    struct map<WCDBTag, WCDBRouterInfo *, std::__1::less<WCDBTag>, std::__1::allocator<std::__1::pair<const WCDBTag, WCDBRouterInfo *>>> _taggedRouterInfos;
    struct set<WCDBTag, std::__1::less<WCDBTag>, std::__1::allocator<WCDBTag>> _criticalRouterTags;
    struct set<WCDBTag, std::__1::less<WCDBTag>, std::__1::allocator<WCDBTag>> _retrievableTags;
    map_845d5abd _idkey;
    _Bool _showWhereDatabase;
    NSArray *_routerInfos;
}

+ (void)report:(id)arg1;
+ (void)safeInvokeProgressHandler:(CDUnknownBlockType)arg1 withProgress:(double)arg2 andIncrement:(double)arg3;
+ (id)shared;
+ (void)tryReportIDKey:(id)arg1;
+ (void)tryReportKV:(id)arg1;
+ (void)tryReportRetrieverSummary:(id)arg1;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)asyncShowUsageForDatabase:(int)arg1 withCompleteHandler:(CDUnknownBlockType)arg2;
- (void)clearInitMark;
- (_Bool)containsDeposited;
- (void)enableIdleTimer:(_Bool)arg1;
- (void)enableNewSync:(_Bool)arg1;
- (void)enableTraceForDatabase:(int)arg1;
- (void)exitApplication;
- (id)getAndCheckCorruptedDatabaseInfos;
- (id)getCorruptedCriticalDatabaseInfos;
- (id)getRetrievableDatabaseInfos;
- (const map_845d5abd *)idkey;
- (id)initOnce;
- (_Bool)isCriticalRouter:(int)arg1;
- (void)onIPxx:(id)arg1;
- (_Bool)recover:(id)arg1 withProgressHandler:(CDUnknownBlockType)arg2;
- (_Bool)removeDepositedDatabase;
- (_Bool)rollbackBrandMsgDatabase:(CDUnknownBlockType)arg1;
- (_Bool)rollbackMessageDatabase:(CDUnknownBlockType)arg1;
- (id)routerInfoWithTag:(int)arg1;
@property(readonly, nonatomic) NSArray *routerInfos; // @synthesize routerInfos=_routerInfos;
@property _Bool showWhereDatabase; // @synthesize showWhereDatabase=_showWhereDatabase;
- (_Bool)shouldAutoMigrateBrandMsgDatabase;
- (_Bool)shouldAutoMigrateMMDB;
- (_Bool)shouldMainDatabaseUseNewBackup;
- (_Bool)shouldMainDatabaseUseNewRecover;
- (_Bool)shouldSplitBrandMsgDatabase;
- (_Bool)shouldSplitMMDB;
- (_Bool)shouldVacuum;

@end

