//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "ICdnComMgrExt.h"
#import "IMsgExt.h"
#import "MMService.h"

@class NSObject<OS_dispatch_queue>, NSString;

@interface WCDumpFileMgr : MMService <IMsgExt, ICdnComMgrExt, MMService>
{
    NSObject<OS_dispatch_queue> *_workQueue;
    struct map<std::__1::basic_string<char>, __WCSN::WCSDumpFileContext_s, std::__1::less<std::__1::basic_string<char>>, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, __WCSN::WCSDumpFileContext_s>>> _dicDumpFileContext;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)OnCdnUpload:(id)arg1;
- (void)OnGetNewXmlMsg:(id)arg1 Type:(id)arg2 MsgWrap:(id)arg3;
- (void)dealloc;
- (vector_a94cd8cb)dumpAllIllegal:(struct WCSDumpFileContext_s)arg1;
- (void)dumpFile:(id)arg1;
- (struct WCSDumpFileContext_s)dumpSingle:(struct WCSDumpFileContext_s)arg1;
- (id)init;
- (void)onServiceTerminate;
- (void)reportFail:(struct WCSDumpFileContext_s)arg1;
- (void)reportFileInfo:(id)arg1 withContext:(struct WCSDumpFileContext_s)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

