//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MMTableView, NSArray, NSString, WCGiftCardData;

@interface WCMultiGiftPersonView : MMUIView <UITableViewDelegate, UITableViewDataSource>
{
    double _maxWidth;
    double _minHeight;
    WCGiftCardData *_giftCardData;
    MMTableView *_giftTableView;
    NSArray *_accepterList;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *accepterList; // @synthesize accepterList=_accepterList;
- (void)configTableSize;
- (id)createTableViewHeaderView;
@property(retain, nonatomic) WCGiftCardData *giftCardData; // @synthesize giftCardData=_giftCardData;
@property(retain, nonatomic) MMTableView *giftTableView; // @synthesize giftTableView=_giftTableView;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) double maxWidth; // @synthesize maxWidth=_maxWidth;
@property(nonatomic) double minHeight; // @synthesize minHeight=_minHeight;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

