//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "AccessCardLogicDelegate.h"
#import "MMTipsViewControllerDelegate.h"
#import "SessionSelectControllerDelegate.h"
#import "ShareMessageConfirmLogicHelperDelegate.h"
#import "WCActionSheetDelegate.h"
#import "WCCardGeneralCardContentDelegate.h"
#import "WCCardInvoiceCardContentViewDelegate.h"
#import "WCCardMemberCardContentDelegate.h"
#import "WCCardNewTicketContentDelegate.h"
#import "WCGroupTagViewControllerDelegate.h"
#import "WCNewCardDetailLogicDelegate.h"
#import "WCNewShareCardConsumedViewDelegate.h"
#import "WCShareCardCodeViewDelegate.h"
#import "WCShareCardUserListViewControllerDelegate.h"

@class AccessCardLogicController, MMToastViewController, NSIndexPath, NSMutableArray, NSString, ShareMessageConfirmLogicHelper, UIScrollView, WCActionSheet, WCCardBaseCardDetailContentView, WCNewCardDetailLogicController, WCNewShareCardConsumedView, WCShareCardCodeView;

@interface WCNewCardDetailViewController : MMUIViewController <WCNewCardDetailLogicDelegate, WCActionSheetDelegate, MMTipsViewControllerDelegate, WCNewShareCardConsumedViewDelegate, SessionSelectControllerDelegate, ShareMessageConfirmLogicHelperDelegate, WCShareCardCodeViewDelegate, WCCardGeneralCardContentDelegate, WCCardMemberCardContentDelegate, WCShareCardUserListViewControllerDelegate, WCGroupTagViewControllerDelegate, WCCardInvoiceCardContentViewDelegate, AccessCardLogicDelegate, WCCardNewTicketContentDelegate>
{
    AccessCardLogicController *_accessCardLogic;
    _Bool _isFromScanQRCode;
    _Bool _isPresent;
    _Bool _hiddenRightBar;
    _Bool _hiddenUserHeaderView;
    _Bool _hiddenDeleteItem;
    _Bool _isFromShareCardList;
    _Bool _isFromGiftCard;
    _Bool _isAddCard;
    _Bool _bIsFromSDKAuth;
    _Bool _bHideAcceptBtn;
    _Bool _bIsGetConsumedReward;
    _Bool _bHasTryShowConsumedView;
    _Bool _bIsStartResumeFromShareCardCodeView;
    _Bool _bIsEndResumeFromShareCardCodeView;
    _Bool _bIsOpenOperationView;
    _Bool _bIsOpenOffinePayView;
    _Bool _bIsSelectTagGroup;
    id <WCNewCardDetailViewControllerDelegate> _delegate;
    NSIndexPath *_lastIndex;
    unsigned long long _appBrandModeType;
    WCNewCardDetailLogicController *_logicController;
    NSString *_shareToUsername;
    ShareMessageConfirmLogicHelper *_shareToFriendHelper;
    WCActionSheet *_actionSheet;
    WCCardBaseCardDetailContentView *_curContentView;
    UIScrollView *_emptyContentView;
    MMToastViewController *_toastVC;
    WCShareCardCodeView *_cardCodeView;
    WCNewShareCardConsumedView *_consumedView;
    NSMutableArray *_arrGroupUser;
    NSMutableArray *_arrBlackUser;
    NSMutableArray *_arrGroupUserLabelID;
    NSMutableArray *_arrBlackUserLabelID;
    long long _currentTipViewIndex;
}

- (void).cxx_destruct;
- (void)GroupTagViewControllerWillDissappear;
- (void)OnSelectSession:(id)arg1 SessionSelectController:(id)arg2;
- (void)OnSelectSessionCancel:(id)arg1;
- (void)OnSendMessageOK:(id)arg1;
- (void)actionFromSvrActionSheet:(id)arg1;
@property(retain, nonatomic) WCActionSheet *actionSheet; // @synthesize actionSheet=_actionSheet;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
@property(nonatomic) unsigned long long appBrandModeType; // @synthesize appBrandModeType=_appBrandModeType;
@property(retain, nonatomic) NSMutableArray *arrBlackUser; // @synthesize arrBlackUser=_arrBlackUser;
@property(retain, nonatomic) NSMutableArray *arrBlackUserLabelID; // @synthesize arrBlackUserLabelID=_arrBlackUserLabelID;
@property(retain, nonatomic) NSMutableArray *arrGroupUser; // @synthesize arrGroupUser=_arrGroupUser;
@property(retain, nonatomic) NSMutableArray *arrGroupUserLabelID; // @synthesize arrGroupUserLabelID=_arrGroupUserLabelID;
@property(nonatomic) _Bool bHasTryShowConsumedView; // @synthesize bHasTryShowConsumedView=_bHasTryShowConsumedView;
@property(nonatomic) _Bool bHideAcceptBtn; // @synthesize bHideAcceptBtn=_bHideAcceptBtn;
- (_Bool)bIsCardFromOutAppScene;
@property(nonatomic) _Bool bIsEndResumeFromShareCardCodeView; // @synthesize bIsEndResumeFromShareCardCodeView=_bIsEndResumeFromShareCardCodeView;
@property(nonatomic) _Bool bIsFromSDKAuth; // @synthesize bIsFromSDKAuth=_bIsFromSDKAuth;
@property(nonatomic) _Bool bIsGetConsumedReward; // @synthesize bIsGetConsumedReward=_bIsGetConsumedReward;
@property(nonatomic) _Bool bIsOpenOffinePayView; // @synthesize bIsOpenOffinePayView=_bIsOpenOffinePayView;
@property(nonatomic) _Bool bIsOpenOperationView; // @synthesize bIsOpenOperationView=_bIsOpenOperationView;
@property(nonatomic) _Bool bIsSelectTagGroup; // @synthesize bIsSelectTagGroup=_bIsSelectTagGroup;
@property(nonatomic) _Bool bIsStartResumeFromShareCardCodeView; // @synthesize bIsStartResumeFromShareCardCodeView=_bIsStartResumeFromShareCardCodeView;
- (_Bool)canShowUseBtnInHeader;
@property(retain, nonatomic) WCShareCardCodeView *cardCodeView; // @synthesize cardCodeView=_cardCodeView;
- (void)clickEnterUserListBtn;
@property(retain, nonatomic) WCNewShareCardConsumedView *consumedView; // @synthesize consumedView=_consumedView;
@property(retain, nonatomic) WCCardBaseCardDetailContentView *curContentView; // @synthesize curContentView=_curContentView;
@property(nonatomic) long long currentTipViewIndex; // @synthesize currentTipViewIndex=_currentTipViewIndex;
- (void)dealloc;
@property(nonatomic) __weak id <WCNewCardDetailViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deleteCard;
- (void)deleteCardAlertViewConfirmClick;
- (void)deleteShareCard;
- (void)deleteShareCardAlertViewConfirmClick;
- (void)doOpenOperationView:(double)arg1;
- (void)doOperation:(double)arg1;
@property(retain, nonatomic) UIScrollView *emptyContentView; // @synthesize emptyContentView=_emptyContentView;
- (id)getBrandColor;
- (int)getCardStatus;
- (id)getContollerTitle;
- (id)getDynamicCode;
- (id)getDynamicCodeGenerator;
- (id)getGiftCardShareFromUserName;
- (id)getOfflineCode;
- (unsigned int)getOfflineCodeStatus;
- (unsigned long long)getShareCardShareUserCount;
- (id)getShareCardShareUserName;
- (id)getSubImage:(struct CGRect)arg1 inImage:(id)arg2;
- (id)getUsedStoreList;
- (double)getViewControllerContentViewHeight;
- (void)giftCardToFriend;
- (_Bool)hasBrandColor;
- (_Bool)hasEnterCardDetailBefore;
- (_Bool)hasShowMemberCardTip;
- (_Bool)hasShowShareCardTipsBefore;
@property(nonatomic) _Bool hiddenDeleteItem; // @synthesize hiddenDeleteItem=_hiddenDeleteItem;
@property(nonatomic) _Bool hiddenRightBar; // @synthesize hiddenRightBar=_hiddenRightBar;
@property(nonatomic) _Bool hiddenUserHeaderView; // @synthesize hiddenUserHeaderView=_hiddenUserHeaderView;
- (void)hidePresentNavigation:(_Bool)arg1;
- (void)initContentView;
- (void)initEmptyView;
- (id)initWithCardEnterInfo:(id)arg1;
- (id)initWithShareCard:(id)arg1 withShareCardListIfExist:(id)arg2 andScene:(int)arg3;
@property(nonatomic) _Bool isAddCard; // @synthesize isAddCard=_isAddCard;
@property(nonatomic) _Bool isFromGiftCard; // @synthesize isFromGiftCard=_isFromGiftCard;
@property(nonatomic) _Bool isFromScanQRCode; // @synthesize isFromScanQRCode=_isFromScanQRCode;
@property(nonatomic) _Bool isFromShareCardList; // @synthesize isFromShareCardList=_isFromShareCardList;
- (_Bool)isNeedToDisplayDeeplinkJunmpTips;
@property(nonatomic) _Bool isPresent; // @synthesize isPresent=_isPresent;
- (void)jumpToContactInfoViewController:(id)arg1;
@property(retain, nonatomic) NSIndexPath *lastIndex; // @synthesize lastIndex=_lastIndex;
@property(retain, nonatomic) WCNewCardDetailLogicController *logicController; // @synthesize logicController=_logicController;
- (id)navigationBarBackgroundColor;
- (void)onAcceptCardBtnClick:(_Bool)arg1;
- (void)onAcceptCardRet:(_Bool)arg1 withLoadingStr:(id)arg2 withAcceptInfoJsonStr:(id)arg3 isShareCard:(_Bool)arg4;
- (void)onCardHasBeenUsed:(id)arg1;
- (void)onCardHeaderViewApplyBtnClick;
- (void)onCardHeaderViewOperateBtnClick;
- (void)onClickEnterUserListBtn;
- (void)onClickMemberCardAnnounce:(id)arg1;
- (void)onClickNearbyPhoneBtn;
- (void)onClickNotifyBtn:(_Bool)arg1;
- (void)onClickTipsBtn:(id)arg1 Index:(long long)arg2 tipTag:(long long)arg3;
- (void)onClickWhoCanSeeBtn;
- (void)onCloseCodeView;
- (void)onCloseLargeView;
- (void)onCurShareCardUpdate:(id)arg1;
- (void)onGetCardDataFromSvrErr:(int)arg1;
- (void)onGetOfflineCodeError;
- (void)onGiftCardRet:(int)arg1 cardData:(id)arg2;
- (void)onMarkShareCardError;
- (void)onMarkShareCardWithRet:(_Bool)arg1 isMark:(_Bool)arg2 andMarkUsr:(id)arg3 markCardId:(id)arg4 expireTime:(float)arg5 qrCodeWording:(id)arg6;
- (void)onPayButtonDidClick;
- (void)onReasonButtonClick;
- (void)onReturn;
- (void)onSelectShareUserWithShareData:(id)arg1;
- (void)onShareCardAfterConsumed:(_Bool)arg1;
- (void)onShareCardBtnClick;
- (void)onShareCardConsumedWithShareCardTpInfoList:(id)arg1 shareCardId:(id)arg2 consumedBoxId:(id)arg3 subscribeAppUserName:(id)arg4 subscribeWording:(id)arg5 retMsg:(id)arg6;
- (void)onShareCardDataNotPrepare;
- (void)onShareCardDelete:(_Bool)arg1 withShareCard:(id)arg2;
- (void)onShareCardReqRetSystemErr:(_Bool)arg1;
- (void)onShareCardReqRetWithCardInfo:(id)arg1;
- (void)onShareCardSuccessWithCardData:(id)arg1;
- (void)onShowShareCardTips;
- (void)onShowTipsAndReloadData;
- (void)onUserAuthorizedLocationWithCardID:(id)arg1;
- (void)onViewControllerAllContentNeedReload;
- (void)onViewControllerNeedReload;
- (void)openAppBranWithUserName:(id)arg1 brandPass:(id)arg2;
- (void)openBrandProfileView;
- (void)openCardDetailView;
- (void)openCellList0Item:(id)arg1;
- (void)openGiftCardInfoViewConroller;
- (void)openNearbyShopInfo;
- (void)openOperationView;
- (void)openSecondaryField:(id)arg1;
- (void)openUrl:(id)arg1;
- (void)openUrl:(id)arg1 returnBlock:(CDUnknownBlockType)arg2;
- (void)openUsedStoresView;
- (void)payOrQrCodeButtonDidClick;
- (void)phoneCallAlertViewConfirmClick;
- (id)processCurrentScreenShot;
- (void)recommendToFriend;
- (void)refreshCode;
- (void)refreshIfOfflineCodeScheme;
- (void)reloadContentView;
- (void)reloadViewController;
- (void)reloadViewControllerBackgroundColor;
- (void)setForBatchViewCard;
- (void)setHasEnterCardDetailBefore;
- (void)setHasEnterShareCardListBefore;
- (void)setHasShowMemberCardTip;
- (void)setHasShowShareCardTipsBefore;
@property(retain, nonatomic) ShareMessageConfirmLogicHelper *shareToFriendHelper; // @synthesize shareToFriendHelper=_shareToFriendHelper;
@property(retain, nonatomic) NSString *shareToUsername; // @synthesize shareToUsername=_shareToUsername;
@property(retain, nonatomic) MMToastViewController *toastVC; // @synthesize toastVC=_toastVC;
- (void)shareCardAction;
- (void)shareToFriend;
- (void)shareToSNS;
- (_Bool)shouldHideAcceptBtn;
- (_Bool)shouldRefreshWithShareCard;
- (_Bool)shouldShowGiftFromUserHeaderView;
- (void)showActionList;
- (void)showAdd2CardPkgTip;
- (void)showBrandProfile;
- (void)showCodeView;
- (void)showEmptyView;
- (void)showErrMsg;
- (void)showFirstUseShareCardTip;
- (void)showJsonView;
- (void)showReportView;
- (void)showTableView;
- (void)showTipViewFor3rdDomain;
- (void)stepInOfflinePayWithExpireTime:(double)arg1;
- (void)tryUpdateAccessCard;
- (void)updateCardData:(id)arg1;
- (void)updateRightBarButtonStatus;
- (void)viewDidBeDismissed:(_Bool)arg1;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewDidPop:(_Bool)arg1;
- (void)viewDidPush:(_Bool)arg1;
- (void)viewDidTransitionToNewSize;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

