//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IWCOutCallExt.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIViewControllerAnimatedTransitioning.h"
#import "WCOutCountryCodeDelegate.h"
#import "WCOutDialPadDelegate.h"
#import "WCOutGetCallInfoDelegate.h"

@class GetWCOCallInfoResponse, MMUILabel, NSMutableString, NSString, UIButton, UILabel, WCOutDialPad, WCOutGetCallInfoCgi;

@interface WCOutDialViewController : MMUIViewController <WCOutDialPadDelegate, UIGestureRecognizerDelegate, WCOutCountryCodeDelegate, UIViewControllerAnimatedTransitioning, IWCOutCallExt, WCOutGetCallInfoDelegate>
{
    UIButton *m_deleteBtn;
    UIButton *m_countryCodeBtn;
    UILabel *m_countryNameLabel;
    UILabel *m_phoneNumLabel;
    UILabel *m_contactNameLabel;
    WCOutDialPad *m_dialPad;
    _Bool m_isEditingCountryCode;
    NSString *m_countryCodeChosen;
    NSMutableString *m_editingCountryCodeText;
    NSMutableString *m_editingPhoneText;
    NSString *m_defaultInput;
    _Bool needDisMissSelf;
    unsigned long long DialScece;
    _Bool hasUserEditFullNumber;
    _Bool hasCheckNumber;
    MMUILabel *_freeTipsLabel;
    WCOutGetCallInfoCgi *_getCallinfo;
    GetWCOCallInfoResponse *_callinfoResp;
}

- (void).cxx_destruct;
- (void)CountryCodePickerDidPickCountryCode:(id)arg1;
- (void)GetCallInfoResponse:(int)arg1 Request:(id)arg2 Response:(id)arg3;
- (void)OnCheckNumberResp:(unsigned int)arg1 RespCountryCode:(id)arg2;
- (void)OnPressedDialPadFunctionBtnWithType:(unsigned long long)arg1;
- (void)OnPressedDialPadKeyWithText:(id)arg1 andKeyCode:(int)arg2;
- (void)animateTransition:(id)arg1;
- (void)animateTransition:(id)arg1 fromVC:(id)arg2 toVC:(id)arg3 fromView:(id)arg4 toView:(id)arg5;
- (void)appendToCountryCodeTextWithNextChar:(id)arg1;
- (void)appendToInputWithNextChar:(id)arg1;
- (void)appendToInputWithText:(id)arg1;
- (void)appendToPhoneNumTextWithNextChar:(id)arg1;
- (void)beginToEditCountryCode;
@property(retain, nonatomic) GetWCOCallInfoResponse *callinfoResp; // @synthesize callinfoResp=_callinfoResp;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)checkFreeTipsLabel;
- (_Bool)checkIsEditingCountryCode:(_Bool)arg1;
- (void)chooseCountryCode;
- (void)dealloc;
- (void)didLongPressDeleteBtn:(id)arg1;
- (void)didPressedButton:(id)arg1;
@property(retain, nonatomic) MMUILabel *freeTipsLabel; // @synthesize freeTipsLabel=_freeTipsLabel;
@property(retain, nonatomic) WCOutGetCallInfoCgi *getCallinfo; // @synthesize getCallinfo=_getCallinfo;
- (void)getPackageList;
- (id)init;
- (void)initView;
- (id)initWithInput:(id)arg1 PhoneNum:(id)arg2 DialScece:(unsigned long long)arg3;
- (_Bool)isFreeCallCountry:(id)arg1;
- (id)mmNavigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (void)onCopyInputLabel;
- (void)onPasteToInputLabel;
- (void)onShowOperationMenu:(id)arg1;
- (void)openKitchen;
- (void)removeLastTextFromCountryCodeText;
- (void)removeLastTextFromInput;
- (void)removeLastTextFromPhoneNumText;
- (void)showLogWithLongPressed:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (void)updateCountryCodeAndNeedSave:(_Bool)arg1;
- (void)updatePhoneNumLabel;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillBePoped:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

