//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

@interface WCPayCreditPayFinishCreateViewController : WCPayBaseViewController
{
    id <WCPayCreditPayFinishCreateViewControllerDelegate> m_delegate;
}

- (void).cxx_destruct;
- (id)init;
- (void)initFooterView;
- (void)initHeaderView;
- (void)initNavigationBar;
- (void)onBack;
- (void)onIncreaseLimit;
- (void)setDelegate:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;

@end

