//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, WCPaySelectDateItemData;

@interface WCPayRealnameAuthenReq : NSObject
{
    NSString *_true_name;
    NSString *_cre_type;
    NSString *_cre_name;
    NSString *_identify_card;
    NSString *_identify_card_origin;
    NSString *_user_country;
    NSString *_user_province;
    NSString *_user_city;
    NSString *_profession_name;
    NSString *_profession_type;
    NSString *_birth_date;
    WCPaySelectDateItemData *_birth_date_origin;
    NSString *_cre_expire_date;
    WCPaySelectDateItemData *_cre_expire_date_origin;
    NSString *_creid_renewal;
    long long _creid_renewal_origin;
    NSString *_nationality;
    NSString *_countryCode;
}

+ (id)modelPropertyBlacklist;
- (void).cxx_destruct;
@property(retain) NSString *birth_date; // @synthesize birth_date=_birth_date;
@property(retain) WCPaySelectDateItemData *birth_date_origin; // @synthesize birth_date_origin=_birth_date_origin;
@property(retain) NSString *countryCode; // @synthesize countryCode=_countryCode;
@property(retain) NSString *cre_expire_date; // @synthesize cre_expire_date=_cre_expire_date;
@property(retain) WCPaySelectDateItemData *cre_expire_date_origin; // @synthesize cre_expire_date_origin=_cre_expire_date_origin;
@property(retain) NSString *cre_name; // @synthesize cre_name=_cre_name;
@property(retain) NSString *cre_type; // @synthesize cre_type=_cre_type;
@property(retain) NSString *creid_renewal; // @synthesize creid_renewal=_creid_renewal;
@property long long creid_renewal_origin; // @synthesize creid_renewal_origin=_creid_renewal_origin;
@property(retain) NSString *identify_card; // @synthesize identify_card=_identify_card;
@property(retain) NSString *identify_card_origin; // @synthesize identify_card_origin=_identify_card_origin;
@property(retain) NSString *nationality; // @synthesize nationality=_nationality;
@property(retain) NSString *profession_name; // @synthesize profession_name=_profession_name;
@property(retain) NSString *profession_type; // @synthesize profession_type=_profession_type;
@property(retain) NSString *true_name; // @synthesize true_name=_true_name;
@property(retain) NSString *user_city; // @synthesize user_city=_user_city;
@property(retain) NSString *user_country; // @synthesize user_country=_user_country;
@property(retain) NSString *user_province; // @synthesize user_province=_user_province;

@end

