//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

#import "WCBaseInfoItemDelegate.h"

@class NSString, UIButton, UIView, WCPayTenpayPasswordCtrlItem;

@interface WCPayNewPwdViewController : WCPayBaseViewController <WCBaseInfoItemDelegate>
{
    id <WCPayNewPwdViewControllerDelegate> m_delegate;
    _Bool _isUseFaceId;
    _Bool _canUseBiotricAuth;
    unsigned long long _authType;
    NSString *_vcPwdTitle;
    NSString *_vcPwdTips;
    NSString *_vcBiotricTitle;
    NSString *_vcTouchIdTips;
    NSString *_vcFaceIdTips;
    UIView *_verifyPasswordView;
    UIView *_verifyBiotricView;
    UIView *_currentView;
    UIButton *_footerButton;
    UIButton *_changeToBiotricAuthBtn;
    UIButton *_changeToPwdAuthBtn;
    WCPayTenpayPasswordCtrlItem *_passwordTextField;
}

- (void).cxx_destruct;
- (void)WCBaseInfoItemEditChanged:(id)arg1;
- (void)animateToPwdCtrl;
@property(nonatomic) unsigned long long authType; // @synthesize authType=_authType;
@property(nonatomic) _Bool canUseBiotricAuth; // @synthesize canUseBiotricAuth=_canUseBiotricAuth;
@property(retain, nonatomic) UIButton *changeToBiotricAuthBtn; // @synthesize changeToBiotricAuthBtn=_changeToBiotricAuthBtn;
@property(retain, nonatomic) UIButton *changeToPwdAuthBtn; // @synthesize changeToPwdAuthBtn=_changeToPwdAuthBtn;
- (void)clearPwdInput;
@property(retain, nonatomic) UIView *currentView; // @synthesize currentView=_currentView;
- (void)dealloc;
@property(retain, nonatomic) UIButton *footerButton; // @synthesize footerButton=_footerButton;
- (void)initNavigationBar;
@property(nonatomic) _Bool isUseFaceId; // @synthesize isUseFaceId=_isUseFaceId;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)onBiotricAuthNext;
- (void)onCancelVerify;
- (void)onChangeToBiotricAuth;
- (void)onChangeToPwdAuth;
@property(retain, nonatomic) WCPayTenpayPasswordCtrlItem *passwordTextField; // @synthesize passwordTextField=_passwordTextField;
- (void)refreshViewWithData:(id)arg1;
- (void)setDelegate:(id)arg1;
@property(retain, nonatomic) NSString *vcBiotricTitle; // @synthesize vcBiotricTitle=_vcBiotricTitle;
@property(retain, nonatomic) NSString *vcFaceIdTips; // @synthesize vcFaceIdTips=_vcFaceIdTips;
@property(retain, nonatomic) NSString *vcPwdTips; // @synthesize vcPwdTips=_vcPwdTips;
@property(retain, nonatomic) NSString *vcPwdTitle; // @synthesize vcPwdTitle=_vcPwdTitle;
@property(retain, nonatomic) NSString *vcTouchIdTips; // @synthesize vcTouchIdTips=_vcTouchIdTips;
@property(retain, nonatomic) UIView *verifyBiotricView; // @synthesize verifyBiotricView=_verifyBiotricView;
@property(retain, nonatomic) UIView *verifyPasswordView; // @synthesize verifyPasswordView=_verifyPasswordView;
- (void)showVerifyBiotricCtrl;
- (void)showVerifyPwdCtrl;
- (void)updateAuthView:(id)arg1 pwdTips:(id)arg2 biotricTitle:(id)arg3 touchIdTips:(id)arg4 faceIdTips:(id)arg5 canUseBiotricAuth:(_Bool)arg6;
- (void)updateBiotricCtrlWithTitle:(id)arg1 touchTips:(id)arg2 faceidTips:(id)arg3;
- (void)updatePwdCtrlWithTitle:(id)arg1 tips:(id)arg2;
- (void)updateSwitchBiotricLabel:(double)arg1;
- (_Bool)useBlackStatusbar;
- (_Bool)useTransparentNavibar;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

