//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WCPayGPUIUtil : NSObject
{
}

+ (id)genCellInputContentRichTextViewWithLinkDeleagte:(id)arg1;
+ (id)genCellInputContentTextFieldWithFrame:(struct CGRect)arg1 textFieldDelegate:(id)arg2 textFieldDidChangeTarget:(id)arg3 didChangeCallbackSelector:(SEL)arg4;
+ (id)genCellInputContentTipsLabel;
+ (id)genCenterContentLabel;
+ (id)genDecimalPadKeyboardDoneBtnToolBarWithTarget:(id)arg1 selector:(SEL)arg2;
+ (id)genNoticeButtonWithNoticeContent:(id)arg1;
+ (id)genSepDashLineViewWithContontainerWidth:(double)arg1;
+ (id)genSepLineViewWithContontainerWidth:(double)arg1;
+ (unsigned long long)getCorrectIntValueFromDouble:(double)arg1;
+ (void)limitActivityThemeContent:(id)arg1;
+ (void)setTextFieldDisplayValueShortestWithValue:(double)arg1 textField:(id)arg2;

@end

