//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayControlLogic.h"

#import "WCPayLQTCloseFundAccountCgiDelegate.h"
#import "WCPayLQTDetailViewControllerDelegate.h"
#import "WCPayLQTMoneyControlLogicDelegate.h"
#import "WCPayLQTOpenLqbAccountCgiDelegate.h"
#import "WCPayLQTQryUserFundDetailCgiDelegate.h"
#import "WCPayPayPwdViewControllerDelegate.h"
#import "WCPayRealNameTipsViewControllerDelegate.h"

@class MMTipsViewController, NSString, WCPayLQTCloseFundAccountCgi, WCPayLQTMoneyControlLogic, WCPayLQTOpenLqbAccountCgi, WCPayLQTQryUserFundDetailCgi;

@interface WCPayLQTDetailControlLogic : WCPayControlLogic <WCPayLQTDetailViewControllerDelegate, WCPayLQTQryUserFundDetailCgiDelegate, WCPayLQTCloseFundAccountCgiDelegate, WCPayPayPwdViewControllerDelegate, WCPayLQTMoneyControlLogicDelegate, WCPayLQTOpenLqbAccountCgiDelegate, WCPayRealNameTipsViewControllerDelegate>
{
    _Bool _bIsLQTFetchOrSaveSucc;
    _Bool _bHasShowRealnameGuide;
    id <WCPayLQTDetailControlLogicDelegate> _logicDelegate;
    NSString *_traceInfo;
    WCPayLQTQryUserFundDetailCgi *_qryDetailCgi;
    WCPayLQTCloseFundAccountCgi *_closeFundCgi;
    WCPayLQTMoneyControlLogic *_lqtMoneyControlLogic;
    WCPayLQTOpenLqbAccountCgi *_lqbOpenAccoutCgi;
    unsigned long long _fromScene;
    MMTipsViewController *_upgradeTipsView;
}

- (void).cxx_destruct;
- (void)OnGetBindQueryInfo:(id)arg1 Error:(id)arg2;
- (void)OnVerifyPayPassword:(id)arg1;
- (void)PayPwdBack;
- (void)PayPwdRightActionBack;
- (void)VerifyPayPwdNext:(id)arg1;
@property(nonatomic) _Bool bHasShowRealnameGuide; // @synthesize bHasShowRealnameGuide=_bHasShowRealnameGuide;
@property(nonatomic) _Bool bIsLQTFetchOrSaveSucc; // @synthesize bIsLQTFetchOrSaveSucc=_bIsLQTFetchOrSaveSucc;
- (void)clickLqbOpenAccountError;
@property(retain, nonatomic) WCPayLQTCloseFundAccountCgi *closeFundCgi; // @synthesize closeFundCgi=_closeFundCgi;
- (void)dealloc;
- (void)delayDismissViewControllerOnCloseAccount;
@property(nonatomic) unsigned long long fromScene; // @synthesize fromScene=_fromScene;
- (void)gotoLQTDetailViewControllerAndRequestData;
- (id)initWithFromScene:(unsigned long long)arg1 controlData:(id)arg2;
@property(nonatomic) __weak id <WCPayLQTDetailControlLogicDelegate> logicDelegate; // @synthesize logicDelegate=_logicDelegate;
@property(retain, nonatomic) WCPayLQTOpenLqbAccountCgi *lqbOpenAccoutCgi; // @synthesize lqbOpenAccoutCgi=_lqbOpenAccoutCgi;
@property(retain, nonatomic) WCPayLQTMoneyControlLogic *lqtMoneyControlLogic; // @synthesize lqtMoneyControlLogic=_lqtMoneyControlLogic;
- (void)onDetailViewControllerBack;
- (void)onDetailViewControllerClickDeposit;
- (void)onDetailViewControllerFetchBtnClick;
- (void)onDetailViewControllerNeedUpdateDataFromSvr;
- (void)onDetailViewControllerSaveBtnClick;
- (void)onDetailViewControllerShouldPopItem:(id)arg1 fromTransferIn:(_Bool)arg2;
- (void)onDetailViewControllerUnBindBtnClick;
- (void)onGetDetailPopItems:(id)arg1 scene:(unsigned long long)arg2;
- (void)onGetLQTCloseFundAccountResp:(id)arg1;
- (void)onGetLQTQryUserFundDetailPopItems:(id)arg1;
- (void)onGetLQTQryUserFundDetailRealnameGuideInfo:(id)arg1;
- (void)onGetLQTQryUserFundDetailResp:(id)arg1;
- (void)onGetLqbOpenAccountCgiResp:(id)arg1;
- (void)onLQTMoneyControlLogicNeedToRefreshBalanceDetail;
- (void)onLQTMoneyControlLogicNeedToRefreshLQTDetail;
- (void)onLQTMoneyControlLogicStop:(_Bool)arg1;
- (void)onLQTMoneyControlLogicUpdateTraceInfo:(id)arg1;
- (void)onPopsItemClick:(id)arg1;
@property(retain, nonatomic) WCPayLQTQryUserFundDetailCgi *qryDetailCgi; // @synthesize qryDetailCgi=_qryDetailCgi;
- (void)queryUserLQTDetailFromSvrShouldLoading:(_Bool)arg1;
- (void)queryUserLQTDetailFromSvrShouldLoading:(_Bool)arg1 loadCache:(_Bool)arg2;
- (void)realNameTipsVCDidCancel:(id)arg1;
- (void)realNameTipsVCDidConfirm:(id)arg1;
- (void)reportLQTUpgradeV2:(unsigned long long)arg1 action:(unsigned long long)arg2;
- (void)sendCloseFundAccountRequestWithPwdString:(id)arg1;
- (void)sendLqbOpenAccountRequest;
@property(retain, nonatomic) NSString *traceInfo; // @synthesize traceInfo=_traceInfo;
@property(retain) MMTipsViewController *upgradeTipsView; // @synthesize upgradeTipsView=_upgradeTipsView;
- (void)startLQTMoneyControlLogicWithMoneyScece:(unsigned long long)arg1;
- (void)startLogic;
- (void)stopLogic;
- (void)updateTraceInfo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

