//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface WCPayOpenApiMatcher : NSObject
{
    NSMutableArray *_m_matchArray;
}

+ (id)shareInstance;
- (void).cxx_destruct;
- (id)init;
@property(retain, nonatomic) NSMutableArray *m_matchArray; // @synthesize m_matchArray=_m_matchArray;
- (_Bool)matchApi:(id)arg1;

@end

