//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CContact, WCPaySelectSingleContactControlLogic;

@protocol WCPaySelectSingleContactControlLogicDelegate <NSObject>
- (void)selectSingleContactLogic:(WCPaySelectSingleContactControlLogic *)arg1 didSelectContact:(CContact *)arg2;
@end

