//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

@class NSArray, WCPayProfession;

@interface WCPayGetProfessionViewController : WCPayBaseViewController
{
    WCPayProfession *_selectedProfession;
    NSArray *_professions;
    id <WCPayGetProfessionViewControllerDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)clickInfoCell:(struct WCTableViewNormalCellManager *)arg1;
@property(nonatomic) __weak id <WCPayGetProfessionViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithProfessions:(id)arg1;
@property(retain, nonatomic) NSArray *professions; // @synthesize professions=_professions;
- (void)reloadTableView;
@property(retain, nonatomic) WCPayProfession *selectedProfession; // @synthesize selectedProfession=_selectedProfession;
- (void)viewDidLoad;

@end

