//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, WCPayOverseaGetTransferNameResponse;

@protocol WCPayOverseaGetTransferNameCgiDelegate <NSObject>
- (void)onWCPayOverseaGetTransferNameResponseBizError:(int)arg1 errorMsg:(NSString *)arg2;
- (void)onWCPayOverseaGetTransferNameResponseCgiError:(int)arg1 errorMsg:(NSString *)arg2;
- (void)onWCPayOverseaGetTransferNameResponseOK:(WCPayOverseaGetTransferNameResponse *)arg1;
@end

