//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextField.h"

@class UIView;

@interface WCPayTextField : UITextField
{
    unsigned int _showBit;
    double _tipsOffsetY;
    double _tipsOffsetX;
    UIView *_largeAmountTips;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UIView *largeAmountTips; // @synthesize largeAmountTips=_largeAmountTips;
@property(nonatomic) unsigned int showBit; // @synthesize showBit=_showBit;
@property(nonatomic) double tipsOffsetX; // @synthesize tipsOffsetX=_tipsOffsetX;
@property(nonatomic) double tipsOffsetY; // @synthesize tipsOffsetY=_tipsOffsetY;
- (void)textFieldDidChange;

@end

