//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, WCPayAddressInfo;

@interface WCPayTransferMoneyData : NSObject
{
    NSString *_receiverMaskTrueName;
    NSString *_truenameExtend;
    WCPayAddressInfo *_m_addressInfo;
    NSString *_m_addressRemark;
    NSString *_m_placeorderReserves;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCPayAddressInfo *m_addressInfo; // @synthesize m_addressInfo=_m_addressInfo;
@property(retain, nonatomic) NSString *m_addressRemark; // @synthesize m_addressRemark=_m_addressRemark;
@property(retain, nonatomic) NSString *m_placeorderReserves; // @synthesize m_placeorderReserves=_m_placeorderReserves;
@property(copy, nonatomic) NSString *receiverMaskTrueName; // @synthesize receiverMaskTrueName=_receiverMaskTrueName;
@property(copy, nonatomic) NSString *truenameExtend; // @synthesize truenameExtend=_truenameExtend;

@end

