//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "WCPlayerControlProtocol.h"
#import "WCPlayerVolumeObserverDelegate.h"

@class MMProgressViewEx, NSString, UIImageView, WCPlayerView, WCPlayerVolumeObserver, WXVideoSlider;

@interface WCPlayerControlView : UIView <WCPlayerVolumeObserverDelegate, WCPlayerControlProtocol>
{
    _Bool _isBufferingViewLoading;
    WCPlayerView *playerView;
    UIView *_coverMask;
    MMProgressViewEx *_loadingView;
    double _progress;
    WCPlayerVolumeObserver *_volumeObserver;
    WXVideoSlider *_volumeSlider;
    UIView *_volumePanel;
    UIView *_volumeBgView;
    UIImageView *_volumeIconView;
}

- (void).cxx_destruct;
- (void)addWCPlayerSubview;
@property(retain, nonatomic) UIView *coverMask; // @synthesize coverMask=_coverMask;
- (id)getVolumeIconName;
- (void)hiddenBufferingView;
- (void)hiddenPercentView;
- (void)hiddenThumbImageView;
- (void)hiddenVolumePanel;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool isBufferingViewLoading; // @synthesize isBufferingViewLoading=_isBufferingViewLoading;
- (void)layoutSubviews;
@property(retain, nonatomic) MMProgressViewEx *loadingView; // @synthesize loadingView=_loadingView;
- (void)onCreateThumbImage:(id)arg1;
- (void)onReceiveAllVideoData;
- (void)onVideoDidPlayToEndTime;
- (void)onVideoPause;
- (void)onVideoPlay;
- (void)onVideoPlayFail:(int)arg1 LocalizedErrorDes:(id)arg2;
- (void)onVideoPlayFinish;
- (void)onVideoPrepareToPlay:(id)arg1;
- (void)onVolumeDidChange:(double)arg1;
@property(nonatomic) __weak WCPlayerView *playerView; // @synthesize playerView;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(retain, nonatomic) UIView *volumeBgView; // @synthesize volumeBgView=_volumeBgView;
@property(retain, nonatomic) UIImageView *volumeIconView; // @synthesize volumeIconView=_volumeIconView;
@property(retain, nonatomic) WCPlayerVolumeObserver *volumeObserver; // @synthesize volumeObserver=_volumeObserver;
@property(retain, nonatomic) UIView *volumePanel; // @synthesize volumePanel=_volumePanel;
@property(retain, nonatomic) WXVideoSlider *volumeSlider; // @synthesize volumeSlider=_volumeSlider;
- (void)showBufferingView;
- (void)showPercentView;
- (void)showThumbImageView;
- (void)startObserveVolume;
- (void)stopObserveVolume;
- (void)updateVideoBufferPercent:(double)arg1;
- (void)updateVideoCurrentTime:(double)arg1;
- (void)updateVideoSize:(struct CGSize)arg1;
- (void)updateVideoTotalTime:(double)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

