//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCPreloadProviderDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSMutableSet, WCPreloadProvider;

@interface WCPreloadLogicMgr : NSObject <WCPreloadProviderDelegate>
{
    NSMutableArray *m_downloadItemID;
    unsigned int m_lastRefreshTime;
    id <WCPreloadLogicDelegate> m_delegate;
    WCPreloadProvider *m_dataProvider;
    unsigned int m_preloadCount;
    _Bool m_enablePreload;
    NSMutableArray *m_waitDownloadItem;
    NSMutableSet *m_setPreDownloadItemIDForBigImage;
    NSMutableSet *m_setPreDownloadItemIDForSmallImage;
    NSMutableDictionary *m_dicPrelDownloadItemNetType;
    NSMutableArray *m_videoDownloadItemID;
    NSMutableArray *m_videoWaitDownloadItem;
    unsigned int m_preloadSucFeedCountForSmallImage;
    unsigned int m_viewNewFeedCount;
    unsigned int m_preloadSucImageCountForBigImage;
    unsigned int m_viewNewBigImageCount;
    unsigned int m_preloadBigImageCount;
    unsigned long long m_latestID;
    NSMutableSet *m_setFirstClickItemIdForLogBigImage;
    NSMutableDictionary *m_dicPreDownloadItemIdToSucPreloadCnt;
    NSMutableDictionary *m_dicPreDownloadItemIdToSucPreloadPicIndexArrayStr;
}

- (void).cxx_destruct;
- (void)addBigImageCountForPreloadSuc;
- (void)addBigImageCountForViewNewBigImage;
- (void)addFeedCountForPreloadSmallImageSuc;
- (void)addFeedCountForViewNewFeeds;
- (void)addFirstClickDataItemForPreloadBigImage:(id)arg1;
- (_Bool)couldPreloadBigImage;
- (_Bool)couldPreloadImage;
- (_Bool)couldPreloadSmallImage;
- (_Bool)couldPreloadVideo;
- (void)dealloc;
- (void)downloadBatchThumb:(id)arg1;
- (void)downloadImages;
- (void)downloadMedia:(id)arg1 downloadType:(int)arg2;
- (void)downloadMedia:(id)arg1 downloadType:(int)arg2 dataItem:(id)arg3;
- (void)downloadVideos;
- (unsigned int)getCheckUpdateTimeSecs;
- (int)getCurHistoryClickRatioLimit;
- (unsigned int)getNetworkType;
- (int)getPreloadCntForItemId:(id)arg1;
- (id)getPreloadNetType:(id)arg1;
- (id)getpreloadPicIndexArrayStrForItemId:(id)arg1;
- (void)handleLatestWCObjectChanged:(id)arg1;
- (_Bool)hasFirstClickDataItemForPreloadBigImage:(id)arg1;
- (_Bool)hasPreloadDataItemForBigImage:(id)arg1;
- (_Bool)hasPreloadDataItemForSmallImage:(id)arg1;
- (id)init;
- (_Bool)isInPreloadAroundImgLimitTime;
- (_Bool)isInPreloadLimitTime;
@property(nonatomic) __weak id <WCPreloadLogicDelegate> m_delegate; // @synthesize m_delegate;
- (void)onDataUpdatedForPreload:(id)arg1 andData:(id)arg2;
- (void)preloadDataList:(id)arg1;
- (void)removeFirstClickDataItemForPreloadBigImage:(id)arg1;
- (void)removePreloadDataItemForBigImage:(id)arg1;
- (void)removePreloadDataItemForSmallImage:(id)arg1;
- (void)removeSucPreloadInfoForItemId:(id)arg1;
- (void)tryIncreaseSucPreloadCntForItemId:(id)arg1 mediaItem:(id)arg2;
- (void)tryLogPreloadImageResult;
- (void)tryPreloadData;
- (void)updateStatusForPreload:(_Bool)arg1;

@end

