//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSMutableDictionary;

@interface WCSnsLocalCacheMgr : MMObject
{
    _Bool m_hadLoadedCache;
    NSMutableDictionary *m_dicLocalCache;
}

- (void).cxx_destruct;
- (void)callServiceEnterBackground;
- (void)callServiceInit;
- (void)callServiceMemoryWarning;
- (void)callServiceReload;
- (void)callServiceTerminate;
- (void)clearDelayShowInfoCache;
- (id)getSnsOperationWrapWithFeedId:(id)arg1;
- (id)getSnsOperationsWithFeedId:(id)arg1;
- (void)mergeSnsOperationsWithFeedId:(id)arg1 feedCreateTime:(unsigned int)arg2 snsOperationsData:(id)arg3;
- (id)pathForDicLocalCache;
- (void)saveDicLocalCache;
- (void)saveSnsLocalCache;
- (void)setDelayShowInfoNeedDelay:(id)arg1;
- (void)setShowTime:(unsigned int)arg1 WithFeedId:(id)arg2;
- (void)tryLoadDicLocalCache;
- (void)updateOperationsWithFeedId:(id)arg1 createTime:(unsigned int)arg2 snsOperations:(id)arg3;

@end

