//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBCoding.h"
#import "WCPlayerMediaExt.h"
#import "WCTColumnCoding.h"

@class NSString;

@interface WCStoryMediaItem : NSObject <WCPlayerMediaExt, PBCoding, WCTColumnCoding>
{
    _Bool bUseXorEncrypt;
    _Bool _notPostSucc;
    float duration;
    int createTime;
    int encIdx;
    float _preloadDuration;
    int _preloadIndex;
    NSString *tid;
    NSString *mid;
    NSString *md5;
    NSString *videoMD5;
    NSString *thumbImageUrl;
    NSString *videoUrl;
    unsigned long long xorEncrpyKey;
    unsigned long long enckey;
    NSString *token;
}

+ (int)columnTypeForWCDB;
+ (void)initialize;
+ (id)unarchiveWithWCTValue:(struct NSObject *)arg1;
- (void).cxx_destruct;
- (struct NSObject *)archivedWCTValue;
@property(nonatomic) _Bool bUseXorEncrypt; // @synthesize bUseXorEncrypt;
- (void)cleanMeidaFileCache;
- (_Bool)createTempSightPath;
@property(nonatomic) int createTime; // @synthesize createTime;
@property(readonly, copy) NSString *description;
@property(nonatomic) float duration; // @synthesize duration;
@property(nonatomic) int encIdx; // @synthesize encIdx;
@property(nonatomic) unsigned long long enckey; // @synthesize enckey;
- (id)getFormatVideoPath;
- (id)getMediaDataPath;
- (id)getMediaWrapIdentifier;
- (unsigned int)getPreloadPercent;
- (id)getTempVideoPath;
- (id)getThumbIdentifier;
- (id)getThumbImagePath;
- (id)getTmpThumbImagePath;
- (const map_f8690629 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (_Bool)hasData;
- (_Bool)hasPreview;
- (_Bool)hasSight;
- (id)init;
- (_Bool)isValid;
@property(retain, nonatomic) NSString *md5; // @synthesize md5;
@property(retain, nonatomic) NSString *mid; // @synthesize mid;
@property(nonatomic) _Bool notPostSucc; // @synthesize notPostSucc=_notPostSucc;
- (id)pathForPreview;
- (id)pathForSightData;
@property(nonatomic) float preloadDuration; // @synthesize preloadDuration=_preloadDuration;
@property(nonatomic) int preloadIndex; // @synthesize preloadIndex=_preloadIndex;
- (_Bool)saveDataFromData:(id)arg1;
- (_Bool)saveDataFromPath:(id)arg1;
- (_Bool)savePreviewFromData:(id)arg1;
- (_Bool)savePreviewFromPath:(id)arg1;
- (_Bool)saveSightDataFromData:(id)arg1;
- (_Bool)saveSightDataFromPath:(id)arg1;
@property(retain, nonatomic) NSString *thumbImageUrl; // @synthesize thumbImageUrl;
@property(retain, nonatomic) NSString *tid; // @synthesize tid;
@property(retain, nonatomic) NSString *token; // @synthesize token;
@property(retain, nonatomic) NSString *videoMD5; // @synthesize videoMD5;
@property(retain, nonatomic) NSString *videoUrl; // @synthesize videoUrl;
@property(nonatomic) unsigned long long xorEncrpyKey; // @synthesize xorEncrpyKey;
- (id)tempPathForSightData;
- (id)tmpPathForPreview;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

