//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCStoryBaseCGIObj.h"

@interface WCStoryBgmSearchCgiObj : WCStoryBaseCGIObj
{
    CDUnknownBlockType _completionBlock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
- (void)didFailWithError:(id)arg1 reponse:(id)arg2;
- (void)didGetResponse:(id)arg1;
- (id)initWithSearchId:(unsigned long long)arg1 searchKey:(id)arg2 pageOffset:(unsigned int)arg3 recommentId:(unsigned long long)arg4 completionBlock:(CDUnknownBlockType)arg5;

@end

