//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCTableViewCellManager.h"

@class WCTableViewCellNormalConfig;

@interface WCTableViewNormalCellManager : WCTableViewCellManager
{
    double titleRight;
}

+ (unsigned long long)accessoryType:(long long)arg1;
+ (struct WCTableViewNormalCellManager *)badgeCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 badge:(id)arg4;
+ (struct WCTableViewNormalCellManager *)badgeCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 badge:(id)arg4 rightValue:(id)arg5;
+ (struct WCTableViewNormalCellManager *)badgeCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 badge:(id)arg4 rightValue:(id)arg5 imageName:(id)arg6;
+ (struct WCTableViewNormalCellManager *)cellForMakeSel:(SEL)arg1 makeTarget:(id)arg2 height:(double)arg3 userInfo:(id)arg4;
+ (struct WCTableViewNormalCellManager *)editorCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 tip:(id)arg4 focus:(_Bool)arg5 autoCorrect:(_Bool)arg6 text:(id)arg7;
+ (double)getAutoSizingRightMargin:(id)arg1;
+ (struct WCTableViewNormalCellManager *)normalCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 accessoryType:(long long)arg4;
+ (struct WCTableViewNormalCellManager *)normalCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 detail:(id)arg4 imageName:(id)arg5 accessoryType:(long long)arg6;
+ (struct WCTableViewNormalCellManager *)normalCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 rightValue:(id)arg4 accessoryType:(long long)arg5;
+ (struct WCTableViewNormalCellManager *)normalCellForSel:(SEL)arg1 target:(id)arg2 title:(id)arg3 rightValue:(id)arg4 imageName:(id)arg5 accessoryType:(long long)arg6;
+ (struct WCTableViewNormalCellManager *)normalCellForTitle:(id)arg1 rightValue:(id)arg2;
+ (struct WCTableViewNormalCellManager *)normalCellForTitle:(id)arg1 rightValue:(id)arg2 imageName:(id)arg3;
+ (struct WCTableViewNormalCellManager *)urlInnerBlueCellForTitle:(id)arg1 rightValue:(id)arg2 url:(id)arg3;
+ (struct WCTableViewNormalCellManager *)urlInnerCellForTitle:(id)arg1 url:(id)arg2;
- (void)actionEditorCell:(id)arg1;
- (void)actionUrlCell;
- (void)actionUrlInnerCell;
- (void)addUserInfoValue:(id)arg1 forKey:(id)arg2;
- (double)cellHeightFor:(id)arg1;
- (double)cellSeparatorLeftInset;
- (void)configureCell:(id)arg1;
- (void)configureCell:(id)arg1 withLeftConfig:(id)arg2;
- (void)configureCell:(id)arg1 withRightConfig:(id)arg2;
- (id)getUserInfoValueForKey:(id)arg1;
- (id)init;
- (void)makeEditorCell:(id)arg1;
- (void)makeNormalCell:(id)arg1;
- (void)makeNormalCell:(id)arg1 title:(id)arg2;
- (void)switchDidChanged:(id)arg1;

// Remaining properties
@property(retain, nonatomic) WCTableViewCellNormalConfig *cellConfig; // @dynamic cellConfig;

@end

