//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCTableViewSectionManager.h"

@interface WCTableViewSingleSelectionSectionManager : WCTableViewSectionManager
{
    id <WCTableViewSingleSelectionSectionManagerDelegate> _delegate;
    long long _selectedIndex;
}

- (void).cxx_destruct;
- (void)addSelectionCell:(id)arg1;
@property(nonatomic) __weak id <WCTableViewSingleSelectionSectionManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didBeClickedAt:(id)arg1;
- (id)init;
- (void)reloadCells:(id)arg1;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;

@end

