//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString, UITableView, UIView;

@interface WCTableViewSectionManager : NSObject
{
    unsigned long long _cellMode;
    UIView *_headerView;
    UIView *_footerView;
    NSString *_headerTitle;
    NSString *_footerTitle;
    double _fHeaderHeight;
    double _fFooterHeight;
    double _fTopLineLeftInset;
    double _fBottomLineLeftInset;
    id _userInfo;
    UITableView *_tableView;
    NSMutableArray *_cells;
}

+ (id)defaultSection;
+ (id)sectionInfoDefaut;
+ (id)sectionInfoFooter:(id)arg1;
+ (id)sectionInfoFooterWithView:(id)arg1;
+ (id)sectionInfoHeader:(id)arg1;
+ (id)sectionInfoHeader:(id)arg1 Footer:(id)arg2;
+ (id)sectionInfoHeaderWithView:(id)arg1;
+ (id)sectionWithFooter:(id)arg1;
+ (id)sectionWithFooterView:(id)arg1;
+ (id)sectionWithHeader:(id)arg1;
+ (id)sectionWithHeader:(id)arg1 Footer:(id)arg2;
+ (id)sectionWithHeaderView:(id)arg1;
+ (id)sectionWithHeaderView:(id)arg1 FooterView:(id)arg2;
- (void).cxx_destruct;
- (void)addCell:(id)arg1;
@property(nonatomic) unsigned long long cellMode; // @synthesize cellMode=_cellMode;
@property(retain, nonatomic) NSMutableArray *cells; // @synthesize cells=_cells;
- (void)didBeClickedAt:(id)arg1;
@property(nonatomic) double fBottomLineLeftInset; // @synthesize fBottomLineLeftInset=_fBottomLineLeftInset;
@property(nonatomic) double fFooterHeight; // @synthesize fFooterHeight=_fFooterHeight;
@property(nonatomic) double fHeaderHeight; // @synthesize fHeaderHeight=_fHeaderHeight;
@property(nonatomic) double fTopLineLeftInset; // @synthesize fTopLineLeftInset=_fTopLineLeftInset;
@property(copy, nonatomic) NSString *footerTitle; // @synthesize footerTitle=_footerTitle;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
- (id)getCellAt:(unsigned long long)arg1;
- (unsigned long long)getCellCount;
- (id)getFooterView;
- (id)getHeaderView;
@property(copy, nonatomic) NSString *headerTitle; // @synthesize headerTitle=_headerTitle;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
- (id)init;
- (void)insertCell:(id)arg1 At:(unsigned int)arg2;
- (id)makeViewWith:(id)arg1 topPading:(double)arg2 bottomPadding:(double)arg3;
- (void)removeCellAt:(unsigned long long)arg1;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo=_userInfo;

@end

