//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIImage;

@interface WeAppCustomTabItemData : NSObject
{
    UIImage *_iconImg;
    UIImage *_selectedIconImg;
    NSString *_titleText;
    NSString *_linkUrl;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImage *iconImg; // @synthesize iconImg=_iconImg;
@property(copy, nonatomic) NSString *linkUrl; // @synthesize linkUrl=_linkUrl;
@property(retain, nonatomic) UIImage *selectedIconImg; // @synthesize selectedIconImg=_selectedIconImg;
@property(copy, nonatomic) NSString *titleText; // @synthesize titleText=_titleText;

@end

