//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"
#import "PBMessageObserverDelegate.h"

@class NSString, ReportObj16171;

@interface WePkgStatReport : MMService <MMService, PBMessageObserverDelegate>
{
    ReportObj16171 *_reportObj16171;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)kvReport13980:(id)arg1;
@property(retain, nonatomic) ReportObj16171 *reportObj16171; // @synthesize reportObj16171=_reportObj16171;
- (void)svrReport14229:(id)arg1;
- (_Bool)svrReport:(unsigned int)arg1 withLogExt:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

