//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "UIScrollViewDelegate.h"
#import "scrollViewDelegate.h"

@class MMPageControl, MMScrollView, NSString, UIImageView;

@interface WhatsnewViewController : MMUIViewController <scrollViewDelegate, UIScrollViewDelegate>
{
    id <whatsnewViewDelegateEx> m_delegate;
    MMScrollView *m_scrollView;
    unsigned long long m_uiCurrentPage;
    MMPageControl *m_pageControl;
    UIImageView *m_btnImageView;
    _Bool _m_showWithAnimation;
}

- (void).cxx_destruct;
- (void)dealloc;
- (void)enterWechat;
- (_Bool)fixPageControl;
- (void)highlightBtn;
- (void)initPageCtrl;
- (void)initPages;
- (void)initScrollView;
- (void)initView;
@property(nonatomic) __weak id <whatsnewViewDelegateEx> m_delegate; // @synthesize m_delegate;
@property(nonatomic) _Bool m_showWithAnimation; // @synthesize m_showWithAnimation=_m_showWithAnimation;
- (void)nextPage:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)stopShowWhatsNew;
- (void)touchesBegan_ScrollView:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled_ScrollView:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded_ScrollView:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved_ScrollView:(id)arg1 withEvent:(id)arg2;
- (void)unhighlightBtn;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

