//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class FavoritesItem, NSDate, RTESectionMgr, WNContentStorage, WNHtmlStringBuilder, WeNoteViewController;

@interface WNContentCache : MMObject
{
    NSDate *_modifyTime;
    FavoritesItem *_favItem;
    WNContentStorage *_wnContent;
    RTESectionMgr *_sectionMgr;
    WNHtmlStringBuilder *_htmlBuilder;
    WeNoteViewController *_openingViewControllor;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FavoritesItem *favItem; // @synthesize favItem=_favItem;
@property(retain, nonatomic) WNHtmlStringBuilder *htmlBuilder; // @synthesize htmlBuilder=_htmlBuilder;
@property(retain, nonatomic) NSDate *modifyTime; // @synthesize modifyTime=_modifyTime;
@property(nonatomic) __weak WeNoteViewController *openingViewControllor; // @synthesize openingViewControllor=_openingViewControllor;
@property(retain, nonatomic) RTESectionMgr *sectionMgr; // @synthesize sectionMgr=_sectionMgr;
@property(retain, nonatomic) WNContentStorage *wnContent; // @synthesize wnContent=_wnContent;

@end

