//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MMRefreshTableFooterDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MMTableView, MMUILabel, MMUIViewController<WSVideoPlayerViewDelegate>, NSString, UIView, WCTimeLineFooterView, WSStreamPlayerView, WSVideoFlowDataLogic, WSVideoWowCommentFloatView;

@interface WSVideoFullScreenController : NSObject <UITableViewDelegate, UITableViewDataSource, MMRefreshTableFooterDelegate>
{
    WCTimeLineFooterView *_footerView;
    WSStreamPlayerView *_transPlayerView;
    unsigned long long _transIndex;
    _Bool _hasAttachTransView;
    _Bool _isDebugingExchange;
    MMUILabel *_toastLabel;
    UIView *_toastContainer;
    WSVideoWowCommentFloatView *_wowCommentView;
    NSString *_lastPlayedNetStatus;
    _Bool _bForbidVideoInsert;
    int _dataStatus;
    MMTableView *_tableView;
    long long _curVideoIndex;
    WSStreamPlayerView *_playerView;
    WSVideoFlowDataLogic *_dataLogic;
    MMUIViewController<WSVideoPlayerViewDelegate> *_vc;
}

- (void).cxx_destruct;
- (void)MMRefreshTableFooterDidTriggerRefresh:(id)arg1;
@property(nonatomic) _Bool bForbidVideoInsert; // @synthesize bForbidVideoInsert=_bForbidVideoInsert;
@property(readonly, nonatomic) long long curVideoIndex; // @synthesize curVideoIndex=_curVideoIndex;
@property(nonatomic) __weak WSVideoFlowDataLogic *dataLogic; // @synthesize dataLogic=_dataLogic;
@property(nonatomic) int dataStatus; // @synthesize dataStatus=_dataStatus;
- (void)debugRetryNextUrl:(id)arg1;
- (void)decideNetLayer;
- (id)getCurrentCellPlayerView;
- (void)handleWowSuccess:(_Bool)arg1;
- (void)hideWowCommentFloatView;
- (void)initToastView;
- (id)initWithViewController:(id)arg1 dataLogic:(id)arg2 transPlayerView:(id)arg3;
- (_Bool)isOnDawangEnv;
- (unsigned long long)judgeNetLogicChange;
- (void)judgeWKLogic;
- (void)onUpdatePrefetchFlag:(_Bool)arg1;
- (void)playNextVideo;
@property(retain, nonatomic) WSStreamPlayerView *playerView; // @synthesize playerView=_playerView;
- (void)prepareView;
- (void)refreshVideoPlay;
- (void)reloadVideoData;
- (void)reloadVideoData:(int)arg1;
- (void)reportExpose;
- (void)resetVideoPlay;
- (void)resumeToFlow;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
@property(retain, nonatomic) MMTableView *tableView; // @synthesize tableView=_tableView;
- (void)setToastViewVisible:(_Bool)arg1;
@property(nonatomic) __weak MMUIViewController<WSVideoPlayerViewDelegate> *vc; // @synthesize vc=_vc;
- (void)showTipInfoToastWithText:(id)arg1;
- (void)showToast:(id)arg1;
- (void)showWangkaToast;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)viewDidTransitionToNewSize;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

