//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

@class MMBubbleLayer, MMScrollView, MMUIButton, MMUIImageView, MMUILabel, UITableViewCell, UIView, WSVideoFlowTableViewCell, WSVideoModel;

@interface WSVideoWowEducateViewController : MMUIViewController
{
    UIView *_coverView;
    MMScrollView *_contentFloatView;
    MMUILabel *_tipsTitleLabel;
    MMUIButton *_confirmButton;
    MMUIImageView *_tipImageView;
    MMBubbleLayer *_contentFloatViewMask;
    _Bool _needShowEduTipImageView;
    id <WSVideoWowEducateDelegate> _delegate;
    WSVideoModel *_videoModel;
    WSVideoFlowTableViewCell *_cell;
    UITableViewCell *_fromView;
}

- (void).cxx_destruct;
- (void)animatShowOnView:(id)arg1 refFrame:(struct CGRect)arg2;
- (void)animateHideWithCompleteBlock:(CDUnknownBlockType)arg1;
@property(nonatomic) __weak WSVideoFlowTableViewCell *cell; // @synthesize cell=_cell;
@property(nonatomic) __weak id <WSVideoWowEducateDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UITableViewCell *fromView; // @synthesize fromView=_fromView;
- (void)initTipImageView;
- (void)initTipsLabel;
- (void)initView;
- (void)initWowConformButton;
- (void)internalLayout;
@property(nonatomic) _Bool needShowEduTipImageView; // @synthesize needShowEduTipImageView=_needShowEduTipImageView;
- (void)onConfirm:(id)arg1;
- (void)onTapCancel:(id)arg1;
- (void)pop;
@property(retain, nonatomic) WSVideoModel *videoModel; // @synthesize videoModel=_videoModel;
- (void)smartSetAnchorPoint:(struct CGPoint)arg1 forView:(id)arg2;
- (void)viewDidLoad;

@end

