//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface WSWebRecommendPerformanceMonitor : MMService <MMService>
{
    NSObject<OS_dispatch_queue> *_monitorQueue;
    double _webRecommendTLInitTime;
    double _webRecommendTLUIBeginRenderTime;
    double _webRecommendTLBePushedTime;
    double _webRecommendTLSuperViewInitDuration;
    double _webRecommendTLUIRenderDuration;
    double _webRecommendTLUIRenderDurationFromInit;
    double _videoPageInitTime;
    double _videoRequestWebRecommendBeginTime;
    double _videoRequestWebRecommendEndTime;
    double _videoWaitForAllUrlEndFromInit;
    double _videoWaitForAllUrlEndFromFirstOne;
    NSMutableDictionary *_videoApiRequestBeginDic;
    NSMutableDictionary *_videoUrlRequestBeginDic;
    NSMutableDictionary *_videoDecideCellForUrlDic;
    double _videoPageRenderDuration;
    double _videoRequestWebRecommendDuration;
    double _videoFirstVideoPlayFromInitDuration;
    double _videoFirstVideoPlayFromRequestEndDuration;
    NSMutableDictionary *_videoApiRequestDurationDic;
    NSMutableDictionary *_videoUrlRequestDurationDic;
    NSMutableDictionary *_videoUrlPlayDurationDic;
}

- (void).cxx_destruct;
- (void)devideUploadVideoDataWithSlice:(long long)arg1 requestId:(id)arg2;
- (void)onServiceClearData;
- (void)onServiceInit;
- (_Bool)onServiceMemoryWarning;
- (void)onServiceReloadData;
- (void)onServiceTerminate;
- (void)recordVideoAverageSpeed:(double)arg1 fromUrl:(id)arg2;
- (void)recordVideoBeginDownloadFromUrl:(id)arg1;
- (void)recordVideoBeginPlayFromUrl:(id)arg1;
- (void)recordVideoDecideCellForUrl:(id)arg1;
- (void)recordVideoFlowDidAppear;
- (void)recordVideoFlowFetchVideo:(id)arg1;
- (void)recordVideoFlowFetchVideoEnd:(id)arg1 returnUrlHead:(id)arg2;
- (void)recordVideoFlowInit;
- (void)recordVideoFlowLeave;
- (void)recordVideoFlowRequestWebRecommend;
- (void)recordVideoFlowRequestWebRecommendEnd;
- (void)recordVideoFlowWaitForAllUrlEnd;
- (void)recordWebRecommendTLBePoped;
- (void)recordWebRecommendTLBePushed;
- (void)recordWebRecommendTLInit;
- (void)recordWebRecommendTLUIInit;
- (void)recordWebRecommendTLUIReady;
- (void)recordWebRecommendTLUIWillRender;
- (void)resetTLData;
- (void)resetVideoData;
- (void)sendToMonitorQueueToExcute:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) NSMutableDictionary *videoApiRequestBeginDic; // @synthesize videoApiRequestBeginDic=_videoApiRequestBeginDic;
@property(retain, nonatomic) NSMutableDictionary *videoApiRequestDurationDic; // @synthesize videoApiRequestDurationDic=_videoApiRequestDurationDic;
@property(retain, nonatomic) NSMutableDictionary *videoDecideCellForUrlDic; // @synthesize videoDecideCellForUrlDic=_videoDecideCellForUrlDic;
@property(nonatomic) double videoFirstVideoPlayFromInitDuration; // @synthesize videoFirstVideoPlayFromInitDuration=_videoFirstVideoPlayFromInitDuration;
@property(nonatomic) double videoFirstVideoPlayFromRequestEndDuration; // @synthesize videoFirstVideoPlayFromRequestEndDuration=_videoFirstVideoPlayFromRequestEndDuration;
@property(nonatomic) double videoPageInitTime; // @synthesize videoPageInitTime=_videoPageInitTime;
@property(nonatomic) double videoPageRenderDuration; // @synthesize videoPageRenderDuration=_videoPageRenderDuration;
@property(nonatomic) double videoRequestWebRecommendBeginTime; // @synthesize videoRequestWebRecommendBeginTime=_videoRequestWebRecommendBeginTime;
@property(nonatomic) double videoRequestWebRecommendDuration; // @synthesize videoRequestWebRecommendDuration=_videoRequestWebRecommendDuration;
@property(nonatomic) double videoRequestWebRecommendEndTime; // @synthesize videoRequestWebRecommendEndTime=_videoRequestWebRecommendEndTime;
@property(retain, nonatomic) NSMutableDictionary *videoUrlPlayDurationDic; // @synthesize videoUrlPlayDurationDic=_videoUrlPlayDurationDic;
@property(retain, nonatomic) NSMutableDictionary *videoUrlRequestBeginDic; // @synthesize videoUrlRequestBeginDic=_videoUrlRequestBeginDic;
@property(retain, nonatomic) NSMutableDictionary *videoUrlRequestDurationDic; // @synthesize videoUrlRequestDurationDic=_videoUrlRequestDurationDic;
@property(nonatomic) double videoWaitForAllUrlEndFromFirstOne; // @synthesize videoWaitForAllUrlEndFromFirstOne=_videoWaitForAllUrlEndFromFirstOne;
@property(nonatomic) double videoWaitForAllUrlEndFromInit; // @synthesize videoWaitForAllUrlEndFromInit=_videoWaitForAllUrlEndFromInit;
@property(nonatomic) double webRecommendTLBePushedTime; // @synthesize webRecommendTLBePushedTime=_webRecommendTLBePushedTime;
@property(nonatomic) double webRecommendTLInitTime; // @synthesize webRecommendTLInitTime=_webRecommendTLInitTime;
@property(nonatomic) double webRecommendTLSuperViewInitDuration; // @synthesize webRecommendTLSuperViewInitDuration=_webRecommendTLSuperViewInitDuration;
@property(nonatomic) double webRecommendTLUIBeginRenderTime; // @synthesize webRecommendTLUIBeginRenderTime=_webRecommendTLUIBeginRenderTime;
@property(nonatomic) double webRecommendTLUIRenderDuration; // @synthesize webRecommendTLUIRenderDuration=_webRecommendTLUIRenderDuration;
@property(nonatomic) double webRecommendTLUIRenderDurationFromInit; // @synthesize webRecommendTLUIRenderDurationFromInit=_webRecommendTLUIRenderDurationFromInit;
- (void)uploadData;
- (void)uploadTLData:(_Bool)arg1;
- (void)uploadVideoData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

