//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface WXDynamicVideoMiniProgramObject : NSObject
{
    _Bool _withShareTicket;
    NSString *_webpageUrl;
    NSString *_userName;
    NSString *_path;
    NSData *_hdImageData;
    unsigned long long _miniProgramType;
    NSString *_videoSource;
    NSString *_appThumbUrl;
}

+ (id)object;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *appThumbUrl; // @synthesize appThumbUrl=_appThumbUrl;
@property(retain, nonatomic) NSData *hdImageData; // @synthesize hdImageData=_hdImageData;
- (id)init;
@property(nonatomic) unsigned long long miniProgramType; // @synthesize miniProgramType=_miniProgramType;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(copy, nonatomic) NSString *videoSource; // @synthesize videoSource=_videoSource;
@property(copy, nonatomic) NSString *webpageUrl; // @synthesize webpageUrl=_webpageUrl;
@property(nonatomic) _Bool withShareTicket; // @synthesize withShareTicket=_withShareTicket;

@end

