//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@class NSObject<OS_dispatch_semaphore>, YYSentinel;

@interface YYImage : UIImage
{
    CDUnknownBlockType m_getBlock;
    UIImage *m_originImage;
    UIImage *m_decodeImage;
    _Bool m_isDecodingInBackground;
    NSObject<OS_dispatch_semaphore> *m_lock;
    YYSentinel *m_sentinel;
    struct CGSize _prefertSize;
}

+ (id)imageWithBlock:(CDUnknownBlockType)arg1;
+ (id)imageWithBlock:(CDUnknownBlockType)arg1 prefertSize:(struct CGSize)arg2;
+ (id)imageWithUIImage:(id)arg1;
+ (id)imageWithUIImage:(id)arg1 prefertSize:(struct CGSize)arg2;
- (void).cxx_destruct;
- (void)_cancelAsyncLoad;
- (id)_fourceDecodeImage:(id)arg1 prefertSize:(struct CGSize)arg2 isCancelled:(CDUnknownBlockType)arg3;
- (void)_loadInBackground;
- (void)asyncLoad;
- (void)dealloc;
@property(readonly, nonatomic) UIImage *decodeImage; // @synthesize decodeImage=m_decodeImage;
@property(readonly, nonatomic) UIImage *image;
- (id)initWithBlock:(CDUnknownBlockType)arg1 prefertSize:(struct CGSize)arg2;
@property(retain, nonatomic) UIImage *originImage; // @synthesize originImage=m_originImage;
@property(nonatomic) struct CGSize prefertSize; // @synthesize prefertSize=_prefertSize;
- (void)setDecodeImage:(id)arg1;

@end

