//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL, NSURLRequest, UIScrollView;

@protocol YYWebViewInterface <NSObject>
- (void)LoadHTMLString:(NSString *)arg1 baseURL:(NSURL *)arg2;
- (void)LoadRequest:(NSURLRequest *)arg1;
@property(nonatomic) _Bool allowsBackForwardNavigationGestures;
@property(nonatomic) _Bool allowsInlineMediaPlayback;
@property(readonly, nonatomic, getter=canGoBack) _Bool canGoBack;
@property(readonly, nonatomic, getter=canGoForward) _Bool canGoForward;
- (void)enableJavaScriptPopup:(_Bool)arg1;
- (void)evaluateJavaScriptFromString:(NSString *)arg1 completionBlock:(void (^)(NSString *, NSError *))arg2;
- (void)goBack;
- (void)goForward;
- (id)initWithFrame:(struct CGRect)arg1 delegate:(id <YYWebViewDelegate>)arg2;
@property(readonly, nonatomic, getter=isLoading) _Bool loading;
@property(nonatomic) _Bool mediaPlaybackRequiresUserAction;
- (void)reload;
@property(readonly, nonatomic) NSURLRequest *request;
@property(nonatomic) _Bool scalesPageToFit;
@property(readonly, nonatomic) UIScrollView *scrollView;
@property(nonatomic) __weak id <YYWebViewDelegate> wvDelegate;
- (void)stopLoading;
@end

